/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * winProduto.java
 *
 * Created on 16/07/2010, 15:50:37
 */

package br.com.caminhoneiro;

import br.com.conexao.Conexao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Jhonathas
 */
public class caminhoneiro extends javax.swing.JFrame {

    /** Creates new form winProduto */
    int navega = 0; //variavel pra saber o  botão clicado;
    private Conexao conexao;
    int inicia_combo = 0;
    private boolean state = false;

    public caminhoneiro() {
        initComponents(); //Inicializa os componentes da tela
        conexao = new Conexao();
        conexao.conecta("mil_interface");
              
        //Insere nomes do município no cbMunicipio
        try {
            conexao.execute("select * FROM tab_local where pai='Pará' or pai='Maranhão' or pai='Amapá' ");
            while (conexao.resultSet.next()){
                cbMunicipio.addItem(conexao.resultSet.getString("nome"));
                //System.out.println(conexao.resultSet.getString("nome"));
            }
        }catch (SQLException ex) {
            Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }

        conexao.execute("select * from atravessador_cadastro");

        try {
            conexao.resultSet.first();
            mostra_dados_atravessador();


        }catch (SQLException ex) {
            Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpAtravessador = new javax.swing.JPanel();
        tfIdade = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbMunicipio = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Cadastrar = new javax.swing.JButton();
        botao_excluir = new javax.swing.JButton();
        botao_novo = new javax.swing.JButton();
        botao_primeiro = new javax.swing.JButton();
        botao_anterior = new javax.swing.JButton();
        botao_proximo = new javax.swing.JButton();
        botao_ultimo = new javax.swing.JButton();
        botao_alterar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfApelido = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tfNaturalidade = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        tfAtividadePrincipal = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tfAtividadeSecundaria = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tfComposicaoFamiliar = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        tfEscolaridade = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tfPqParou = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        cbLocalMoradia = new javax.swing.JComboBox();
        cbEstadoCivil = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Questionário Atravessador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fechar_janela(evt);
            }
        });

        jpAtravessador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpAtravessador.setPreferredSize(new java.awt.Dimension(735, 538));

        jLabel22.setText("Idade.:");

        jLabel23.setText("Nome.:");

        jLabel24.setText("Município");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAction(evt);
            }
        });

        botao_excluir.setText("Excluir");
        botao_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirActionPerformed(evt);
            }
        });

        botao_novo.setText("Limpar");
        botao_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_novoActionPerformed(evt);
            }
        });

        botao_primeiro.setText("<<");
        botao_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_primeiroActionPerformed(evt);
            }
        });

        botao_anterior.setText("<");
        botao_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_anteriorActionPerformed(evt);
            }
        });

        botao_proximo.setText(">");
        botao_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_proximoActionPerformed(evt);
            }
        });

        botao_ultimo.setText(">>");
        botao_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ultimoActionPerformed(evt);
            }
        });

        botao_alterar.setText("Alterar");
        botao_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(botao_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_excluir)
                        .addGap(7, 7, 7)
                        .addComponent(botao_alterar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(botao_primeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_proximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_ultimo)))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_primeiro)
                    .addComponent(botao_anterior)
                    .addComponent(botao_proximo)
                    .addComponent(botao_ultimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_novo)
                    .addComponent(Cadastrar)
                    .addComponent(botao_excluir)
                    .addComponent(botao_alterar))
                .addContainerGap())
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel25.setText("Dados Pessoais");

        jLabel26.setText("Apelido.:");

        jLabel27.setText("Naturalidade.:");

        jLabel28.setText("Sexo.:");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        jLabel29.setText("Atividade principal de renda.:");

        jLabel30.setText("Atividade secundária.:");

        jLabel31.setText("Estado civil.:");

        jLabel32.setText("Composição Familiar.:");

        jLabel33.setText("Escolaridade.:");

        jLabel34.setText("Porque Parou?");

        jLabel35.setText("Local de Moradia.:");

        cbLocalMoradia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sede Municipal", "Comunidade/Vila local", "Outro Município", "Capital" }));

        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado", "União Estável" }));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel42.setText("Questionário Caminhoneiro");

        jLabel1.setText("Tipo de veiculo:");

        jRadioButton1.setText("Só transporta");

        jRadioButton2.setText("Transporta e comercializa");

        jCheckBox1.setText("Caminhão");

        jCheckBox2.setText("Moto");

        jCheckBox3.setText("Carro particular");

        jCheckBox4.setText("Bicicleta");

        javax.swing.GroupLayout jpAtravessadorLayout = new javax.swing.GroupLayout(jpAtravessador);
        jpAtravessador.setLayout(jpAtravessadorLayout);
        jpAtravessadorLayout.setHorizontalGroup(
            jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAtravessadorLayout.createSequentialGroup()
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox4))
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(38, 38, 38)
                                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                                    .addComponent(jLabel28)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel22)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tfIdade))
                                                .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel33))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfEscolaridade)
                                            .addComponent(tfAtividadePrincipal)
                                            .addComponent(cbEstadoCivil, 0, 196, Short.MAX_VALUE)))
                                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel34)
                                            .addComponent(jLabel32))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfPqParou)
                                            .addComponent(tfComposicaoFamiliar)
                                            .addComponent(tfAtividadeSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfApelido)
                                            .addComponent(cbLocalMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel42)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAtravessadorLayout.setVerticalGroup(
            jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAtravessadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(tfNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(cbLocalMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(tfAtividadePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(tfEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(tfAtividadeSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfComposicaoFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPqParou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jpAtravessador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-792)/2, (screenSize.height-461)/2, 792, 461);
    }// </editor-fold>//GEN-END:initComponents

    private void fechar_janela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar_janela
        conexao.desconecta();
    }//GEN-LAST:event_fechar_janela

    private void botao_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarActionPerformed
        

        try{
            String sql ="UPDATE atravessador_cadastro SET "+
                    "id_local = '"+cbMunicipio.getSelectedItem()+"',"+
                    "nome = '"+tfNome.getText()+"',"+
                    "apelido = '"+ tfApelido.getText() +"',"+
                    "naturalidade = '"+ tfNaturalidade.getText() +"',"+
                    "sexo = '"+ cbSexo.getSelectedItem() +"',"+
                    "idade = '"+ tfIdade.getText() +"',"+
                    "atividade_principal = '"+ tfAtividadePrincipal.getText() +"',"+
                    "atividade_secundaria = '"+ tfAtividadeSecundaria.getText() +"',"+
                    "estado_civil = '"+ cbEstadoCivil.getSelectedItem() +"',"+
                    "composicao_familiar = '"+ tfComposicaoFamiliar.getText() +"',"+
                    "escolaridade = '"+ tfEscolaridade.getText() +"',"+
                    "pq_parou = '"+ tfPqParou.getText() +"',"+
                    "local_moradia = '"+ cbLocalMoradia.getSelectedItem() +"',"+
//                    "qualidade_moradia = '"+ cbQualidadeMoradia.getSelectedItem() +"',"+
//                    "tipo_construcao = '"+ tfTipoConstrucao.getText() +"',"+
//                    "atividades_geram_renda = '"+ taAtividadeRendaFamilia.getText() +"',"+
//                    "atividade_entrevistado = '"+ tfEntrevistado.getText() +"',"+
//                    "atividade_esposa = '"+ tfEsposa.getText() +"',"+
//                    "atividade_filhos = '"+ tfFilhos.getText() +"',"+
//                    "atividade_netos = '"+ tfNetos.getText() +"',"+
//                    "tempo_diario_trab = '"+ tfTempoDiario.getText() +"',"+
//                    "tempo_na_atividade = '"+ tfTempoAtividade.getText() +"',"+
//                    "renda_mensal_ou_viagem = '"+ tfRendaMensal.getText() +"',"+
//                    "possui_reg_colonia = '"+ a +"',"+
//                    "qual_colonia = '"+ tfQualColonia.getText() +"',"+
//                    "na_colonia_desde = '"+ tfDesdeQuando.getText() +"' "+


                    "where id_atravessador = "+conexao.resultSet.getString("id_atravessador");

            System.out.println(sql);
            if (conexao.update(sql)){
                JOptionPane.showMessageDialog(null,"Alterado com sucesso");
                //Atualiza Resultset
                conexao.execute("select * from atravessador_cadastro");
                conexao.resultSet.next();
                mostra_dados_atravessador();
            }


        }catch (Exception e){
            System.out.println(e + "Erro no botão alterar");
        }
}//GEN-LAST:event_botao_alterarActionPerformed

    private void botao_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ultimoActionPerformed
        try {
            conexao.resultSet.last();
            mostra_dados_atravessador();


        }catch (SQLException ex) {
            Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_botao_ultimoActionPerformed

    private void botao_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_proximoActionPerformed
        try {

            conexao.resultSet.next();
            mostra_dados_atravessador();
            navega = 2;


        }catch (SQLException ex) {
            Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_botao_proximoActionPerformed

    private void botao_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_anteriorActionPerformed
        try {
            conexao.resultSet.previous();
            mostra_dados_atravessador();
            navega = 1;

        }catch (SQLException ex) {
            Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_botao_anteriorActionPerformed

    private void botao_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_primeiroActionPerformed
        try {
            conexao.resultSet.first();
            mostra_dados_atravessador();


        }catch (SQLException ex) {
            Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_botao_primeiroActionPerformed

    private void botao_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_novoActionPerformed
        tfNome.setText("");
        tfApelido.setText("");
        tfNaturalidade.setText("");
        tfIdade.setText("0");
        tfAtividadePrincipal.setText("");
        tfAtividadeSecundaria.setText("");
        cbEstadoCivil.setSelectedIndex(0);
        tfComposicaoFamiliar.setText("");
        tfEscolaridade.setText("");
        tfPqParou.setText("");
//        taAtividadeRendaFamilia.setText("");
//        tfEntrevistado.setText("");
//        tfEsposa.setText("");
//        tfFilhos.setText("");
//        tfNetos.setText("");
//        tfTempoDiario.setText("0");
//        tfTempoAtividade.setText("0");
//        tfRendaMensal.setText("0");
//        tfQualColonia.setText("");
//        tfDesdeQuando.setText("01/01/2001");
//        tfTipoConstrucao.setText("");
//
//        //System.out.println(conexao.resultSet.getString("local_moradia"));
//        chbPossuiColonia.setSelected(false);
//        cbMunicipio.setSelectedIndex(0);
//        cbSexo.setSelectedIndex(0);
//        cbLocalMoradia.setSelectedIndex(0);
//        cbQualidadeMoradia.setSelectedIndex(0);
}//GEN-LAST:event_botao_novoActionPerformed

    private void botao_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirActionPerformed
        String sql;
        try {
            sql = "select * from atravessador_cadastro Where id_atravessador =" + conexao.resultSet.getString("id_atravessador");
            conexao.execute(sql);
            conexao.resultSet.first();
            String nome = "Deletar o atravessador : "+conexao.resultSet.getString("nome")+" ?";
            int opcao_escolhida = JOptionPane.showConfirmDialog(null,nome,"Exclusão ",JOptionPane.YES_NO_OPTION);
            if (opcao_escolhida == JOptionPane.YES_OPTION) {
                sql = "DELETE FROM atravessador_cadastro Where id_atravessador ="+conexao.resultSet.getString("id_atravessador");
                if (conexao.salvar(sql)) {
                    JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso");
                    //atualiza o ResultSet
                    conexao.execute("select * from atravessador_cadastro");
                    conexao.resultSet.first();
                    mostra_dados_atravessador();
                }
            } else{
                conexao.execute("select * from atravessador_cadastro");
                conexao.resultSet.first();
                mostra_dados_atravessador();
            }

        } catch (SQLException ex) {
            System.out.println("Erro ao tentar excluir "+ex);
        }
    }//GEN-LAST:event_botao_excluirActionPerformed

    private void CadastrarAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAction
         try {
            String sqlinsert = "insert into atravessador_cadastro "
                    + "(id_local,nome,apelido,naturalidade,"
                    + "sexo,idade,atividade_principal,atividade_secundaria,"
                    + "estado_civil,composicao_familiar,escolaridade,pq_parou,"
                    + "local_moradia,qualidade_moradia,tipo_construcao,"
                    + "atividades_geram_renda,atividade_entrevistado,"
                    + "atividade_esposa,atividade_filhos,atividade_netos,"
                    + "tempo_diario_trab,tempo_na_atividade,"
                    + "renda_mensal_ou_viagem,possui_reg_colonia,qual_colonia,"
                    + "na_colonia_desde) values ('"+
                    cbMunicipio.getSelectedItem()+"','"+
                    tfNome.getText()+"','"+
                    tfApelido.getText()+"','"+
                    tfNaturalidade.getText()+"','"+
                    cbSexo.getSelectedItem()+"',"+
                    tfIdade.getText()+",'"+
                    tfAtividadePrincipal.getText()+"','"+
                    tfAtividadeSecundaria.getText()+"','"+
                    cbEstadoCivil.getSelectedItem()+"','"+
                    tfComposicaoFamiliar.getText()+"','"+
                    tfEscolaridade.getText()+"','"+
                    tfPqParou.getText()+"','"+
                    cbLocalMoradia.getSelectedItem()+"','";
//                    cbQualidadeMoradia.getSelectedItem()+"','"+
//                    tfTipoConstrucao.getText()+"','"+
//                    taAtividadeRendaFamilia.getText()+"','"+
//                    tfEntrevistado.getText()+"','"+
//                    tfEsposa.getText()+"','"+
//                    tfFilhos.getText()+"','"+
//                    tfNetos.getText()+"','"+
//                    tfTempoDiario.getText()+"','"+
//                    tfTempoAtividade.getText()+"','"+
//                    tfRendaMensal.getText()+"',"+
//                    a+",'"+
//                    tfQualColonia.getText()+"','"+
//                    tfDesdeQuando.getText()+"')";

            //System.out.println(sqlinsert);

            if (conexao.salvar(sqlinsert)) {
                JOptionPane.showMessageDialog(null,"Cadastrado com sucesso");
                //agora é hora de atualizar o resultset
                conexao.execute("select * from atravessador_cadastro");
                conexao.resultSet.first(); //1º registro
                mostra_dados_atravessador();
            }


        }catch (SQLException erro){
            System.out.println(erro);
        }
}//GEN-LAST:event_CadastrarAction

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frm_atravessador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton botao_alterar;
    private javax.swing.JButton botao_anterior;
    private javax.swing.JButton botao_excluir;
    private javax.swing.JButton botao_novo;
    private javax.swing.JButton botao_primeiro;
    private javax.swing.JButton botao_proximo;
    private javax.swing.JButton botao_ultimo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbEstadoCivil;
    private javax.swing.JComboBox cbLocalMoradia;
    private javax.swing.JComboBox cbMunicipio;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpAtravessador;
    private javax.swing.JTextField tfApelido;
    private javax.swing.JTextField tfAtividadePrincipal;
    private javax.swing.JTextField tfAtividadeSecundaria;
    private javax.swing.JTextField tfComposicaoFamiliar;
    private javax.swing.JTextField tfEscolaridade;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JTextField tfNaturalidade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPqParou;
    // End of variables declaration//GEN-END:variables


    public void mostra_dados_atravessador(){
        try {

            tfNome.setText(conexao.resultSet.getString("nome"));
            tfApelido.setText(conexao.resultSet.getString("apelido"));
            tfNaturalidade.setText(conexao.resultSet.getString("naturalidade"));
            tfIdade.setText(conexao.resultSet.getString("idade"));
            tfAtividadePrincipal.setText(conexao.resultSet.getString("atividade_principal"));
            tfAtividadeSecundaria.setText(conexao.resultSet.getString("atividade_secundaria"));
            cbEstadoCivil.setSelectedItem(conexao.resultSet.getString("estado_civil"));
            tfComposicaoFamiliar.setText(conexao.resultSet.getString("composicao_familiar"));
            tfEscolaridade.setText(conexao.resultSet.getString("escolaridade"));
            tfPqParou.setText(conexao.resultSet.getString("pq_parou"));
//            taAtividadeRendaFamilia.setText(conexao.resultSet.getString("atividades_geram_renda"));
//            tfEntrevistado.setText(conexao.resultSet.getString("atividade_entrevistado"));
//            tfEsposa.setText(conexao.resultSet.getString("atividade_esposa"));
//            tfFilhos.setText(conexao.resultSet.getString("atividade_filhos"));
//            tfNetos.setText(conexao.resultSet.getString("atividade_netos"));
//            tfTempoDiario.setText(conexao.resultSet.getString("tempo_diario_trab"));
//            tfTempoAtividade.setText(conexao.resultSet.getString("tempo_na_atividade"));
//            tfRendaMensal.setText(conexao.resultSet.getString("renda_mensal_ou_viagem"));
//            tfQualColonia.setText(conexao.resultSet.getString("qual_colonia"));
//            tfDesdeQuando.setText(conexao.resultSet.getString("na_colonia_desde"));
//            tfTipoConstrucao.setText(conexao.resultSet.getString("tipo_construcao"));

            //System.out.println(conexao.resultSet.getString("local_moradia"));
            
//            if (conexao.resultSet.getString("possui_reg_colonia").equals("1"))
//                   chbPossuiColonia.setSelected(true);
//            else
//                   chbPossuiColonia.setSelected(false);
//
//            cbMunicipio.setSelectedItem(conexao.resultSet.getString("id_local"));
//            cbSexo.setSelectedItem(conexao.resultSet.getString("sexo"));
//            cbLocalMoradia.setSelectedItem(conexao.resultSet.getString("local_moradia"));
//            cbQualidadeMoradia.setSelectedItem(conexao.resultSet.getString("qualidade_moradia"));


        }catch (SQLException ex) {
            if (navega == 1){
                JOptionPane.showMessageDialog(null,"Você já esta no primeiro registro");
                proximo();
            }
            else if (navega == 2){
                JOptionPane.showMessageDialog(null,"Você já esta no ultimo registro");
                anterior();
            }
            else
                JOptionPane.showMessageDialog(null,"Nenhum registro encontrado "+ ex );
            navega = 0;
            //Logger.getLogger(frm_cad_atravessador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void anterior() {
         try {
                    conexao.resultSet.previous();
                } catch (SQLException ex1) {
                    Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex1);
                }
    }

    private void proximo() {
        try {
                    conexao.resultSet.next();
                } catch (SQLException ex1) {
                    Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex1);
                }
    }
    



}
