/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WinQuestionarioEmpresa.java
 *
 * Created on 10/08/2010, 12:08:12
 */
package br.com.view;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Toolkit;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Elton
 */
public class WinQuestionarioEmpresa extends javax.swing.JFrame {

    /** Creates new form WinQuestionarioEmpresa */
    private Integer index = 1;
    private final int max = 17;
    private final int min = 2;

    public WinQuestionarioEmpresa() {
        initLookAndfeel();
        initComponents();
        btAnterior.setEnabled(false);
        ChangePanel("Empresa", new WinBeanEmpresa());
        Insets in = Toolkit.getDefaultToolkit().getScreenInsets(this.getGraphicsConfiguration());
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int width = d.width - (in.left + in.top);
        int height = d.height - (in.top + in.bottom);
        setSize(width, height);
        setLocation(in.left, in.top);

    }
//
//          public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new WinQuestionarioEmpresa().setVisible(true);
//            }
//        });
//    }

    private void initLookAndfeel() {
        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDireito = new javax.swing.JPanel();
        btAnterior = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelDireito.setBackground(new java.awt.Color(255, 255, 255));
        panelDireito.setPreferredSize(new java.awt.Dimension(999, 999));

        javax.swing.GroupLayout panelDireitoLayout = new javax.swing.GroupLayout(panelDireito);
        panelDireito.setLayout(panelDireitoLayout);
        panelDireitoLayout.setHorizontalGroup(
            panelDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        panelDireitoLayout.setVerticalGroup(
            panelDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );

        btAnterior.setText("Anterior");
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        btProximo.setText("Proximo");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btAnterior)
                .addGap(18, 18, 18)
                .addComponent(btProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(panelDireito, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDireito, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAnterior)
                    .addComponent(btProximo))
                .addContainerGap(450, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        // TODO add your handling code here:

         if (index-- == min) {
            updatePanel(index);
            btAnterior.setEnabled(false);

        } else {
            updatePanel(index);
        }

        btProximo.setEnabled(true);
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        // TODO add your handling code here:
       
        if (index++ == max) {
            updatePanel(index);
            btProximo.setEnabled(false);
           
        } else {
            
            updatePanel(index);
        }
         btAnterior.setEnabled(true);
      
    }//GEN-LAST:event_btProximoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JButton btAnterior;
    protected static javax.swing.JButton btProximo;
    private javax.swing.JPanel panelDireito;
    // End of variables declaration//GEN-END:variables

    /**
     * Realiza a troca de panel dinamicamente
     * @param nomePainel O nome do painel
     * @param jPanel O Jpanel a ser mostrada
     */
    private void ChangePanel(String nomePainel, JPanel jPanel) {

        panelDireito.removeAll();
        panelDireito.setVisible(false);

        try {

            Container container = getContentPane();
            container.setLayout(new BorderLayout());

            panelDireito = new JPanel(new CardLayout());
            panelDireito.add(nomePainel, jPanel);
            container.add(BorderLayout.AFTER_LINE_ENDS, panelDireito);
            CardLayout card = (CardLayout) panelDireito.getLayout();
            card.next(panelDireito);


        } catch (Exception e) {
        }
    }

    private void updatePanel(Integer index) {
        switch (index) {
            case 1: {
                ChangePanel("Empresa", new WinBeanEmpresa());
                break;
            }
              case 2: {
                ChangePanel("Empresa", new WinSelecionaEmpresa());
                break;
            }
            case 3: {
                ChangePanel("EmpresaEB", new WinEB());
                break;
            }
            case 4: {
                ChangePanel("EmpresaEP", new WinEspecieProcessada());
                break;
            }
            case 5: {
                ChangePanel("Q1", new WinQuestionario1());
                break;
            }
            case 6: {
                ChangePanel("EmpresaEP", new WinProblemas());
                break;
            }
            case 7: {
                ChangePanel("EmpresaEP", new WinQuestionario2());
                break;
            }
            case 8: {
                ChangePanel("EmpresaEP", new WinImposto());
                break;
            }
            case 9: {
                ChangePanel("EmpresaEP", new WinQuestionario3());
                break;
            }
            case 10: {
                ChangePanel("EmpresaEP", new WinQuestionario4());
                break;
            }
            case 11: {
                ChangePanel("EmpresaEP", new WinDetalheFrota());
                break;
            }
            case 12: {
                ChangePanel("EmpresaEP", new EmpresaMaterial());
                break;
            }
            case 13: {
                ChangePanel("EmpresaEP", new WinTripulacao());
                break;
            }
            case 14: {
                ChangePanel("EmpresaEP", new WinQuestionario5());
                break;
            }
            case 15: {
                ChangePanel("EmpresaEP", new WinEmpresaPescador());
                break;
            }
            case 16: {
               ChangePanel("EmpresaEP", new WinQuestionario6());
                break;
            }
            case 17: {
                ChangePanel("EmpresaEP", new WinEmpresaMercado());
                break;
            }
            case 18: {
                ChangePanel("EmpresaEP", new WinQuestionario7());
                break;
            }

        }
    }
}
