/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WinJanelaMensalidade.java
 *
 * Created on 11/03/2010, 21:34:25
 */
package br.com.bean;

import Camada.Util.JMoneyField;
import Camada.Util.ToDecimal;
import br.com.Bean.Aluno;
import br.com.Bean.Mensalidade;
import br.com.Persistencia.DAO;
import br.com.Util.Converte;
import br.com.Util.Mensagen;
import br.com.Util.Parametro;
import br.com.Util.Status;
import br.com.Util.Tipo;
import br.com.Util.UtilProgresso;
import br.com.calendario.CalendarioComboBox;

/**
 *
 * @author elton
 */
public class WinJanelaMensalidade extends javax.swing.JFrame {

    /** Creates new form WinJanelaMensalidade */
    private Aluno aluno;
    private String cmd;
    private Mensalidade mensalidade;
    private DAO processamento;
    private boolean confirma;

    public WinJanelaMensalidade() {
        processamento = UtilProgresso.processamento;
        initComponents();
    }

    /**
     * Abri uma janela para add uma mensalidade
     * @param aluno
     * @param cmd
     */
    WinJanelaMensalidade(Aluno aluno, String cmd) {

        processamento = UtilProgresso.processamento;
        initComponents();

        this.cmd = cmd;
        this.aluno = aluno;

        initConfig(true);
    }

    /**
     * Abri uma janela para atualizar ou confirma pagamento de uma mensalidade
     * @param aluno
     * @param cmd
     * @param m
     */
    WinJanelaMensalidade(Aluno aluno, String cmd, Mensalidade m) {

        processamento = UtilProgresso.processamento;
        initComponents();

        this.cmd = cmd;
        this.mensalidade = m;
        this.aluno = aluno;

        if (cmd.contains("OK")) {
            labelPgto.setText("Dia de Pgto da Mensalidade.:");
            labelPgto.setToolTipText("Referente ao dia que foi realizado de fato o pgto.");
            tf_mensalidade.setVisible(false);
            labelMensalidade.setVisible(false);
            labelNome.setText(aluno.getNome());
        } else {
            //Atualiza
            initConfig(Boolean.TRUE);
        }

    }

    public String getValor() {
        return tf_mensalidade.getText();
    }

    public String getData() {
        return cb_mensalidade.getDateFormat();
    }

    private void initConfig(Boolean estado) {
        this.setConfirma(false);
        labelPgto.setVisible(estado);
        cb_mensalidade.setVisible(estado);

        labelNome.setText(aluno.getNome());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        labelMensalidade = new javax.swing.JLabel();
        tf_mensalidade = new JMoneyField();
        labelPgto = new javax.swing.JLabel();
        cb_mensalidade = new CalendarioComboBox();
        jLabel1 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        labelMensalidade.setText("Valor da Mensalidade* (R$).:");

        labelPgto.setText("Pgto da Mensalidade.:");

        cb_mensalidade.setDateFormat("dd.MM.yyyy");

        jLabel1.setText("Nome.: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelMensalidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_mensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(181, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPgto)
                        .addGap(10, 10, 10)
                        .addComponent(cb_mensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(187, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(49, 49, 49))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelNome))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_mensalidade, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(labelPgto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMensalidade)
                    .addComponent(tf_mensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        this.setConfirma(false);
        WinJanelaMensalidade.this.dispose();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        boolean resposta = false;

        try {
            if (cmd.equalsIgnoreCase("Add")) {

                String dataPagamento = Converte.dateToString(cb_mensalidade.getDate());

                Mensalidade mensalidade = new Mensalidade();
                mensalidade.setDataMensalidade(Converte.StringToDate(dataPagamento));
                mensalidade.setStatus(Status.Inadimplente);
                mensalidade.setValor(new ToDecimal().strTofloat(tf_mensalidade.getText()));
                mensalidade.setAluno(aluno);


                resposta = processamento.cadastra(mensalidade);
                //processamento.aberturaFinanceiro(dataPagamento, Tipo.Entrada, Parametro.MENSALIDADE + aluno.getNome(), mensalidade.getValor());
                showMessage(Parametro.ADD_MENSALIDADE, resposta);


            } else if (cmd.equalsIgnoreCase("Atualizar")) {

                mensalidade.setDataPagamento(cb_mensalidade.getDate());
                mensalidade.setValor(new ToDecimal().strTofloat(tf_mensalidade.getText()));
                resposta = processamento.atualizar(mensalidade);
                showMessage(Parametro.ATUALIZA_MENSALIDADE, resposta);
            } else if (cmd.equalsIgnoreCase("OK")) {

                this.setConfirma(true);
                String dataPagamento = Converte.dateToString(cb_mensalidade.getDate());
                mensalidade.setDataPagamento(cb_mensalidade.getDate());
                showMessage(Parametro.MENSALIDADE, processamento.atualizar(mensalidade));
                processamento.aberturaFinanceiro(dataPagamento,
                        Tipo.Entrada, Parametro.MENSALIDADE + aluno.getNome(), mensalidade.getValor(),mensalidade);
                
            }
        } catch (Exception e) {
            System.out.println("exception.: " + e);
        } finally {
            WinJanelaMensalidade.this.dispose();
        }


    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new WinJanelaMensalidade().setVisible(true);
//            }
//        });
//    }
    private void showMessage(String parametro, boolean resposta) {
        if (resposta) {
            Mensagen.getMensagem(parametro);
        }
    }

    public boolean isConfirma() {
        return confirma;
    }

    public void setConfirma(boolean confirma) {
        this.confirma = confirma;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.imagine.component.calendar.CalendarComboBox cb_mensalidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMensalidade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPgto;
    public static javax.swing.JTextField tf_mensalidade;
    // End of variables declaration//GEN-END:variables
}
