/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_questionario_atravessador.java
 *
 * Created on 26/07/2010, 09:44:24
 */
package br.com.formulario.atravessador;

import br.com.conexao.Conexao;
import br.com.util.JMoneyField;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MPA
 */

public class atravessador2 extends javax.swing.JFrame {

    /** Creates new form frm_questionario_atravessador */
    private Conexao conexao;
    int inicia_combo = 0;
    String id_atravessador;
    String ItemDoCb;
    public atravessador2() {
        initComponents();
        conexao = new Conexao();
        conexao.conecta("mil_interface");

        //Insere nome no cbNomeAtravessador
                try {
                    cbNomeAtravessador.removeAllItems();
                    conexao.execute("select * from atravessador_cadastro");
                    
                    while (conexao.resultSet.next()){
                        cbNomeAtravessador.addItem(conexao.resultSet.getString("id_atravessador")+
                                                       " # "+ conexao.resultSet.getString("nome"));
                        //ItemDoCb = conexao.resultSet.getString("id_atravessador")+ " # "+ conexao.resultSet.getString("nome");
                        //pega_codigo(1);
                        //System.out.println(conexao.resultSet.getString("nome"));
                    }
                }catch (SQLException ex) {
                    System.out.println(ex);
                }

        conexao.execute("select * from atravessador_questionario");
        try {
            conexao.resultSet.first();
        } catch (SQLException ex) {
            System.out.println(ex+" linha 58");
        }
         mostra_dados();



    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpPescadoSubproduto = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        cbNomeAtravessador = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        botao_salvar_questionario = new javax.swing.JButton();
        botao_alterar = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        ckbPossuiColonia = new javax.swing.JCheckBox();
        tfDesdeQuando = new javax.swing.JTextField();
        tfQualColonia = new javax.swing.JTextField();
        tfTempoAtividade = new javax.swing.JTextField();
        rbMadeira = new javax.swing.JRadioButton();
        rbBanheiroDentro = new javax.swing.JRadioButton();
        rbAlvenaria = new javax.swing.JRadioButton();
        rbBanheiroFora = new javax.swing.JRadioButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        ckbLuzSim = new javax.swing.JCheckBox();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        ckbFossaSim = new javax.swing.JCheckBox();
        jLabel52 = new javax.swing.JLabel();
        ckbDrenagemSim = new javax.swing.JCheckBox();
        ckbAguaSim = new javax.swing.JCheckBox();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        tfRenda = new JMoneyField();
        jLabel55 = new javax.swing.JLabel();
        tfAtividade = new javax.swing.JTextField();
        btExcluirRendaFamilia = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        tfParentesco = new javax.swing.JTextField();
        btAdicionarRendaFamilia = new javax.swing.JButton();
        jScrollPane30 = new javax.swing.JScrollPane();
        jTableAtividadeFamiliar = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        tfQualBeneficio = new javax.swing.JTextField();
        ckbRecebeBeneficioGovernoSim = new javax.swing.JCheckBox();
        jLabel57 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        rbPescadorP = new javax.swing.JRadioButton();
        rbEmpresaP = new javax.swing.JRadioButton();
        rbOutroAtravessadorP = new javax.swing.JRadioButton();
        rbDonoBarcoP = new javax.swing.JRadioButton();
        rbMercadoFeiraP = new javax.swing.JRadioButton();
        rbCooperativaP = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbPescadorG = new javax.swing.JRadioButton();
        rbEmpresaG = new javax.swing.JRadioButton();
        rbDonoBarcoG = new javax.swing.JRadioButton();
        rbMercadoFeiraG = new javax.swing.JRadioButton();
        rbOutroAtravessadorG = new javax.swing.JRadioButton();
        rbCooperativaG = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ckbAumentouSim = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fechar_janela(evt);
            }
        });

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel41.setForeground(new java.awt.Color(0, 102, 102));
        jLabel41.setText("Questionário Atravessador");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel41)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        cbNomeAtravessador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomeAtravessadorActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome.:");

        botao_salvar_questionario.setText("Salvar");
        botao_salvar_questionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_salvar_questionarioActionPerformed(evt);
            }
        });

        botao_alterar.setText("Alterar");
        botao_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarActionPerformed(evt);
            }
        });

        jLabel43.setText("Quando tempo está na atividade?");

        jLabel44.setText("Qual?");

        jLabel45.setText("Desde quando? (ex: 14/10/1988)");

        jLabel47.setText("Tem registro em alguma entidade de classe (colônia, associação, cooperativa)?");

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel49.setText("Quem de sua família trabalha? E com qual atividade?:");

        ckbPossuiColonia.setText("Sim");
        ckbPossuiColonia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckbPossuiColoniaStateChanged(evt);
            }
        });
        ckbPossuiColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbPossuiColoniaActionPerformed(evt);
            }
        });

        tfTempoAtividade.setText("0");

        rbMadeira.setText("Madeira");

        rbBanheiroDentro.setText("Dentro");

        rbAlvenaria.setText("Alvenaria");

        rbBanheiroFora.setText("Fora");
        rbBanheiroFora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBanheiroForaActionPerformed(evt);
            }
        });

        jLabel42.setText("Banheiro.:");

        jLabel46.setText("Casa.:");

        ckbLuzSim.setText("Sim");

        jLabel48.setText("Luz elétrica.:");

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel50.setText("MORADIA");

        jLabel51.setText("Fossa seca ou sépica.:");

        ckbFossaSim.setText("Sim");
        ckbFossaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbFossaSimActionPerformed(evt);
            }
        });

        jLabel52.setText("Água encanada.:");

        ckbDrenagemSim.setText("Sim");

        ckbAguaSim.setText("Sim");

        jLabel53.setText("Drenagem pluvial.:");

        jLabel54.setText("Renda");

        jLabel55.setText("Atividade");

        btExcluirRendaFamilia.setText("Excluir");
        btExcluirRendaFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirRendaFamiliaActionPerformed(evt);
            }
        });

        jLabel56.setText("Parentesco:");

        btAdicionarRendaFamilia.setText("Adicionar");
        btAdicionarRendaFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarRendaFamiliaActionPerformed(evt);
            }
        });

        jTableAtividadeFamiliar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod", "Parentesco", "Atividade", "Renda"
            }
        ));
        jScrollPane30.setViewportView(jTableAtividadeFamiliar);

        jLabel25.setText("Qual.:");

        ckbRecebeBeneficioGovernoSim.setText("Sim");

        jLabel57.setText("Recebe algum benefício do governo.:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel58.setText("Como funciona o \"caminho da cadeia de comercialização\" do pescado ou da grude");

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel59.setText("1 - Recepção dos produtos:");

        jLabel1.setText("De quem compra o produto, ou seja, quais seus fornecedores?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Pescado");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        rbPescadorP.setText("Pescador");

        rbEmpresaP.setText("Empresa");

        rbOutroAtravessadorP.setText("Outro Atravessador");

        rbDonoBarcoP.setText("Dono do Barco");

        rbMercadoFeiraP.setText("Mercado ou Feira");

        rbCooperativaP.setText("Cooperativa");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Grude");

        rbPescadorG.setText("Pescador");

        rbEmpresaG.setText("Empresa");

        rbDonoBarcoG.setText("Dono do Barco");

        rbMercadoFeiraG.setText("Mercado ou Feira");

        rbOutroAtravessadorG.setText("Outro Atravessador");

        rbCooperativaG.setText("Cooperativa");

        jLabel4.setText("Quantos fornecedores são?");

        jLabel5.setText("O n° de fornecedores aumntaram nos últimos 5 anos?");

        ckbAumentouSim.setText("Sim");

        javax.swing.GroupLayout jpPescadoSubprodutoLayout = new javax.swing.GroupLayout(jpPescadoSubproduto);
        jpPescadoSubproduto.setLayout(jpPescadoSubprodutoLayout);
        jpPescadoSubprodutoLayout.setHorizontalGroup(
            jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNomeAtravessador, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel52)
                                            .addComponent(jLabel42)
                                            .addComponent(jLabel46)
                                            .addComponent(jLabel48)
                                            .addComponent(jLabel51))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ckbLuzSim)
                                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbBanheiroDentro)
                                                    .addComponent(rbMadeira))
                                                .addGap(8, 8, 8)
                                                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbBanheiroFora)
                                                    .addComponent(rbAlvenaria)))
                                            .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(ckbDrenagemSim)
                                                .addComponent(ckbFossaSim)
                                                .addComponent(ckbAguaSim))))
                                    .addComponent(jLabel53))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPescadoSubprodutoLayout.createSequentialGroup()
                                    .addComponent(jLabel56)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel55)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel54)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btAdicionarRendaFamilia))
                                .addComponent(jScrollPane30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                                .addComponent(btExcluirRendaFamilia))
                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTempoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addComponent(jLabel57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckbRecebeBeneficioGovernoSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfQualBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                        .addComponent(jLabel44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfQualColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel45)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfDesdeQuando, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                        .addComponent(jLabel47)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckbPossuiColonia)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(279, 279, 279))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botao_salvar_questionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao_alterar))
                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel58)
                                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(rbPescadorP)
                                            .addComponent(rbEmpresaP)
                                            .addComponent(rbOutroAtravessadorP)
                                            .addComponent(rbDonoBarcoP)
                                            .addComponent(rbMercadoFeiraP)
                                            .addComponent(rbCooperativaP)
                                            .addComponent(jLabel5))
                                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(rbPescadorG)
                                                    .addComponent(rbEmpresaG)
                                                    .addComponent(rbOutroAtravessadorG)
                                                    .addComponent(rbDonoBarcoG)
                                                    .addComponent(rbMercadoFeiraG)
                                                    .addComponent(rbCooperativaG)))
                                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ckbAumentouSim))))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE))))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel59))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPescadoSubprodutoLayout.setVerticalGroup(
            jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbNomeAtravessador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel46))
                    .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbAlvenaria)
                        .addComponent(rbMadeira)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(ckbLuzSim, 0, 0, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(rbBanheiroFora)
                    .addComponent(rbBanheiroDentro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(ckbAguaSim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                            .addComponent(ckbDrenagemSim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(ckbFossaSim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(ckbPossuiColonia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(tfQualColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45)
                    .addComponent(tfDesdeQuando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(tfParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55)
                    .addComponent(tfAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54)
                    .addComponent(tfRenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdicionarRendaFamilia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluirRendaFamilia)
                .addGap(12, 12, 12)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbRecebeBeneficioGovernoSim)
                    .addComponent(jLabel57)
                    .addComponent(jLabel25)
                    .addComponent(tfQualBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(tfTempoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPescadorP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbEmpresaP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbOutroAtravessadorP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDonoBarcoP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbMercadoFeiraP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCooperativaP))
                    .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPescadoSubprodutoLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbPescadorG)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbEmpresaG)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbOutroAtravessadorG)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbDonoBarcoG)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbMercadoFeiraG)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbCooperativaG))))
                .addGap(28, 28, 28)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ckbAumentouSim))
                .addGap(130, 130, 130)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_alterar)
                    .addComponent(botao_salvar_questionario))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jpPescadoSubproduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-637)/2, (screenSize.height-788)/2, 637, 788);
    }// </editor-fold>//GEN-END:initComponents

    private void cbNomeAtravessadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomeAtravessadorActionPerformed
       
        //Pesquisa automática do Combo Box Nome do atravessador
        
        if (inicia_combo == 1){
         try {
            conexao.execute("select * from atravessador_questionario");
            conexao.resultSet.first();
            String igual = "n"; //inicia dizendo que não localizou
            while(igual == "n") //diz que enquanto não localizar é para ir executando
            {
                String id = pega_codigo_ou_nome(1,cbNomeAtravessador.getSelectedItem().toString());
                if (conexao.resultSet.getString("id_atravessador").equals(id)) {
                    igual = "s"; //incica que achou
                } else
                    conexao.resultSet.next();
            }
            //nas linhas abaixo, mostra_conteudo_tabela();
             mostra_dados();


        } catch (SQLException ex) {
            limpar_dados();
            System.out.println(ex+" Erro na pesquisa de nome");
            }
        }inicia_combo = 1;
         
    }//GEN-LAST:event_cbNomeAtravessadorActionPerformed

    private void fechar_janela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar_janela
        conexao.desconecta();
    }//GEN-LAST:event_fechar_janela

    private void botao_salvar_questionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_salvar_questionarioActionPerformed
        

        //System.out.println(a);


        try {
            String sqlinsert = "insert into atravessador_questionario "
                    + "(id_atravessador,nome_atravessador,origem_produto,"
                    + "sempre_dos_mesmos_pesc,peixe_inteiro,criterios_qualidade_produto,"
                    + "exigencia_pescado_subprodutos,como_func_recepcao,"
                    + "como_func_armazenamento,como_funf_comercializacao,"
                    + "dificuldades_para_manter_e_solucoes,possui_cliente_consumidor,"
                    + "possui_cliente_restaurante,possui_cliente_supermercados,"
                    + "possui_cliente_revendedores,possui_cliente_feiras,"
                    + "possui_cliente_outros,possui_cliente_outros_quais,"
                    + "sempre_vende_pros_mesmos,exigencias_compradores,"
                    + "como_negocia,cede_adiantamento,situacao_obriga_entregar_prod,"
                    + "existe_interacao,grau_competitividade,atuacao_instituicoes_sua_relacao,"
                    + "estoque_continua_estavel,pescado_diminuindo_mot_mudanca,"
                    + "numero_aumentou_o_que_acha,perspectiva,pretende_continuar,"
                    + "desejo_para_filhos,sempre_dos_mesmos_pesc_quais,observacao) values ("+
                    pega_codigo_ou_nome(1,cbNomeAtravessador.getSelectedItem().toString())+",'"+
                    pega_codigo_ou_nome(0,cbNomeAtravessador.getSelectedItem().toString())+"','";
//                    taOrigemProduto.getText()+"',"+
//                    ckb[0]+","+
//                    ckb[1]+",'"+
//                    taCriterioQualidadeProduto.getText()+"','"+
//                    taExigenciaCompraPescado.getText()+"','"+
//                    taRecepcao.getText()+"','"+
//                    taArmazenamento.getText()+"','"+
//                    taComercializacao.getText()+"','"+
//                    tpDificuldadesEncontradas.getText()+"',"+
//                    ckb[2]+","+
//                    ckb[3]+","+
//                    ckb[4]+","+
//                    ckb[5]+","+
//                    ckb[6]+","+
//                    ckb[7]+",'"+
//                    tfOutros_principaisClientes.getText()+"','"+
//                    tpSempreMesmoCompradores.getText()+"','"+
//                    tpExigenciasCompradores.getText()+"','"+
//                    tpComoNegocia.getText()+"','"+
//                    tpCedeAdiantamento.getText()+"','"+
//                    tpSitObrigaEntregar.getText()+"','"+
//                    tpExisteIteracao.getText()+"','"+
//                    tpGrauCompetitividade.getText()+"','"+
//                    tpAtuacaoInstituicoesSuaRelacao.getText()+"','"+
//                    tpEstoqueContEstavel.getText()+"','"+
//                    tpTamanhoPescadoDiminuindo.getText()+"','"+
//                    tpNumeroFornecedoresAumentou.getText()+"','"+
//                    tpPerspectiva.getText()+"','"+
//                    tpContinuarAtividade.getText()+"','"+
//                    tpDesejoFilhos.getText()+"','"+
//                    //aqui só mudanças
//                    tfOutrasFormasDeComercializacaoPeixe.getText()+"','"+//sempre_dos_mesmos_pesc_quais
//                    tpObservacao.getText()+"')";//observacao

                   // System.out.println(sqlinsert);

            if (conexao.salvar(sqlinsert)){
            //agora é hora de atualizar o resultset
            JOptionPane.showMessageDialog(null,"Salvo com sucesso");
            conexao.execute("select * from atravessador_questionario");
            conexao.resultSet.first(); //1º registro
            mostra_dados();
            cbNomeAtravessador.setSelectedIndex(0);
            }

        }catch (SQLException erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_botao_salvar_questionarioActionPerformed

    private void botao_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarActionPerformed
       

        try{
            String sql ="UPDATE atravessador_questionario SET "+
//                          "origem_produto = '"+taOrigemProduto.getText()+"',"+
//                          "sempre_dos_mesmos_pesc = '"+ ckb[0] +"',"+
//                          "peixe_inteiro = '"+ ckb[1] +"',"+
//                          "criterios_qualidade_produto = '"+ taCriterioQualidadeProduto.getText() +"',"+
//                          "exigencia_pescado_subprodutos = '"+ taExigenciaCompraPescado.getText() +"',"+
//                          "como_func_recepcao = '"+ taRecepcao.getText() +"',"+
//                          "como_func_armazenamento = '"+ taArmazenamento.getText() +"',"+
//                          "como_funf_comercializacao = '"+ taComercializacao.getText() +"',"+
//                          "dificuldades_para_manter_e_solucoes = '"+ tpDificuldadesEncontradas.getText() +"',"+
//                          "possui_cliente_consumidor = '"+ ckb[2] +"',"+
//                          "possui_cliente_restaurante = '"+ ckb[3] +"',"+
//                          "possui_cliente_supermercados = '"+ ckb[4] +"',"+
//                          "possui_cliente_revendedores = '"+ ckb[5] +"',"+
//                          "possui_cliente_feiras = '"+ ckb[6] +"',"+
//                          "possui_cliente_outros = '"+ ckb[7] +"',"+
//                          "possui_cliente_outros_quais = '"+ tfOutros_principaisClientes.getText() +"',"+
//                          "sempre_vende_pros_mesmos = '"+ tpSempreMesmoCompradores.getText() +"',"+
//                          "exigencias_compradores = '"+ tpExigenciasCompradores.getText() +"',"+
//                          "como_negocia = '"+ tpComoNegocia.getText() +"',"+
//                          "cede_adiantamento = '"+ tpCedeAdiantamento.getText() +"',"+
//                          "situacao_obriga_entregar_prod = '"+ tpSitObrigaEntregar.getText() +"',"+
//                          "existe_interacao = '"+ tpExisteIteracao.getText() +"',"+
//                          "grau_competitividade = '"+ tpGrauCompetitividade.getText() +"',"+
//                          "atuacao_instituicoes_sua_relacao = '"+ tpAtuacaoInstituicoesSuaRelacao.getText() +"',"+
//                          "estoque_continua_estavel = '"+ tpEstoqueContEstavel.getText() +"',"+
//                          "pescado_diminuindo_mot_mudanca = '"+ tpTamanhoPescadoDiminuindo.getText() +"',"+
//                          "numero_aumentou_o_que_acha = '"+ tpNumeroFornecedoresAumentou.getText() +"',"+
//                          "perspectiva = '"+ tpPerspectiva.getText() +"',"+
//                          "pretende_continuar = '"+ tpContinuarAtividade.getText() +"',"+
//                          "desejo_para_filhos = '"+ tpDesejoFilhos.getText() +"',"+
//
//
//                          "sempre_dos_mesmos_pesc_quais = '"+ tfOutrasFormasDeComercializacaoPeixe.getText() +"',"+
//                          "observacao = '"+ tpObservacao.getText() +"' "+


                          "where id_atravessador = "+pega_codigo_ou_nome(1,cbNomeAtravessador.getSelectedItem().toString());

            System.out.println(sql);
            if (conexao.update(sql)){
            JOptionPane.showMessageDialog(null,"Alterado com sucesso");
            //Atualiza Resultset
            conexao.execute("select * from atravessador_questionario");
            conexao.resultSet.next();
            mostra_dados();
            cbNomeAtravessador.setSelectedIndex(0);
            }


        }catch (Exception e){
            System.out.println(e + "Erro no botão alterar");
        }
    }//GEN-LAST:event_botao_alterarActionPerformed

    private void ckbPossuiColoniaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckbPossuiColoniaStateChanged
        if (ckbPossuiColonia.isSelected()){
            tfQualColonia.setEditable(true);
        }else{
            tfQualColonia.setEditable(false);
            tfQualColonia.setText("");
        }
}//GEN-LAST:event_ckbPossuiColoniaStateChanged

    private void ckbPossuiColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbPossuiColoniaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ckbPossuiColoniaActionPerformed

    private void btExcluirRendaFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirRendaFamiliaActionPerformed
        excluirRT();
}//GEN-LAST:event_btExcluirRendaFamiliaActionPerformed

    private void btAdicionarRendaFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarRendaFamiliaActionPerformed
        addBtRt();
}//GEN-LAST:event_btAdicionarRendaFamiliaActionPerformed

    private void rbBanheiroForaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBanheiroForaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBanheiroForaActionPerformed

    private void ckbFossaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbFossaSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbFossaSimActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new atravessador2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_alterar;
    private javax.swing.JButton botao_salvar_questionario;
    private javax.swing.JButton btAdicionarRendaFamilia;
    private javax.swing.JButton btExcluirRendaFamilia;
    private javax.swing.JComboBox cbNomeAtravessador;
    private javax.swing.JCheckBox ckbAguaSim;
    private javax.swing.JCheckBox ckbAumentouSim;
    private javax.swing.JCheckBox ckbDrenagemSim;
    private javax.swing.JCheckBox ckbFossaSim;
    private javax.swing.JCheckBox ckbLuzSim;
    private javax.swing.JCheckBox ckbPossuiColonia;
    private javax.swing.JCheckBox ckbRecebeBeneficioGovernoSim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableAtividadeFamiliar;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpPescadoSubproduto;
    private javax.swing.JRadioButton rbAlvenaria;
    private javax.swing.JRadioButton rbBanheiroDentro;
    private javax.swing.JRadioButton rbBanheiroFora;
    private javax.swing.JRadioButton rbCooperativaG;
    private javax.swing.JRadioButton rbCooperativaP;
    private javax.swing.JRadioButton rbDonoBarcoG;
    private javax.swing.JRadioButton rbDonoBarcoP;
    private javax.swing.JRadioButton rbEmpresaG;
    private javax.swing.JRadioButton rbEmpresaP;
    private javax.swing.JRadioButton rbMadeira;
    private javax.swing.JRadioButton rbMercadoFeiraG;
    private javax.swing.JRadioButton rbMercadoFeiraP;
    private javax.swing.JRadioButton rbOutroAtravessadorG;
    private javax.swing.JRadioButton rbOutroAtravessadorP;
    private javax.swing.JRadioButton rbPescadorG;
    private javax.swing.JRadioButton rbPescadorP;
    private javax.swing.JTextField tfAtividade;
    private javax.swing.JTextField tfDesdeQuando;
    private javax.swing.JTextField tfParentesco;
    private javax.swing.JTextField tfQualBeneficio;
    private javax.swing.JTextField tfQualColonia;
    private javax.swing.JTextField tfRenda;
    private javax.swing.JTextField tfTempoAtividade;
    // End of variables declaration//GEN-END:variables

        public void preencher_jtable(){
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(10);

        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);//limpa o JTable1;

        try{
            while (conexao.resultSet.next())
                modelo.addRow(new Object[]{conexao.resultSet.getString("id_material"),
                                           conexao.resultSet.getString("nome"),
                                           conexao.resultSet.getString("tipo"),
                                           conexao.resultSet.getString("quantidade"),
                                           conexao.resultSet.getString("custo"),
                                           conexao.resultSet.getString("outros"),
                                           conexao.resultSet.getString("frequencia")});

            conexao.resultSet.first();
        }catch (SQLException erro){
            System.out.println(erro);
        }



    }

    public void mostra_dados(){
        try {
            //Exibir os text areas
//            taOrigemProduto.setText(conexao.resultSet.getString("origem_produto"));
//            taCriterioQualidadeProduto.setText(conexao.resultSet.getString("criterios_qualidade_produto"));
//            taExigenciaCompraPescado.setText(conexao.resultSet.getString("exigencia_pescado_subprodutos"));
//            taRecepcao.setText(conexao.resultSet.getString("como_func_recepcao"));
//            taArmazenamento.setText(conexao.resultSet.getString("como_func_armazenamento"));
//            taComercializacao.setText(conexao.resultSet.getString("como_funf_comercializacao"));
//
//           tpDificuldadesEncontradas.setText(conexao.resultSet.getString("dificuldades_para_manter_e_solucoes"));
//           tpSempreMesmoCompradores.setText(conexao.resultSet.getString("sempre_vende_pros_mesmos"));
//           tpExigenciasCompradores.setText(conexao.resultSet.getString("exigencias_compradores"));
//           tpComoNegocia.setText(conexao.resultSet.getString("como_negocia"));
//           tpCedeAdiantamento.setText(conexao.resultSet.getString("cede_adiantamento"));
//           tpSitObrigaEntregar.setText(conexao.resultSet.getString("situacao_obriga_entregar_prod"));
//           tpExisteIteracao.setText(conexao.resultSet.getString("existe_interacao"));
//           tpGrauCompetitividade.setText(conexao.resultSet.getString("grau_competitividade"));
//           tpAtuacaoInstituicoesSuaRelacao.setText(conexao.resultSet.getString("atuacao_instituicoes_sua_relacao"));
//           tpEstoqueContEstavel.setText(conexao.resultSet.getString("estoque_continua_estavel"));
//           tpTamanhoPescadoDiminuindo.setText(conexao.resultSet.getString("pescado_diminuindo_mot_mudanca"));
//           tpNumeroFornecedoresAumentou.setText(conexao.resultSet.getString("numero_aumentou_o_que_acha"));
//           tpPerspectiva.setText(conexao.resultSet.getString("perspectiva"));
//           tpContinuarAtividade.setText(conexao.resultSet.getString("pretende_continuar"));
//           tpDesejoFilhos.setText(conexao.resultSet.getString("desejo_para_filhos"));
//           tfOutros_principaisClientes.setText(conexao.resultSet.getString("possui_cliente_outros_quais"));
//
//            //Selecionar os check boxes conforme o BD
//            if (conexao.resultSet.getString("sempre_dos_mesmos_pesc").equals("1"))
//                   ckbSempreDosMesmos.setSelected(true);
//            else
//                   ckbSempreDosMesmos.setSelected(false);
//
//            if (conexao.resultSet.getString("peixe_inteiro").equals("1"))
//                   ckbPeixeInteiro.setSelected(true);
//            else
//                   ckbPeixeInteiro.setSelected(false);
//
//            if (conexao.resultSet.getString("possui_cliente_consumidor").equals("1"))
//                   ckbConsumidor.setSelected(true);
//            else
//                   ckbConsumidor.setSelected(false);
//
//            if (conexao.resultSet.getString("possui_cliente_restaurante").equals("1"))
//                   ckbRestaurante.setSelected(true);
//            else
//                   ckbRestaurante.setSelected(false);
//
//            if (conexao.resultSet.getString("possui_cliente_supermercados").equals("1"))
//                   ckbSupemercados.setSelected(true);
//            else
//                   ckbSupemercados.setSelected(false);
//
//            if (conexao.resultSet.getString("possui_cliente_revendedores").equals("1"))
//                   ckbRevendedores.setSelected(true);
//            else
//                   ckbRevendedores.setSelected(false);
//
//            if (conexao.resultSet.getString("possui_cliente_feiras").equals("1"))
//                   ckbFeiras.setSelected(true);
//            else
//                   ckbFeiras.setSelected(false);
//
//            if (conexao.resultSet.getString("possui_cliente_outros").equals("1"))
//                   ckbOutros_principaisClientes.setSelected(true);
//            else
//                   ckbOutros_principaisClientes.setSelected(false);
//
//           if (ckbOutros_principaisClientes.isSelected()){ // se outros estiver marcado, deixa editar
//            tfOutros_principaisClientes.setEditable(true);
//            }
//           else
//            tfOutros_principaisClientes.setEditable(false);
//
//           //mudancas
//
//           tfOutrasFormasDeComercializacaoPeixe.setText(conexao.resultSet.getString("sempre_dos_mesmos_pesc_quais"));
//           tpObservacao.setText(conexao.resultSet.getString("observacao"));





        } catch (Exception e) {
            System.out.println(e + " metodo mostrar dados");
        }
    }

        public void limpar_dados(){
//            taOrigemProduto.setText("");
//            taCriterioQualidadeProduto.setText("");
//            taExigenciaCompraPescado.setText("");
//            taRecepcao.setText("");
//            taArmazenamento.setText("");
//            taComercializacao.setText("");
//
//            tpDificuldadesEncontradas.setText("");
//            ckbConsumidor.setSelected(false);
//            ckbRestaurante.setSelected(false);
//            ckbSupemercados.setSelected(false);
//            ckbRevendedores.setSelected(false);
//            ckbFeiras.setSelected(false);
//            ckbOutros_principaisClientes.setSelected(false);
//
//            tfOutros_principaisClientes.setText("");
//            tpSempreMesmoCompradores.setText("");
//            tpExigenciasCompradores.setText("");
//            tpComoNegocia.setText("");
//            tpCedeAdiantamento.setText("");
//            tpSitObrigaEntregar.setText("");
//            tpExisteIteracao.setText("");
//            tpGrauCompetitividade.setText("");
//            tpAtuacaoInstituicoesSuaRelacao.setText("");
//            tpEstoqueContEstavel.setText("");
//            tpTamanhoPescadoDiminuindo.setText("");
//
//            tpNumeroFornecedoresAumentou.setText("");
//            tpPerspectiva.setText("");
//            tpContinuarAtividade.setText("");
//            tpDesejoFilhos.setText("");
//
//            ckbSempreDosMesmos.setSelected(false);
//            ckbPeixeInteiro.setSelected(false);
//
//            tfOutrasFormasDeComercializacaoPeixe.setText("");
//            tpObservacao.setText("");
    }

        public String pega_codigo_ou_nome(int n,String teste) { //Se entrar com 1 pega o Código, se não pega o Nome
              //pegar a Id do atravessador
              
              //aqui ele pega a quantidade de carcteres que tem uma determinada variável
              //e armazena numa INT para usá-la de contador
              int contador = teste.length();

              //cria um for( para fazer uma varredura letra por letra até encontrar
              for(int i = 0;i<contador;i++){
                 //usamos substring pra pegar um caractere, passando como parâmetro,
                 //o primeiro caractere a ser pega, até a ultima.
                //fiz um if para verificar se o caractere é igual a "#"
                if (teste.substring(i,i+1).equals("#")){
                   int posicao = i+1;
                    System.out.println("Está na posição " + posicao);
                    if (n == 1){
                        return teste.substring(0,posicao-2);
                    }
                    else
                        return teste.substring(posicao+1,teste.length());
                }

              }
              return "nada";
        }

        public void preencher_jtableMercado(JTable table){
        table.getColumnModel().getColumn(0).setMaxWidth(0);
        table.getColumnModel().getColumn(0).setPreferredWidth(0);
        table.getColumnModel().getColumn(1).setPreferredWidth(40);
        table.getColumnModel().getColumn(2).setPreferredWidth(10);
        table.getColumnModel().getColumn(3).setPreferredWidth(10);
        table.getColumnModel().getColumn(4).setPreferredWidth(10);
        table.getColumnModel().getColumn(5).setPreferredWidth(10);

        DefaultTableModel modelo = (DefaultTableModel)table.getModel();
        modelo.setNumRows(0);//limpa o JTable;

        try{
            while (conexao.resultSet.next())
                modelo.addRow(new Object[]{conexao.resultSet.getString("id_mercado"),
                                           conexao.resultSet.getString("especie"),
                                           conexao.resultSet.getString("produto"),
                                           conexao.resultSet.getString("destino"),
                                           conexao.resultSet.getString("volume")+" "+conexao.resultSet.getString("unidade_volume"),
                                           conexao.resultSet.getString("preco")});

            conexao.resultSet.first();
        }catch (SQLException erro){
            System.out.println(erro);
        }



    }

                public void preencher_jtableEspecie(){
////        jtEspecie.getColumnModel().getColumn(0).setMaxWidth(0);
////        jtEspecie.getColumnModel().getColumn(0).setPreferredWidth(0);
////        jtEspecie.getColumnModel().getColumn(1).setPreferredWidth(10);
////        jtEspecie.getColumnModel().getColumn(2).setPreferredWidth(10);
////        jtEspecie.getColumnModel().getColumn(3).setPreferredWidth(10);
////        jtEspecie.getColumnModel().getColumn(4).setPreferredWidth(10);
////
//        DefaultTableModel modelo = (DefaultTableModel)jTableAtividadeFamiliar.getModel();
//        modelo.setNumRows(0);//limpa o JTable;
//
//        try{
//            while (conexao.resultSet.next())
//                modelo.addRow(new Object[]{conexao.resultSet.getString("id_especie"),
//                                           conexao.resultSet.getString("especie"),
//                                           conexao.resultSet.getString("causa_da_perda"),
//                                           conexao.resultSet.getString("estimativa_da_perda"),
//                                           conexao.resultSet.getString("destino_do_peixe_perdido")});
//
//            conexao.resultSet.first();
//        }catch (SQLException erro){
//            System.out.println(erro);
//        }
    }

    public void exibir_L_E_N_I(int i){
//        if (i == 0){
//        //Atualiza A primeira tabela Mercado Local
//        conexao.execute("select * from atravessador_addmercado where id_atravessador="
//                        +pega_codigo_ou_nome(1,cbNomeAtravessador.getSelectedItem().toString())+" "
//                        + "and mercado='Mercado Local'");
//        preencher_jtableMercado(jtMercadoLocal);
//        conexao.execute("select * from atravessador_cadastro");
//        } else if (i == 1){
//        //Atualiza A segunda tabela Mercado Estadual
//        conexao.execute("select * from atravessador_addmercado where id_atravessador="
//                        +pega_codigo_ou_nome(1,cbNomeAtravessador.getSelectedItem().toString())+" "
//                        + "and mercado='Mercado Estadual'");
//        preencher_jtableMercado(jtMercadoEstadual);
//        conexao.execute("select * from atravessador_cadastro");
//        }else if (i == 2){
//        //Atualiza A terceira tabela Mercado Nacional
//        conexao.execute("select * from atravessador_addmercado where id_atravessador="
//                        +pega_codigo_ou_nome(1,cbNomeAtravessador.getSelectedItem().toString())+" "
//                        + "and mercado='Mercado Nacional'");
//        preencher_jtableMercado(jtMercadoNacional);
//        conexao.execute("select * from atravessador_cadastro");
//        }else if (i == 3){
//        //Atualiza A primeira tabela Mercado Internacional
//        conexao.execute("select * from atravessador_addmercado where id_atravessador="
//                        +pega_codigo_ou_nome(1,cbNomeAtravessador.getSelectedItem().toString())+" "
//                        + "and mercado='Mercado Internacional'");
//        preencher_jtableMercado(jtMercadoInternacional);
//        conexao.execute("select * from atravessador_cadastro");
//        }
    }

    private void excluirRT() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    private void addBtRt() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

}
