/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * winProduto.java
 *
 * Created on 16/07/2010, 15:50:37
 */
package br.com.formulario.empresa.view;

import br.com.conexao.Conexao;

/**
 *
 * @author Elton
 */
public class addMaterial extends javax.swing.JFrame {

    /** Creates new form winProduto */
    private Conexao conexao;
    private Integer id;
    private String chave;
    private String bean;

    public addMaterial() {
    }

    public addMaterial(Integer id,Class t) {
        this.id = id;
        bean =  t.getSimpleName();
        if(bean.equalsIgnoreCase("EmpresaMaterial"))
        {
            chave = "empresaId";
        }else chave = "pescadorId";
        initComponents();
        conexao = new Conexao();
        conexao.conecta("mil_interface");
        setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfMatTipo = new javax.swing.JTextField();
        tfMatQuantidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botao_add_mat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfMatOutroMat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMatCusto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfMatFrequencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbMatMaterial = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        tfMatOutros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tfMatQuantidade.setText("0");

        jLabel1.setText("Tipo.:");

        jLabel2.setText("Quantidade");

        botao_add_mat.setText("Add");
        botao_add_mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Action(evt);
            }
        });

        jLabel3.setText("Material.:");

        tfMatOutroMat.setEditable(false);

        jLabel4.setText("Custo.:");

        tfMatCusto.setText("0");

        jLabel5.setText("Frequência.:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setText("Gastos com material na atividade");

        jLabel7.setText("Outro Mat.:");

        cbMatMaterial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Combustível", "Lubrificante", "Gelo", "Rancho", "Pagamento de pescador", "Manutenção da rede", "Manutenção do barco", "Outro" }));
        cbMatMaterial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMatMaterialItemStateChanged(evt);
            }
        });
        cbMatMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMatMaterialActionPerformed(evt);
            }
        });

        jLabel8.setText("Outros.:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfMatFrequencia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMatOutros, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMatCusto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMatQuantidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMatTipo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMatOutroMat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMatMaterial, javax.swing.GroupLayout.Alignment.LEADING, 0, 209, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel6)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(botao_add_mat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMatMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMatOutroMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfMatTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfMatQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfMatCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tfMatOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfMatFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botao_add_mat)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Action(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Action

         String sqlinsert;
        if(cbMatMaterial.getSelectedItem().toString().equalsIgnoreCase("Outro"))
        {
            sqlinsert = "insert into " +bean +
                " (material,tipo,quantidade," +
                "custo,outros,frequencia,"+chave+") values ('"+
                tfMatOutroMat.getText() + "','" +
                tfMatTipo.getText() + "','" +
                tfMatQuantidade.getText() + "','" +
                tfMatCusto.getText() + "','" +
                tfMatOutros.getText() + "','" +
                tfMatFrequencia.getText() + "'," +
                id+")";
        }else
        {
             sqlinsert = "insert into " +bean +
                " (material,tipo,quantidade," +
                "custo,outros,frequencia,"+chave+") values ('"+
                cbMatMaterial.getSelectedItem().toString() + "','" +
                tfMatTipo.getText() + "','" +
                tfMatQuantidade.getText() + "','" +
                tfMatCusto.getText() + "','" +
                tfMatOutros.getText() + "','" +
                tfMatFrequencia.getText() + "'," +
                id+")";
        }        
        conexao.salvar(sqlinsert);
        //agora é hora de atualizar o resultset
        this.dispose();

    }//GEN-LAST:event_Action

    private void cbMatMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMatMaterialActionPerformed
    }//GEN-LAST:event_cbMatMaterialActionPerformed

    private void cbMatMaterialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMatMaterialItemStateChanged
        if (cbMatMaterial.getSelectedItem() == "Outro") {
            tfMatOutroMat.setEditable(true);
        } else {
            tfMatOutroMat.setEditable(false);
        }
    }//GEN-LAST:event_cbMatMaterialItemStateChanged

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_add_mat;
    private javax.swing.JComboBox cbMatMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tfMatCusto;
    private javax.swing.JTextField tfMatFrequencia;
    private javax.swing.JTextField tfMatOutroMat;
    private javax.swing.JTextField tfMatOutros;
    private javax.swing.JTextField tfMatQuantidade;
    private javax.swing.JTextField tfMatTipo;
    // End of variables declaration//GEN-END:variables

    public Object registro_q_vai() {
        if (tfMatOutroMat.isEditable()) {
            return tfMatOutroMat.getText();
        } else {
            return cbMatMaterial.getSelectedItem();
        }
    }
}
