package br.com.formulario.pescador;

import br.com.conexao.Conexao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;


/**
 *
 * @author Jhonathas
 */
public class pescador_3 extends javax.swing.JFrame {

    private int navega = 0; //variavel pra saber o  botão clicado;
    private int inicia_combo = 0;
    private boolean state = false;

    private Conexao conexao;


    public pescador_3() {
        initComponents(); //Inicializa os componentes da tela
        conexao = new Conexao();
        conexao.conecta("mil_interface");
              
        //Insere nomes do município no cbMunicipio
        try {
            conexao.execute("select * FROM tab_local where pai='Pará' or pai='Maranhão' or pai='Amapá' ");
            while (conexao.resultSet.next()){
                cbPescador.addItem(conexao.resultSet.getString("nome"));
                //System.out.println(conexao.resultSet.getString("nome"));
            }
        }catch (SQLException ex) {
            Logger.getLogger(pescador_3.class.getName()).log(Level.SEVERE, null, ex);
        }

        conexao.execute("select * from atravessador_cadastro");

        try {
            conexao.resultSet.first();
            mostra_dados_atravessador();


        }catch (SQLException ex) {
            Logger.getLogger(pescador_3.class.getName()).log(Level.SEVERE, null, ex);
        }

       /*
        Teste que mostra toda a tabela selecionada
        try {
            while (conexao.resultSet.next()){
            System.out.println(conexao.resultSet.getString("nome"));
            }
        }catch (SQLException ex) {
            Logger.getLogger(pescador.class.getName()).log(Level.SEVERE, null, ex);
        }
       */
        
        


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_questao_1 = new javax.swing.ButtonGroup();
        grupo_questao_2 = new javax.swing.ButtonGroup();
        grupo_questao_3 = new javax.swing.ButtonGroup();
        grupo_questao_4 = new javax.swing.ButtonGroup();
        grupo_questao_5 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        cbPescador = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taQuestao5 = new javax.swing.JTextArea();
        rbQ1sim = new javax.swing.JRadioButton();
        rbQ1nao = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        rbQ2Aumentando = new javax.swing.JRadioButton();
        rbQ2Diminuindo = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        rbQ3Sim = new javax.swing.JRadioButton();
        rbQ3Nao = new javax.swing.JRadioButton();
        chbQ3TrocadeOleo = new javax.swing.JCheckBox();
        chbQ3TrocadePescado = new javax.swing.JCheckBox();
        chbQ3TrocadeAlimentos = new javax.swing.JCheckBox();
        chbQ3Rebocar = new javax.swing.JCheckBox();
        chbQ3Outros = new javax.swing.JCheckBox();
        rbQ4Sim = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        chbQ4Outros = new javax.swing.JCheckBox();
        chbQ4PorRoubodeRede = new javax.swing.JCheckBox();
        chbQ4PorPesqueiros = new javax.swing.JCheckBox();
        rbQ4Nao = new javax.swing.JRadioButton();
        chbQ4PorSobreposicaoDeRedeEEspinhel = new javax.swing.JCheckBox();
        chbQ4PorSobreposicaodeRedes = new javax.swing.JCheckBox();
        rbQ5Sim = new javax.swing.JRadioButton();
        rbQ5Nao = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        taQuestao6 = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        taQuestao7 = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        taQuestao8 = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        taQuestao9 = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        taQuestao10 = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        chbQuestao11DeCrescimento = new javax.swing.JCheckBox();
        chbQuestao11Estabilizacao = new javax.swing.JCheckBox();
        chbQuestao11DeDiminuicao = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Questionário Atravessador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fechar_janela(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);

        jLabel24.setText("Pesacador");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setText("Questionário Pescador");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel42)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setText("Percepção e Perspectivas:");

        jLabel25.setText("1 - Percebeu aumento no número de pescadores nos últimos 10 anos? ");

        taQuestao5.setColumns(20);
        taQuestao5.setRows(5);
        jScrollPane5.setViewportView(taQuestao5);

        grupo_questao_1.add(rbQ1sim);
        rbQ1sim.setText("Sim");

        grupo_questao_1.add(rbQ1nao);
        rbQ1nao.setText("Não");

        jLabel26.setText("2 - O número de barcos está aumentando ou diminuindo em relação a 10 anos atrás?");

        grupo_questao_2.add(rbQ2Aumentando);
        rbQ2Aumentando.setText("Aumentando");

        grupo_questao_2.add(rbQ2Diminuindo);
        rbQ2Diminuindo.setText("Diminuindo");

        jLabel27.setText("3 - Existe alguma interação entre os pescadores em relação à troca, cooperação dos produtos?");

        grupo_questao_3.add(rbQ3Sim);
        rbQ3Sim.setText("Sim");

        grupo_questao_3.add(rbQ3Nao);
        rbQ3Nao.setText("Não");

        chbQ3TrocadeOleo.setText("Troca de óleo");

        chbQ3TrocadePescado.setText("Troca de pescado ou grude");

        chbQ3TrocadeAlimentos.setText("Troca de alimentos");

        chbQ3Rebocar.setText("Rebocar");

        chbQ3Outros.setText("Outros");

        grupo_questao_4.add(rbQ4Sim);
        rbQ4Sim.setText("Sim");

        jLabel28.setText("4 - Existe alguma competitividade/rivalidade entre os pescadores?");

        chbQ4Outros.setText("Outros");

        chbQ4PorRoubodeRede.setText("Por roubo de rede");

        chbQ4PorPesqueiros.setText("Por pesqueiros");

        grupo_questao_4.add(rbQ4Nao);
        rbQ4Nao.setText("Não");

        chbQ4PorSobreposicaoDeRedeEEspinhel.setText("Por sobreposição de rede e espinhel");

        chbQ4PorSobreposicaodeRedes.setText("Por sobreposição de redes");

        grupo_questao_5.add(rbQ5Sim);
        rbQ5Sim.setText("Sim");

        grupo_questao_5.add(rbQ5Nao);
        rbQ5Nao.setText("Não. Por que?");

        jLabel29.setText("5 - Pretende continuar na atividade?");

        jLabel30.setText("6 - Existem conflitos com instituições (IBAMA, MPA, SEPAQ)? Quais instituições e descrever conflitos.");

        taQuestao6.setColumns(20);
        taQuestao6.setRows(5);
        jScrollPane6.setViewportView(taQuestao6);

        jLabel31.setText("7 - O que mudeou na pescaria nos últimos 10 anos? Como era a 10 anos atrás?");

        taQuestao7.setColumns(20);
        taQuestao7.setRows(5);
        jScrollPane7.setViewportView(taQuestao7);

        jLabel32.setText("8 - O que está acontecendo com o tamanho e a quantidade de pescado?");

        taQuestao8.setColumns(20);
        taQuestao8.setRows(5);
        jScrollPane8.setViewportView(taQuestao8);

        jLabel33.setText("9 - Qual o motivo dessas mudanças?");

        taQuestao9.setColumns(20);
        taQuestao9.setRows(5);
        jScrollPane9.setViewportView(taQuestao9);

        jLabel34.setText("10 - O que acha que deveria ser feito pra solucionar?");

        taQuestao10.setColumns(20);
        taQuestao10.setRows(5);
        jScrollPane10.setViewportView(taQuestao10);

        jLabel35.setText("11 - Pretende continuar na atividade?");

        chbQuestao11DeCrescimento.setText("De crescimento");

        chbQuestao11Estabilizacao.setText("Estabilização");

        chbQuestao11DeDiminuicao.setText("De diminuição");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbPescador, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel43)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbQ1sim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbQ1nao))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbQ2Aumentando)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbQ2Diminuindo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbQ3Sim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbQ3Nao))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(chbQ4PorSobreposicaoDeRedeEEspinhel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chbQ4PorRoubodeRede)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chbQ4Outros))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(chbQ4PorPesqueiros)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chbQ4PorSobreposicaodeRedes))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbQ4Sim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbQ4Nao))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbQ5Sim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbQ5Nao))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(chbQ3TrocadeOleo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbQ3TrocadePescado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbQ3TrocadeAlimentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbQ3Rebocar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbQ3Outros))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(161, 161, 161))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(161, 161, 161))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(161, 161, 161))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(161, 161, 161))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(161, 161, 161))
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(chbQuestao11DeCrescimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbQuestao11Estabilizacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbQuestao11DeDiminuicao))
                            .addComponent(jLabel35))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPescador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(rbQ1sim)
                    .addComponent(rbQ1nao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(rbQ2Aumentando)
                    .addComponent(rbQ2Diminuindo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(rbQ3Sim)
                    .addComponent(rbQ3Nao))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbQ3TrocadeOleo)
                    .addComponent(chbQ3TrocadePescado)
                    .addComponent(chbQ3TrocadeAlimentos)
                    .addComponent(chbQ3Rebocar)
                    .addComponent(chbQ3Outros))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(rbQ4Sim)
                    .addComponent(rbQ4Nao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbQ4PorPesqueiros)
                    .addComponent(chbQ4PorSobreposicaodeRedes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbQ4PorSobreposicaoDeRedeEEspinhel)
                    .addComponent(chbQ4PorRoubodeRede)
                    .addComponent(chbQ4Outros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(rbQ5Sim)
                    .addComponent(rbQ5Nao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbQuestao11DeCrescimento)
                    .addComponent(chbQuestao11Estabilizacao)
                    .addComponent(chbQuestao11DeDiminuicao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-779)/2, (screenSize.height-516)/2, 779, 516);
    }// </editor-fold>//GEN-END:initComponents

    private void fechar_janela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar_janela
        conexao.desconecta();
    }//GEN-LAST:event_fechar_janela

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pescador_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbPescador;
    private javax.swing.JCheckBox chbQ3Outros;
    private javax.swing.JCheckBox chbQ3Rebocar;
    private javax.swing.JCheckBox chbQ3TrocadeAlimentos;
    private javax.swing.JCheckBox chbQ3TrocadeOleo;
    private javax.swing.JCheckBox chbQ3TrocadePescado;
    private javax.swing.JCheckBox chbQ4Outros;
    private javax.swing.JCheckBox chbQ4PorPesqueiros;
    private javax.swing.JCheckBox chbQ4PorRoubodeRede;
    private javax.swing.JCheckBox chbQ4PorSobreposicaoDeRedeEEspinhel;
    private javax.swing.JCheckBox chbQ4PorSobreposicaodeRedes;
    private javax.swing.JCheckBox chbQuestao11DeCrescimento;
    private javax.swing.JCheckBox chbQuestao11DeDiminuicao;
    private javax.swing.JCheckBox chbQuestao11Estabilizacao;
    private javax.swing.ButtonGroup grupo_questao_1;
    private javax.swing.ButtonGroup grupo_questao_2;
    private javax.swing.ButtonGroup grupo_questao_3;
    private javax.swing.ButtonGroup grupo_questao_4;
    private javax.swing.ButtonGroup grupo_questao_5;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JRadioButton rbQ1nao;
    private javax.swing.JRadioButton rbQ1sim;
    private javax.swing.JRadioButton rbQ2Aumentando;
    private javax.swing.JRadioButton rbQ2Diminuindo;
    private javax.swing.JRadioButton rbQ3Nao;
    private javax.swing.JRadioButton rbQ3Sim;
    private javax.swing.JRadioButton rbQ4Nao;
    private javax.swing.JRadioButton rbQ4Sim;
    private javax.swing.JRadioButton rbQ5Nao;
    private javax.swing.JRadioButton rbQ5Sim;
    private javax.swing.JTextArea taQuestao10;
    private javax.swing.JTextArea taQuestao5;
    private javax.swing.JTextArea taQuestao6;
    private javax.swing.JTextArea taQuestao7;
    private javax.swing.JTextArea taQuestao8;
    private javax.swing.JTextArea taQuestao9;
    // End of variables declaration//GEN-END:variables


    public void mostra_dados_atravessador(){
        try {

            
           

            //System.out.println(conexao.resultSet.getString("local_moradia"));
            
          
            
            cbPescador.setSelectedItem(conexao.resultSet.getString("id_local"));
       


        }catch (SQLException ex) {
            if (navega == 1){
                JOptionPane.showMessageDialog(null,"Você já esta no primeiro registro");
                proximo();
            }
            else if (navega == 2){
                JOptionPane.showMessageDialog(null,"Você já esta no ultimo registro");
                anterior();
            }
            else
                JOptionPane.showMessageDialog(null,"Nenhum registro encontrado "+ ex );
            navega = 0;
            //Logger.getLogger(pescador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void anterior() {
         try {
                    conexao.resultSet.previous();
                } catch (SQLException ex1) {
                    Logger.getLogger(pescador_3.class.getName()).log(Level.SEVERE, null, ex1);
                }
    }

    private void proximo() {
        try {
                    conexao.resultSet.next();
                } catch (SQLException ex1) {
                    Logger.getLogger(pescador_3.class.getName()).log(Level.SEVERE, null, ex1);
                }
    }
    
private int checar(JCheckBox ckb) {
        if (ckb.isSelected()){
            return 1;
        }else
            return 0;
    }


}
