/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * comunidade_questionariomercadofeira.java
 *
 * Created on 09/08/2010, 10:38:53
 */

package br.com.bean4;

import br.com.Persistencia.Conexao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.DocFlavor.STRING;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Home
 */
public class comunidade_questionariomercadofeira extends javax.swing.JFrame {

      private Conexao conexao;

    /** Creates new form comunidade_questionariomercadofeira */
    public comunidade_questionariomercadofeira() {
        initComponents();
        conexao = new Conexao();
        conexao.conecta("mil_interface");
        // adiciona o municipio no combobox//
         try {
            conexao.execute("select * FROM tab_local where pai='Pará'");
            while (conexao.resultSet.next()){
                cbMunicipio.addItem(conexao.resultSet.getString("nome"));
                //System.out.println(conexao.resultSet.getString("nome"));
            }
        }catch (SQLException ex) {
             System.out.println(ex);
        }

        //Exibe logo de inicio
        conexao.execute("select * from mercado_questionario");
        try {
            conexao.resultSet.first();
            exibir_dados();

        } catch (Exception e) {
        }


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMunicipio = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfApelido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfNaturalidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        tfIdade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfAtividadePrincipal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfAtividadeSecundaria = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfBoxes = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfQuantosPossui = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbEstadoCivil = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        tfComposicaoFamilia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfEscolaridade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfPorQueParou = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbLocalMoradia = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        cbQualidadeMoradia = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        tfTipoConstrucao = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfAlgumaAssociacao = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfOrgaoCarteiraPescado = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tfEntrevistado = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tfEsposa = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tfFilhos = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        tfNetos = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        tfTempoTrabalho = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        tfTempoAtividade = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpPlanoSaude = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpRendaFamiliar = new javax.swing.JTextPane();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtMaterialUtilizado = new javax.swing.JTable();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jbOrigemProduto = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jbDadosEspecie = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        cbEspecie = new javax.swing.JComboBox();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tpQuestao1 = new javax.swing.JTextPane();
        tfQualColonia = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tpQuestao2 = new javax.swing.JEditorPane();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tpQuestao3 = new javax.swing.JTextArea();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tpQuestao4 = new javax.swing.JEditorPane();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tpQuestao5 = new javax.swing.JTextPane();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tpQuestao6 = new javax.swing.JTextPane();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        tpQuestao7 = new javax.swing.JTextPane();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        tpquestao8 = new javax.swing.JTextPane();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        tpQuestao9 = new javax.swing.JTextPane();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        tpQuestao10 = new javax.swing.JTextPane();
        rbMercado = new javax.swing.JRadioButton();
        rbFeiraLivre = new javax.swing.JRadioButton();
        botao_primeiro = new javax.swing.JButton();
        botao_anterior = new javax.swing.JButton();
        botao_proximo = new javax.swing.JButton();
        botao_ultimo = new javax.swing.JButton();
        ckbCriancaEnvolvidas = new javax.swing.JCheckBox();
        ckbInss = new javax.swing.JCheckBox();
        ckbColonia = new javax.swing.JCheckBox();
        ckbAlgumaAssociacao = new javax.swing.JCheckBox();
        ckbCarteiraPescado = new javax.swing.JCheckBox();
        botao_limpar = new javax.swing.JButton();
        botao_cadastrar = new javax.swing.JButton();
        botao_Excluir = new javax.swing.JButton();
        botao_alterar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ckbFamiliar = new javax.swing.JCheckBox();
        ckbArtesanalComVizinho = new javax.swing.JCheckBox();
        ckbArmadorEmbarcacao = new javax.swing.JCheckBox();
        ckbAssalariado = new javax.swing.JCheckBox();
        jbExcluir = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jbPerdaPescado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setText("Questionário-Mercado/Feira");

        jLabel2.setText("Município:");

        cbMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMunicipioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setText("Dados Pessoais ");

        jLabel4.setText("Nome :");

        jLabel5.setText("Apelido:");

        jLabel6.setText("Naturalidade:");

        jLabel7.setText("Sexo:");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FEMININO", "MASCULINO" }));

        jLabel8.setText("Idade:");

        jLabel9.setText("Atividade principal de renda :");

        jLabel10.setText("Atividade secundária:");

        jLabel11.setText("Número total de boxes no local ?");

        tfBoxes.setText("0");

        jLabel12.setText("Quantos você possui ?");

        tfQuantosPossui.setText("0");

        jLabel13.setText("Estado Civil:");

        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SOLTEIRO", "CASADO", "UNIÃO ESTÁVEL" }));

        jLabel14.setText("Composição Familiar:");

        jLabel15.setText("Escolaridade:");

        jLabel16.setText("Por que parou ?");

        jLabel17.setText("Local de Moradia:");

        cbLocalMoradia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sede Municipal", "Comunidade/ vila local", "Outro Município", "Capital" }));

        jLabel18.setText("Qualidade da Moradia:");

        cbQualidadeMoradia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Péssima", "Ruim", "Regular", "Boa", "òtima" }));

        jLabel19.setText("Tipo de Construçao:");

        jLabel20.setText("Possui Regristo no INSS ?");

        jLabel21.setText("Na Colônia?");

        jLabel22.setText("Qual colonia?");

        jLabel23.setText("Em Alguma Associação:");

        jLabel24.setText("Qual :");

        jLabel25.setText("Possui carteira de Pescador ?");

        jLabel26.setText("Qual Orgão?");

        jLabel27.setText("Relação de Trabalho:");

        jLabel28.setText("Possui assisência ao plano de saúde.Especificar:");

        jLabel29.setText("Quais as atividades geram renda para sua família ?");

        jLabel30.setText("Quem na sua família trabalha ? E com qual atividade?");

        jLabel31.setText("Entrevistado:");

        jLabel33.setText("Esposa:");

        jLabel34.setText("Filhos:");

        jLabel35.setText("Netos:");

        jLabel36.setText("Quanto o tempo diário que passam trabalhando ?");

        jLabel37.setText("Quanto tempo esta na atividade ?");

        jScrollPane2.setViewportView(tpPlanoSaude);

        jScrollPane3.setViewportView(tpRendaFamiliar);

        jLabel38.setText("Quais são os gastos com material utilizado na atividade (estimar em frênquencia dos gastos- 1x por semana,por viagem, por mês, etc ).");

        jtMaterialUtilizado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_mercado", "quantidade", "custo", "outros", "frequência"
            }
        ));
        jScrollPane5.setViewportView(jtMaterialUtilizado);
        jtMaterialUtilizado.getColumnModel().getColumn(4).setResizable(false);

        jLabel39.setText("Origem do Produto");

        jbOrigemProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Empresa ", "Pescadores diverso", "Cooperativa", "outros"
            }
        ));
        jScrollPane6.setViewportView(jbOrigemProduto);

        jLabel40.setText("Dados das especies ");

        jbDadosEspecie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "null", "Especie", "Quantidade fresco", "Quantidade Salgado", "Preço Fresco", "Preço Salgado", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jbDadosEspecie);

        jLabel41.setText("Quais as principais perdas de pescado em função da :");

        jLabel42.setText("Espécie:");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel43.setText("Percepção Ambiental e Perspectivas:");

        jLabel44.setText("Existe alguma interação entre os vendedores em relaçãoa troca ou cooperação dos produtos, etc ?");

        jScrollPane8.setViewportView(tpQuestao1);

        jLabel45.setText("Qual o grau de competitividade/rivalidade entre os atravesadores ? ");

        jScrollPane9.setViewportView(tpQuestao2);

        jLabel46.setText("A sazonalidade influencia na disponibilidade do pescador para a venda ?");

        tpQuestao3.setColumns(20);
        tpQuestao3.setRows(5);
        jScrollPane10.setViewportView(tpQuestao3);

        jLabel47.setText("Você acredita que as mudanças no clima podem influenciar nas pesca? Como?");

        jScrollPane11.setViewportView(tpQuestao4);

        jLabel48.setText("O que está acontecendo com o tamanho e a quantidade de pescado ?");

        jScrollPane12.setViewportView(tpQuestao5);

        jLabel49.setText("Você sabe informar quais os motivos responsáveis pela diminuição ?");

        jScrollPane13.setViewportView(tpQuestao6);

        jLabel50.setText("Caso ocorra odesaparecimento do pescado, como você sustentaria a sua familia ?");

        jScrollPane14.setViewportView(tpQuestao7);

        jLabel51.setText("Existem crianças envolvidas nessa pesca ?");

        jLabel52.setText("Você deseja que seus filhos também sejam comerciantes ? Por que? (pespectiva do pescador quanto ao futuro dos filhos)");

        jScrollPane15.setViewportView(tpquestao8);

        jLabel53.setText("Existe algum comflito entre os comerciantes na feira/mercado ?");

        jScrollPane16.setViewportView(tpQuestao9);

        jLabel54.setText("Quais as dificuldades (gargalos) encontradas para manter a atividade de venda ? Quais as possiveis soluções(demanda) para melhorar o seu trabalhos ?");

        jScrollPane17.setViewportView(tpQuestao10);

        buttonGroup1.add(rbMercado);
        rbMercado.setText("Mercado");

        buttonGroup1.add(rbFeiraLivre);
        rbFeiraLivre.setText("Feira Livre");

        botao_primeiro.setText("<<");
        botao_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_primeiroActionPerformed(evt);
            }
        });

        botao_anterior.setText("<");
        botao_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_anteriorActionPerformed(evt);
            }
        });

        botao_proximo.setText(">");
        botao_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_proximoActionPerformed(evt);
            }
        });

        botao_ultimo.setText(">>");
        botao_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ultimoActionPerformed(evt);
            }
        });

        ckbCriancaEnvolvidas.setText("Sim");

        ckbInss.setText("SIm");

        ckbColonia.setText("Sim");

        ckbAlgumaAssociacao.setText("Sim");

        ckbCarteiraPescado.setText("Sim");

        botao_limpar.setText("Limpar");
        botao_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_limparActionPerformed(evt);
            }
        });

        botao_cadastrar.setText("Cadastrar");
        botao_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastrarActionPerformed(evt);
            }
        });

        botao_Excluir.setText("Excluir");
        botao_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ExcluirActionPerformed(evt);
            }
        });

        botao_alterar.setText("Alterar");
        botao_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ckbFamiliar.setText("Familiar");

        ckbArtesanalComVizinho.setText("Artesanal com vizinho, amigos,etc");

        ckbArmadorEmbarcacao.setText("Armador ou Embarcação");

        ckbAssalariado.setText("Assalariado");

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbAtualizar.setText("Atualizer");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jbPerdaPescado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Causa da Perda", "Estimativa de preço(%) ", "Destino do peixe perdido"
            }
        ));
        jScrollPane4.setViewportView(jbPerdaPescado);
        jbPerdaPescado.getColumnModel().getColumn(2).setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfAtividadePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfAtividadeSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfBoxes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfQuantosPossui, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfTipoConstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ckbFamiliar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ckbArtesanalComVizinho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ckbArmadorEmbarcacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ckbAssalariado))
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ckbCarteiraPescado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel26)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfOrgaoCarteiraPescado))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ckbInss)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ckbColonia)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfQualColonia))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ckbAlgumaAssociacao)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfAlgumaAssociacao, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfComposicaoFamilia))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(178, 178, 178)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfPorQueParou, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbMercado))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(10, 10, 10)
                                        .addComponent(tfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rbFeiraLivre)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfEntrevistado, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfEsposa, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNetos, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbAtualizar)
                                    .addComponent(jbExcluir)
                                    .addComponent(jButton1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTempoTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfTempoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel39)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbLocalMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbQualidadeMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1)))
                .addContainerGap(21789, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(botao_primeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botao_anterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botao_proximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botao_ultimo)
                .addGap(40, 40, 40)
                .addComponent(botao_limpar)
                .addGap(14, 14, 14)
                .addComponent(botao_cadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botao_alterar)
                .addContainerGap(21964, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21980, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43)
                .addContainerGap(22090, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44)
                .addContainerGap(22054, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addGap(22083, 22083, 22083))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45)
                .addContainerGap(22204, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22093, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel46)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel47)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane11, 0, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel48)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel49)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50)
                .addContainerGap(22138, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 22530, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbCriancaEnvolvidas)
                .addContainerGap(22280, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel52)
                .addContainerGap(21949, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22048, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel53)
                .addContainerGap(22228, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22099, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel54)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(941, 941, 941)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_primeiro)
                            .addComponent(botao_anterior)
                            .addComponent(botao_proximo)
                            .addComponent(botao_ultimo)
                            .addComponent(botao_limpar)
                            .addComponent(botao_cadastrar)
                            .addComponent(botao_Excluir)
                            .addComponent(botao_alterar))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbMercado)
                                .addComponent(rbFeiraLivre)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(tfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfAtividadePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(tfAtividadeSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfBoxes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(tfQuantosPossui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(tfComposicaoFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(tfPorQueParou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbLocalMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(cbQualidadeMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(tfTipoConstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(tfQualColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbInss)
                            .addComponent(ckbColonia))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(tfAlgumaAssociacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbAlgumaAssociacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(tfOrgaoCarteiraPescado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbCarteiraPescado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(ckbFamiliar)
                            .addComponent(ckbArtesanalComVizinho)
                            .addComponent(ckbArmadorEmbarcacao)
                            .addComponent(ckbAssalariado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(tfEntrevistado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)
                            .addComponent(tfEsposa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(tfFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35)
                            .addComponent(tfNetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(tfTempoTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(tfTempoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbAtualizar)
                                .addGap(5, 5, 5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(cbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(ckbCriancaEnvolvidas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 3016, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMunicipioActionPerformed

    private void botao_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_primeiroActionPerformed
        try {
            conexao.resultSet.first();
            exibir_dados();

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_botao_primeiroActionPerformed

    private void botao_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_anteriorActionPerformed
         try {
            conexao.resultSet.previous();
            exibir_dados();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_botao_anteriorActionPerformed

    private void botao_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_proximoActionPerformed
          try {
            conexao.resultSet.next();
            exibir_dados();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_botao_proximoActionPerformed

    private void botao_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ultimoActionPerformed
     try {
            conexao.resultSet.last();
            exibir_dados();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_botao_ultimoActionPerformed

    private void botao_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_limparActionPerformed
            tfNome.setText("");
            tfApelido.setText("");
            tfNaturalidade.setText("");
            tfIdade.setText("");
            tfAtividadePrincipal.setText("");
            tfAtividadeSecundaria.setText("");
            tfBoxes.setText("");
            tfQuantosPossui.setText("");
            tfComposicaoFamilia.setText("");
            tfEscolaridade.setText("");
            tfPorQueParou.setText("");
            tfTipoConstrucao.setText("");
            tfQualColonia.setText("");
            tfAlgumaAssociacao.setText("");
            tfOrgaoCarteiraPescado.setText("");
            tpPlanoSaude.setText("");
            tpRendaFamiliar.setText("");
            tfEntrevistado.setText("");
            tfEsposa.setText("");
            tfFilhos.setText("");
            tfNetos.setText("");
            tfTempoTrabalho.setText("");
            tfAtividadePrincipal.setText("");
            tpQuestao1.setText("");
            tpQuestao2.setText("");
            tpQuestao3.setText("");
            tpQuestao4.setText("");
            tpQuestao5.setText("");
            tpQuestao6.setText("");
            tpQuestao7.setText("");
            tpquestao8.setText("");
            tpQuestao9.setText("");
            tpQuestao10.setText("");
            cbMunicipio.setSelectedIndex(0);
            buttonGroup1.clearSelection();
            cbSexo.setSelectedIndex(0);
            cbEstadoCivil.setSelectedIndex(0);
            cbLocalMoradia.setSelectedIndex(0);
            cbQualidadeMoradia.setSelectedIndex(0);
            ckbFamiliar.setSelected(false);
            ckbArtesanalComVizinho.setSelected(false);
            ckbArmadorEmbarcacao.setSelected(false);
            ckbAssalariado.setSelected(false);
            ckbInss.setSelected(false);
            ckbColonia.setSelected(false);
            ckbAlgumaAssociacao.setSelected(false);
            ckbCarteiraPescado.setSelected(false);
            ckbCriancaEnvolvidas.setSelected(false);

    }//GEN-LAST:event_botao_limparActionPerformed

    private void botao_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarActionPerformed
        // Para Gravar no banco de dados
      int[] ckb = new int[11];
      if (ckbInss.isSelected()){
        ckb[0]=1;
      } else
        ckb[0]=0;
    if (ckbColonia.isSelected()){
          ckb[1]=1;
      }else
          ckb[1]=0;
    if (ckbAlgumaAssociacao.isSelected()){
          ckb[2]=1;
      }else
          ckb[2]=0;
    if(ckbCarteiraPescado.isSelected()){
           ckb[3]=1;
       }else
           ckb[3]=0;
    if (ckbCriancaEnvolvidas.isSelected()){
          ckb[4]=1;
      }else
          ckb[4]=0;
     if(rbMercado.isSelected()){
           ckb[5]=1;
       }else
           ckb[5]=0;
     if(rbFeiraLivre.isSelected()){
          ckb[6]=1;
       }else
          ckb[6]=0;
      if (ckbFamiliar.isSelected()){
           ckb[7]=1;
      }else
          ckb[7]=0;
       if (ckbArtesanalComVizinho.isSelected()){
            ckb[8]=1;
       }else
           ckb[8]=0;
       if (ckbArmadorEmbarcacao.isSelected()){
            ckb[9]=1;
        }else
            ckb[9]=0;
        if (ckbAssalariado.isSelected()){
            ckb[10]=1;
        }else
            ckb[10]=0;
        try {
          String sqlinsert = "insert into mercado_questionario"
             + "(nome_municipio,e_mercado,e_fera_livre,nome,apelido,naturalidade,"
             + "sexo,idade,atividade_principal,atividade_secundaria,"
             + "boxe_local,quantos_possui,estado_civil,composicao_familiar,"
             + "escolaridade,pq_parou,local_moradia,qualidade_moradia,"
             + "tipo_construcao,inss,na_colonia,qual_colonia,"
             + "alguma_associacao,qual_associacao,carteira_pescador,orgao_carteira_pesca,relacao_trab_familiar"
             + ",relacao_trab_artesanal,relacao_trab_armador,relacao_trab_assalariado,plano_saude,atividade_renda_familiar,entrevistado,esposa,filhos,"
             + "netos,tempo_diario_trabalho,periodo_atividade,periodo_atividade"
             + "questao1,questao2,questao3,questao4,questao5,questao6,questao7,questao8,questao9,questao9,questao10,questao11 ) values('" +
              cbMunicipio.getSelectedItem()+"',"+
              ckb[5]+","+
              ckb[6]+",'"+
              tfNome.getText()+"','"+
              tfApelido.getText()+"','"+
              tfNaturalidade.getText()+"','"+
              cbSexo.getSelectedIndex()+"',"+
              tfIdade.getText()+",'"+
              tfAtividadePrincipal.getText()+"','"+
              tfAtividadeSecundaria.getText()+"',"+
              tfBoxes.getText()+","+
              tfQuantosPossui.getText()+",'"+
              cbEstadoCivil.getSelectedIndex()+"','"+
              tfComposicaoFamilia.getText()+"',"+
              tfEscolaridade.getText()+",'"+
              tfPorQueParou.getText()+"','"+
              cbLocalMoradia.getSelectedIndex()+"','"+
              cbQualidadeMoradia.getSelectedIndex()+"','"+
              tfTipoConstrucao.getText()+"',"+
              ckb[0]+","+
              ckb[1]+",'"+
              tfQualColonia.getText()+"','"+
              ckb[2]+",'"+
              tfAlgumaAssociacao.getText()+"',"+
              ckb[3]+",'"+
              tfOrgaoCarteiraPescado.getText()+"',"+
              ckb[7]+","+
              ckb[8]+","+
              ckb[9]+","+
              ckb[10]+",'"+
              tpPlanoSaude.getText()+"','"+
              tpRendaFamiliar.getText()+"','"+
              tfEntrevistado.getText()+"','"+
              tfEsposa.getText()+"','"+
              tfFilhos.getText()+"','"+
              tfNetos.getText()+"',"+
              tfTempoTrabalho.getText()+","+
              tfTempoAtividade.getText()+","+
              tpQuestao1.getText()+"','"+
              tpQuestao2.getText()+"','"+
              tpQuestao3.getText()+"','"+
              tpQuestao4.getText()+"','"+
              tpQuestao5.getText()+"','"+
              tpQuestao6.getText()+"','"+
              tpQuestao7.getText()+"','"+
              ckb[4]+
              tpQuestao9.getText()+"','"+
              tpQuestao10.getText()+"','"+")";

            System.out.println(sqlinsert);
            if (conexao.salvar(sqlinsert)) {
                JOptionPane.showMessageDialog(null,"Cadastrado com sucesso");
                //agora é hora de atualizar o resultset
                conexao.execute("select * from comunidade_questionariomarcadofeira ");
                conexao.resultSet.first(); //1º registro
               // mostra_dados_atravessador();
            }
                  
        }catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_botao_cadastrarActionPerformed

    private void botao_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ExcluirActionPerformed
        String sql;
        try {
           sql = "select * from mercado_questionario where id_mercado=" + conexao.resultSet.getString("id_mercado");
           conexao.execute(sql);
           conexao.resultSet.first();
           String name="delete o mercado/feira : "+conexao.resultSet.getString("nome")+" ?";
           int opcao_escolha=JOptionPane.showConfirmDialog(null,name,"Exclusão",JOptionPane.YES_NO_OPTION );
           if (opcao_escolha == JOptionPane.YES_OPTION)
           {
                sql = "DELETE FROM mercado_questionario Where id_mercado ="+conexao.resultSet.getString("id_mercado");
                if (conexao.salvar(sql)) {
                        JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso");
                        //atualiza o ResultSet
                        conexao.execute("select * from mercado_questionario");
                        conexao.resultSet.first();
                        exibir_dados();
                    }
                } else{
                    conexao.execute("select * from mercado_questionario");
                    conexao.resultSet.first();
                    exibir_dados();
                }

            }catch (Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_botao_ExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String id = conexao.resultSet.getString("id_mercado").toString();
            
            new addMaterial(id).setVisible(true);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botao_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarActionPerformed
         int[] ckb = new int[11];
      if (ckbInss.isSelected()){
        ckb[0]=1;
      } else
        ckb[0]=0;
    if (ckbColonia.isSelected()){
          ckb[1]=1;
      }else
          ckb[1]=0;
    if (ckbAlgumaAssociacao.isSelected()){
          ckb[2]=1;
      }else
          ckb[2]=0;
    if(ckbCarteiraPescado.isSelected()){
           ckb[3]=1;
       }else
           ckb[3]=0;
    if (ckbCriancaEnvolvidas.isSelected()){
          ckb[4]=1;
      }else
          ckb[4]=0;
     if(rbMercado.isSelected()){
           ckb[5]=1;
       }else
           ckb[5]=0;
     if(rbFeiraLivre.isSelected()){
          ckb[6]=1;
       }else
          ckb[6]=0;
      if (ckbFamiliar.isSelected()){
           ckb[7]=1;
      }else
          ckb[7]=0;
       if (ckbArtesanalComVizinho.isSelected()){
            ckb[8]=1;
       }else
           ckb[8]=0;
       if (ckbArmadorEmbarcacao.isSelected()){
            ckb[9]=1;
        }else
            ckb[9]=0;
        if (ckbAssalariado.isSelected()){
            ckb[10]=1;
        }else
            ckb[10]=0;

        try {
            String sql= "UPDATE mercado_questionario SET "+
             "nome_municipio= '" +cbMunicipio.getSelectedItem()+"',"+
             "e_mercado= '"+ckb[5]+"',"+
             "e_fera_livre='"+ckb[6]+"',"+
             "nome= '"+tfNome.getText()+"',"+
             "apelido='"+tfApelido.getText()+"'," +
             "naturalidade='"+tfNaturalidade.getText()+"',"+
             "sexo = '"+cbSexo.getSelectedIndex()+"',"+
             "idade= '"+tfIdade.getText()+"',"+
             "atividade_principal ='"+tfAtividadePrincipal.getText()+"',"+
             "atividade_secundaria='"+tfAtividadeSecundaria.getText()+"',"+
             "boxe_local='"+tfBoxes.getText()+"',"+
             "quantos_possui='"+tfQuantosPossui.getText()+"',"+
             "estado_civil='"+cbEstadoCivil.getSelectedIndex()+"',"+
             "composicao_familia='"+tfComposicaoFamilia.getText()+"',"+
             "escolaridade='"+tfEscolaridade.getText()+"',"+
             "pq_parou='"+tfPorQueParou.getText()+"',"+
             "local-moradia='"+cbLocalMoradia.getSelectedIndex()+"',"+
             "qualidade_moradia ='"+cbQualidadeMoradia.getSelectedIndex()+"',"+
             "tipo_construcao='" +tfTipoConstrucao.getText()+"',"+
             "inss='"+ckb[0]+","+
             "na_colonia='"+ckb[1]+",'"+
             "qual_colonia='"+tfQualColonia.getText()+"','"+
             "alguma_associacao='"+ckb[2]+",'"+
             "qual_associacao='"+tfAlgumaAssociacao.getText()+"',"+
             "carteira_pescador='"+ckb[3]+","+
             "orgao_carteira_pesca='"+tfOrgaoCarteiraPescado.getText()+"',"+
             "relacao_trab_familiar='"+ckb[7]+","+
             "relcao_trab_artesanal='"+ ckb[8]+","+
             "relacao_trab_armador='"+ ckb[9]+","+
             "relacao_trab_assalariado='"+ ckb[10]+","+
             "plano_saude='"+tpPlanoSaude.getText()+"','"+
             "atividadde_renda_familiar='"+tpRendaFamiliar.getText()+"','"+
             "entrevistado='"+tfEntrevistado.getText()+"','"+
             "esposa='"+tfEsposa.getText()+"','"+
             "filhos='"+tfFilhos.getText()+"','"+
             "netos='"+tfNetos.getText()+"',"+
             "tempo_diario_trabalho='"+tfTempoTrabalho.getText()+","+
             "periodo_atividade='"+tfTempoAtividade.getText()+","+
             "questao1='"+tpQuestao1.getText()+"','"+
             "questao2='"+tpQuestao2.getText()+"','"+
             "questao3='"+tpQuestao3.getText()+"','"+
             "questao4='"+tpQuestao4.getText()+"','"+
             "questao5='"+tpQuestao5.getText()+"','"+
             "questap6='"+tpQuestao6.getText()+"','"+
             "questao7='"+tpQuestao7.getText()+"','"+
             "questao8='"+ckb[4]+"',"+
             "questao9='"+tpQuestao9.getText()+"','"+
             "questoa10='"+tpQuestao10.getText()+"','"+

             "where id_mercado = "+conexao.resultSet.getString("id_mercado");

              System.out.println(sql);
            if (conexao.update(sql)){
            JOptionPane.showMessageDialog(null,"Alterado com sucesso");
            //Atualiza Resultset
            conexao.execute("select * from quetionario_mercado");
            conexao.resultSet.next();
            exibir_dados();
            }

        } catch (Exception e) {
            System.out.println(e + "Erro no botão alterar");
        }


    }//GEN-LAST:event_botao_alterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
         String id_pra_excluir = "";

        if (jtMaterialUtilizado.getSelectedRow() != -1){
            id_pra_excluir = jtMaterialUtilizado.getValueAt(jtMaterialUtilizado.getSelectedRow(),0).toString()+"";
        }

        if (jbOrigemProduto.getSelectedRow() != -1){
            id_pra_excluir = jbOrigemProduto.getValueAt(jbOrigemProduto.getSelectedRow(),0).toString()+"";
        }

        if (jbDadosEspecie.getSelectedRow() != -1){
            id_pra_excluir = jbDadosEspecie.getValueAt(jbDadosEspecie.getSelectedRow(),0).toString()+"";
        }

        if (jbPerdaPescado.getSelectedRow() != -1){
            id_pra_excluir = jbPerdaPescado.getValueAt(jbPerdaPescado.getSelectedRow(),0).toString()+"";
        }

        System.out.println(id_pra_excluir);

        String sql;

        sql = "delete from mercado_addmercado Where id_mercado =" + id_pra_excluir;

                if (conexao.salvar(sql)) {
                    System.out.println("Exclusão realizada com sucesso");

                    exibir_L_E_N_I(0);exibir_L_E_N_I(1);exibir_L_E_N_I(2);exibir_L_E_N_I(3);

                }else{
                JOptionPane.showMessageDialog(null,"Erro na exclusão");


                }

    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
       conexao.execute("select * from mercado_addmaterial where id_mercado="
                            +pega_codigo_ou_nome(1,cbMunicipio.getSelectedItem().toString())+"");
        preencher_jtable();
        conexao.execute("select * from mercado_cadastro");
    }//GEN-LAST:event_jbAtualizarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comunidade_questionariomercadofeira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_Excluir;
    private javax.swing.JButton botao_alterar;
    private javax.swing.JButton botao_anterior;
    private javax.swing.JButton botao_cadastrar;
    private javax.swing.JButton botao_limpar;
    private javax.swing.JButton botao_primeiro;
    private javax.swing.JButton botao_proximo;
    private javax.swing.JButton botao_ultimo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbEspecie;
    private javax.swing.JComboBox cbEstadoCivil;
    private javax.swing.JComboBox cbLocalMoradia;
    private javax.swing.JComboBox cbMunicipio;
    private javax.swing.JComboBox cbQualidadeMoradia;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JCheckBox ckbAlgumaAssociacao;
    private javax.swing.JCheckBox ckbArmadorEmbarcacao;
    private javax.swing.JCheckBox ckbArtesanalComVizinho;
    private javax.swing.JCheckBox ckbAssalariado;
    private javax.swing.JCheckBox ckbCarteiraPescado;
    private javax.swing.JCheckBox ckbColonia;
    private javax.swing.JCheckBox ckbCriancaEnvolvidas;
    private javax.swing.JCheckBox ckbFamiliar;
    private javax.swing.JCheckBox ckbInss;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JTable jbDadosEspecie;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JTable jbOrigemProduto;
    private javax.swing.JTable jbPerdaPescado;
    private javax.swing.JTable jtMaterialUtilizado;
    private javax.swing.JRadioButton rbFeiraLivre;
    private javax.swing.JRadioButton rbMercado;
    private javax.swing.JTextField tfAlgumaAssociacao;
    private javax.swing.JTextField tfApelido;
    private javax.swing.JTextField tfAtividadePrincipal;
    private javax.swing.JTextField tfAtividadeSecundaria;
    private javax.swing.JTextField tfBoxes;
    private javax.swing.JTextField tfComposicaoFamilia;
    private javax.swing.JTextField tfEntrevistado;
    private javax.swing.JTextField tfEscolaridade;
    private javax.swing.JTextField tfEsposa;
    private javax.swing.JTextField tfFilhos;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JTextField tfNaturalidade;
    private javax.swing.JTextField tfNetos;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfOrgaoCarteiraPescado;
    private javax.swing.JTextField tfPorQueParou;
    private javax.swing.JTextField tfQualColonia;
    private javax.swing.JTextField tfQuantosPossui;
    private javax.swing.JTextField tfTempoAtividade;
    private javax.swing.JTextField tfTempoTrabalho;
    private javax.swing.JTextField tfTipoConstrucao;
    private javax.swing.JTextPane tpPlanoSaude;
    private javax.swing.JTextPane tpQuestao1;
    private javax.swing.JTextPane tpQuestao10;
    private javax.swing.JEditorPane tpQuestao2;
    private javax.swing.JTextArea tpQuestao3;
    private javax.swing.JEditorPane tpQuestao4;
    private javax.swing.JTextPane tpQuestao5;
    private javax.swing.JTextPane tpQuestao6;
    private javax.swing.JTextPane tpQuestao7;
    private javax.swing.JTextPane tpQuestao9;
    private javax.swing.JTextPane tpRendaFamiliar;
    private javax.swing.JTextPane tpquestao8;
    // End of variables declaration//GEN-END:variables

    private void exibir_dados() {
        try {
            tfNome.setText(conexao.resultSet.getString("nome"));
            tfApelido.setText(conexao.resultSet.getString("apelido"));
            tfNaturalidade.setText(conexao.resultSet.getString("naturalidade"));
            tfIdade.setText(conexao.resultSet.getString("idade"));
            tfAtividadePrincipal.setText(conexao.resultSet.getString("atividade_principal"));
            tfAtividadeSecundaria.setText(conexao.resultSet.getString("atividade_secundaria"));
            tfBoxes.setText(conexao.resultSet.getString("boxes_local"));
            tfQuantosPossui.setText(conexao.resultSet.getString("quantos_possui"));
            tfComposicaoFamilia.setText(conexao.resultSet.getString("composicao_familiar"));
            tfEscolaridade.setText(conexao.resultSet.getString("escolaridade"));
            tfPorQueParou.setText(conexao.resultSet.getString("pq_parou"));
            tfTipoConstrucao.setText(conexao.resultSet.getString("tipo_construcao"));
            tfQualColonia.setText(conexao.resultSet.getString("qual_colonia"));
            tfAlgumaAssociacao.setText(conexao.resultSet.getString("qual_associacao"));
            tfOrgaoCarteiraPescado.setText(conexao.resultSet.getString("orgao_carteira_pescado"));
            tpPlanoSaude.setText(conexao.resultSet.getString("plano_saude"));
            tpRendaFamiliar.setText(conexao.resultSet.getString("atividade_renda_familiar"));
            tfEntrevistado.setText(conexao.resultSet.getString("entrevistado"));
            tfEsposa.setText(conexao.resultSet.getString("esposa"));
            tfFilhos.setText(conexao.resultSet.getString("filhos"));
            tfNetos.setText(conexao.resultSet.getString("netos"));
            tfTempoTrabalho.setText(conexao.resultSet.getString("tempo_diario_trabalhando"));
            tfAtividadePrincipal.setText(conexao.resultSet.getString("periodo_atividade"));
            tpQuestao1.setText(conexao.resultSet.getString("Questao1"));
            tpQuestao2.setText(conexao.resultSet.getString("Questao2"));
            tpQuestao3.setText(conexao.resultSet.getString("Questao3"));
            tpQuestao4.setText(conexao.resultSet.getString("Questao4"));
            tpQuestao5.setText(conexao.resultSet.getString("Questao5"));
            tpQuestao6.setText(conexao.resultSet.getString("Questao6"));
            tpQuestao7.setText(conexao.resultSet.getString("Questao7"));
            tpquestao8.setText(conexao.resultSet.getString("Questao8"));
            tpQuestao9.setText(conexao.resultSet.getString("Questao9"));
            tpQuestao10.setText(conexao.resultSet.getString("Questao10"));
            



            if (conexao.resultSet.getString("e_mercado").equals("1"))
                   rbMercado.setSelected(true);
            else
                   rbMercado.setSelected(false);

            if (conexao.resultSet.getString("e_fera_livre").equals("1"))
                   rbFeiraLivre.setSelected(true);
            else
                   rbFeiraLivre.setSelected(false);

            if (conexao.resultSet.getString("questao8").equals("1"))
                   ckbCriancaEnvolvidas.setSelected(true);
            else
                   ckbCriancaEnvolvidas.setSelected(false);



        } catch (Exception e) {
        }
    }


    private String values(String string) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

     public String pega_codigo_ou_nome(int n,String teste) { //Se entrar com 1 pega o Código, se não pega o Nome
              //pegar a Id do caminhoneiro

              //aqui ele pega a quantidade de carcteres que tem uma determinada variável
              //e armazena numa INT para usá-la de contador
              int contador = teste.length();

              //cria um for( para fazer uma varredura letra por letra até encontrar
              for(int i = 0;i<contador;i++){
                 //usamos substring pra pegar um caractere, passando como parâmetro,
                 //o primeiro caractere a ser pega, até a ultima.
                //fiz um if para verificar se o caractere é igual a "#"
                if (teste.substring(i,i+1).equals("#")){
                   int posicao = i+1;
                    System.out.println("Está na posição " + posicao);
                    if (n == 1){
                        return teste.substring(0,posicao-2);
                    }
                    else
                        return teste.substring(posicao+1,teste.length());
                }

              }
              return "nada";
    }
  public void preencher_jtable(){
        jtMaterialUtilizado.getColumnModel().getColumn(0).setMaxWidth(0);
        jtMaterialUtilizado.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtMaterialUtilizado.getColumnModel().getColumn(1).setPreferredWidth(40);
        jtMaterialUtilizado.getColumnModel().getColumn(2).setPreferredWidth(10);
        jtMaterialUtilizado.getColumnModel().getColumn(3).setPreferredWidth(10);
        jtMaterialUtilizado.getColumnModel().getColumn(4).setPreferredWidth(10);
        jtMaterialUtilizado.getColumnModel().getColumn(5).setPreferredWidth(10);
        jtMaterialUtilizado.getColumnModel().getColumn(6).setPreferredWidth(10);

        DefaultTableModel modelo = (DefaultTableModel)jtMaterialUtilizado.getModel();
        modelo.setNumRows(0);//limpa o JTable1;

        try{
            while (conexao.resultSet.next())
                modelo.addRow(new Object[]{conexao.resultSet.getString("id_material"),
                                           conexao.resultSet.getString("nome"),
                                           conexao.resultSet.getString("tipo"),
                                           conexao.resultSet.getString("quantidade"),
                                           conexao.resultSet.getString("custo"),
                                           conexao.resultSet.getString("outros"),
                                           conexao.resultSet.getString("frequencia")});

            conexao.resultSet.first();
        }catch (SQLException erro){
            System.out.println(erro);
        }
}

     public void preencher_jtableMercado(JTable table){
        table.getColumnModel().getColumn(0).setMaxWidth(0);
        table.getColumnModel().getColumn(0).setPreferredWidth(0);
        table.getColumnModel().getColumn(1).setPreferredWidth(40);
        table.getColumnModel().getColumn(2).setPreferredWidth(10);
        table.getColumnModel().getColumn(3).setPreferredWidth(10);
        table.getColumnModel().getColumn(4).setPreferredWidth(10);
        table.getColumnModel().getColumn(5).setPreferredWidth(10);

        DefaultTableModel modelo = (DefaultTableModel)table.getModel();
        modelo.setNumRows(0);//limpa o JTable;

        try{
            while (conexao.resultSet.next())
                modelo.addRow(new Object[]{conexao.resultSet.getString("id_mercado"),
                                           conexao.resultSet.getString("especie"),
                                           conexao.resultSet.getString("produto"),
                                           conexao.resultSet.getString("destino"),
                                           conexao.resultSet.getString("volume")+" "+conexao.resultSet.getString("unidade_volume"),
                                           conexao.resultSet.getString("preco")});

            conexao.resultSet.first();
        }catch (SQLException erro){
            System.out.println(erro);
        }



    }

          public void preencher_jtableEspecie(){
        jtEspecie.getColumnModel().getColumn(0).setMaxWidth(0);
        jtEspecie.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtEspecie.getColumnModel().getColumn(1).setPreferredWidth(10);
        jtEspecie.getColumnModel().getColumn(2).setPreferredWidth(10);
        jtEspecie.getColumnModel().getColumn(3).setPreferredWidth(10);
        jtEspecie.getColumnModel().getColumn(4).setPreferredWidth(10);

        DefaultTableModel modelo = (DefaultTableModel)jtEspecie.getModel();
        modelo.setNumRows(0);//limpa o JTable;

        try{
            while (conexao.resultSet.next())
                modelo.addRow(new Object[]{conexao.resultSet.getString("id_especie"),
                                           conexao.resultSet.getString("especie"),
                                           conexao.resultSet.getString("causa_da_perda"),
                                           conexao.resultSet.getString("estimativa_da_perda"),
                                           conexao.resultSet.getString("destino_do_peixe_perdido")});

            conexao.resultSet.first();
        }catch (SQLException erro){
            System.out.println(erro);
        }
    }

    public void exibir_L_E_N_I(int i){
        if (i == 0){
        //Atualiza A primeira tabela Mercado Local
        conexao.execute("select * from questionariomercadofeira_addmaterial where id_caminhoneiro="
                        +pega_codigo_ou_nome(1,cbMunicipio.getSelectedItem().toString())+" "
                        + "and mercado='Mercado Local'");
        preencher_jtableMercado(jtMaterialUtilizado);
        conexao.execute("select * from mercado_questionario");
        } else if (i == 1){

        conexao.execute("select * from mercado_questionario_addmercado where id_caminhoneiro="
                        +pega_codigo_ou_nome(1,cbMunicipio.getSelectedItem().toString())+" "
                        + "and mercado='Mercado Estadual'");
        preencher_jtableMercado(jbOrigemProduto);
        conexao.execute("select * from caminhoneiro_cadastro");
        }else if (i == 2){
        //Atualiza A terceira tabela Mercado Nacional
        conexao.execute("select * from caminhoneiro_addmercado where id_caminhoneiro="
                        +pega_codigo_ou_nome(1,cbNomeAtravessador.getSelectedItem().toString())+" "
                        + "and mercado='Mercado Nacional'");
        preencher_jtableMercado(jtMercadoNacional);
        conexao.execute("select * from caminhoneiro_cadastro");
        }else if (i == 3){
        //Atualiza A primeira tabela Mercado Internacional

    }

}


}
