/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * winProduto.java
 *
 * Created on 16/07/2010, 15:50:37
 */

package br.com.bean2;

import br.com.Persistencia.Conexao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Jhonathas
 */
public class frm_cad_caminhoneiro extends javax.swing.JFrame {

    /** Creates new form winProduto */
    int navega = 0; //variavel pra saber o  botão clicado;
    private Conexao conexao;
    int inicia_combo = 0;
    private boolean state = false;

    public frm_cad_caminhoneiro() {
        initComponents(); //Inicializa os componentes da tela
        conexao = new Conexao();
        conexao.conecta("mil_interface");
              
        //Insere nomes do município no cbMunicipio
        try {
            conexao.execute("select * FROM tab_local where pai='Pará'");
            while (conexao.resultSet.next()){
                cbMunicipio.addItem(conexao.resultSet.getString("nome"));
                //System.out.println(conexao.resultSet.getString("nome"));
            }
        }catch (SQLException ex) {
            Logger.getLogger(frm_cad_caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }

        conexao.execute("select * from caminhoneiro_cadastro");

        try {
            conexao.resultSet.first();
            mostra_dados_atravessador();


        }catch (SQLException ex) {
            Logger.getLogger(frm_cad_caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }

       /*
        Teste que mostra toda a tabela selecionada
        try {
            while (conexao.resultSet.next()){
            System.out.println(conexao.resultSet.getString("nome"));
            }
        }catch (SQLException ex) {
            Logger.getLogger(frm_cad_caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }
       */
        
        


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jpAtravessador = new javax.swing.JPanel();
        tfIdade = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbMunicipio = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Cadastrar = new javax.swing.JButton();
        botao_excluir = new javax.swing.JButton();
        botao_novo = new javax.swing.JButton();
        botao_primeiro = new javax.swing.JButton();
        botao_anterior = new javax.swing.JButton();
        botao_proximo = new javax.swing.JButton();
        botao_ultimo = new javax.swing.JButton();
        botao_alterar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfApelido = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tfNaturalidade = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        tfAtividadePrincipal = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tfAtividadeSecundaria = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tfComposicaoFamiliar = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        tfEscolaridade = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tfPqParou = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        cbLocalMoradia = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        cbQualidadeMoradia = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taAtividadeRendaFamilia = new javax.swing.JTextArea();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        tfEntrevistado = new javax.swing.JTextField();
        tfEsposa = new javax.swing.JTextField();
        tfFilhos = new javax.swing.JTextField();
        tfNetos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfTempoDiario = new javax.swing.JTextField();
        tfTempoAtividade = new javax.swing.JTextField();
        tfRendaMensal = new javax.swing.JTextField();
        tfQualColonia = new javax.swing.JTextField();
        tfDesdeQuando = new javax.swing.JTextField();
        chbPossuiColonia = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        tfTipoConstrucao = new javax.swing.JTextField();
        cbEstadoCivil = new javax.swing.JComboBox();
        rdSoTransporta = new javax.swing.JRadioButton();
        rdTransportaComercializa = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Questionário Atravessador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fechar_janela(evt);
            }
        });

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jpAtravessador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpAtravessador.setPreferredSize(new java.awt.Dimension(735, 538));

        jLabel22.setText("Idade.:");

        jLabel23.setText("Nome.:");

        jLabel24.setText("Município");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAction(evt);
            }
        });

        botao_excluir.setText("Excluir");
        botao_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirActionPerformed(evt);
            }
        });

        botao_novo.setText("Novo");
        botao_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_novoActionPerformed(evt);
            }
        });

        botao_primeiro.setText("<<");
        botao_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_primeiroActionPerformed(evt);
            }
        });

        botao_anterior.setText("<");
        botao_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_anteriorActionPerformed(evt);
            }
        });

        botao_proximo.setText(">");
        botao_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_proximoActionPerformed(evt);
            }
        });

        botao_ultimo.setText(">>");
        botao_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ultimoActionPerformed(evt);
            }
        });

        botao_alterar.setText("Alterar");
        botao_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(botao_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_excluir)
                        .addGap(7, 7, 7)
                        .addComponent(botao_alterar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(botao_primeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_proximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_ultimo)))
                .addContainerGap(480, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_primeiro)
                    .addComponent(botao_anterior)
                    .addComponent(botao_proximo)
                    .addComponent(botao_ultimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_novo)
                    .addComponent(Cadastrar)
                    .addComponent(botao_excluir)
                    .addComponent(botao_alterar))
                .addContainerGap())
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel25.setText("Dados Pessoais");

        jLabel26.setText("Apelido.:");

        jLabel27.setText("Naturalidade.:");

        jLabel28.setText("Sexo.:");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        jLabel29.setText("Atividade principal de renda.:");

        jLabel30.setText("Atividade secundária.:");

        jLabel31.setText("Estado civil.:");

        jLabel32.setText("Composição Familiar.:");

        jLabel33.setText("Escolaridade.:");

        jLabel34.setText("Porque Parou?");

        jLabel35.setText("Local de Moradia.:");

        cbLocalMoradia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sede Municipal", "Comunidade/Vila local", "Outro Município", "Capital" }));

        jLabel36.setText("Qualidade da Moradia.:");

        cbQualidadeMoradia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Péssima", "Ruim", "Regular", "Boa", "Ótima" }));

        jLabel37.setText("Quais atividades geram renda pra sua família?");

        taAtividadeRendaFamilia.setColumns(20);
        taAtividadeRendaFamilia.setRows(5);
        jScrollPane3.setViewportView(taAtividadeRendaFamilia);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel38.setText("Quem de sua família trabalha? E com qual atividade?:");

        jLabel39.setText("Entrevistado.:");

        jLabel40.setText("Esposa.:");

        jLabel41.setText("Filhos.:");

        jLabel42.setText("Netos.:");

        tfFilhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFilhosActionPerformed(evt);
            }
        });

        jLabel1.setText("Qual o tempo diário que passam trabalhando?");

        jLabel2.setText("Quando tempo está na atividade?");

        jLabel3.setText("Qual a renda por mês ou por viagem?");

        jLabel4.setText("Tem registro em alguma entidade de classe (colônia, associação, cooperativa)?");

        jLabel5.setText("Qual?");

        jLabel6.setText("Desde quando? (ex: 14/10/1988)");

        tfDesdeQuando.setText("01/01/2001");

        chbPossuiColonia.setText("Sim");
        chbPossuiColonia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbPossuiColoniaStateChanged(evt);
            }
        });
        chbPossuiColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbPossuiColoniaActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de construção.:");

        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado", "União Estável" }));

        buttonGroup3.add(rdSoTransporta);
        rdSoTransporta.setText("Só Transporta");

        buttonGroup3.add(rdTransportaComercializa);
        rdTransportaComercializa.setText("Trasnporta e comercializa");

        javax.swing.GroupLayout jpAtravessadorLayout = new javax.swing.GroupLayout(jpAtravessador);
        jpAtravessador.setLayout(jpAtravessadorLayout);
        jpAtravessadorLayout.setHorizontalGroup(
            jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAtravessadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdSoTransporta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdTransportaComercializa)
                        .addGap(230, 230, 230))
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addContainerGap(718, Short.MAX_VALUE))
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addContainerGap(512, Short.MAX_VALUE))
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEntrevistado, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEsposa, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFilhos, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNetos, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfEscolaridade, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPqParou, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfComposicaoFamiliar, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAtividadeSecundaria, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAtividadePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
                            .addGroup(jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTempoDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDesdeQuando, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTempoAtividade))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRendaMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(505, Short.MAX_VALUE))
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfQualColonia))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbPossuiColonia)
                        .addContainerGap(296, Short.MAX_VALUE))
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTipoConstrucao, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbLocalMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbQualidadeMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(303, 303, 303))))
        );
        jpAtravessadorLayout.setVerticalGroup(
            jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAtravessadorLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(rdSoTransporta)
                    .addComponent(rdTransportaComercializa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26)
                    .addComponent(tfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tfNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tfAtividadePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tfAtividadeSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(tfComposicaoFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tfEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(tfPqParou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cbLocalMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(cbQualidadeMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfTipoConstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(tfEntrevistado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel40)
                    .addComponent(tfEsposa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(tfFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(tfNetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfTempoDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(tfTempoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfRendaMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(chbPossuiColonia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfQualColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfDesdeQuando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane2.setViewportView(jpAtravessador);

        jTabbedPane1.addTab("Atravessador", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-848)/2, (screenSize.height-865)/2, 848, 865);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged

}//GEN-LAST:event_jTabbedPane1StateChanged

    private void chbPossuiColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbPossuiColoniaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chbPossuiColoniaActionPerformed

    private void tfFilhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFilhosActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tfFilhosActionPerformed

    private void botao_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ultimoActionPerformed
        try {
            conexao.resultSet.last();
            mostra_dados_atravessador();


        }catch (SQLException ex) {
            Logger.getLogger(frm_cad_caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_botao_ultimoActionPerformed

    private void botao_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_proximoActionPerformed
        try {
            
            conexao.resultSet.next();
            mostra_dados_atravessador();
            navega = 2;


        }catch (SQLException ex) {
            Logger.getLogger(frm_cad_caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_botao_proximoActionPerformed

    private void botao_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_anteriorActionPerformed
        try {
            conexao.resultSet.previous();
            mostra_dados_atravessador();
            navega = 1;

        }catch (SQLException ex) {
            Logger.getLogger(frm_cad_caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_botao_anteriorActionPerformed

    private void botao_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_primeiroActionPerformed
        try {
            conexao.resultSet.first();
            mostra_dados_atravessador();


        }catch (SQLException ex) {
            Logger.getLogger(frm_cad_caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_botao_primeiroActionPerformed

    private void botao_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_novoActionPerformed
        tfNome.setText("");
        tfApelido.setText("");
        tfNaturalidade.setText("");
        tfIdade.setText("0");
        tfAtividadePrincipal.setText("");
        tfAtividadeSecundaria.setText("");
        cbEstadoCivil.setSelectedIndex(0);
        tfComposicaoFamiliar.setText("");
        tfEscolaridade.setText("");
        tfPqParou.setText("");
        taAtividadeRendaFamilia.setText("");
        tfEntrevistado.setText("");
        tfEsposa.setText("");
        tfFilhos.setText("");
        tfNetos.setText("");
        tfTempoDiario.setText("");
        tfTempoAtividade.setText("");
        tfRendaMensal.setText("");
        tfQualColonia.setText("");
        tfDesdeQuando.setText("01/01/2001");
        tfTipoConstrucao.setText("");

        //System.out.println(conexao.resultSet.getString("local_moradia"));
        chbPossuiColonia.setSelected(false);
        cbMunicipio.setSelectedIndex(0);
        cbSexo.setSelectedIndex(0);
        cbLocalMoradia.setSelectedIndex(0);
        cbQualidadeMoradia.setSelectedIndex(0);

        buttonGroup3.clearSelection();
}//GEN-LAST:event_botao_novoActionPerformed

    private void botao_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirActionPerformed
        String sql;
        try {
            sql = "select * from caminhoneiro_cadastro Where id_caminhoneiro =" + conexao.resultSet.getString("id_caminhoneiro");
            conexao.execute(sql);
            conexao.resultSet.first();
            String nome = "Deletar o caminhoneiro : "+conexao.resultSet.getString("nome")+" ?";
            int opcao_escolhida = JOptionPane.showConfirmDialog(null,nome,"Exclusão ",JOptionPane.YES_NO_OPTION);
            if (opcao_escolhida == JOptionPane.YES_OPTION) {
                sql = "DELETE FROM caminhoneiro_cadastro Where id_caminhoneiro ="+conexao.resultSet.getString("id_caminhoneiro");
                if (conexao.salvar(sql)) {
                    JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso");
                    //atualiza o ResultSet
                    conexao.execute("select * from caminhoneiro_cadastro");
                    conexao.resultSet.first();
                    mostra_dados_atravessador();
                }
            } else{
                conexao.execute("select * from caminhoneiro_cadastro");
                conexao.resultSet.first();
                mostra_dados_atravessador();
            }

        } catch (SQLException ex) {
            System.out.println("Erro ao tentar excluir "+ex);
        }


    }//GEN-LAST:event_botao_excluirActionPerformed

    private void CadastrarAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAction
        // Para graver os dados no banco de dados
        int[] ckb = new int[3];
        if (chbPossuiColonia.isSelected()){
            ckb[0] = 1;
        }else
            ckb[0] = 0;
        //System.out.println(a);
        if (rdSoTransporta.isSelected()){
            ckb[1] = 1;
        }else
            ckb[1] = 0;

        if (rdTransportaComercializa.isSelected()){
            ckb[2] = 1;
        }else
            ckb[2] = 0;


        try {
            String sqlinsert = "insert into caminhoneiro_cadastro "
                    + "(id_local,nome,apelido,naturalidade,"
                    + "sexo,idade,atividade_principal,atividade_secundaria,"
                    + "estado_civil,composicao_familiar,escolaridade,pq_parou,"
                    + "local_moradia,qualidade_moradia,tipo_construcao,"
                    + "atividades_geram_renda,atividade_entrevistado,"
                    + "atividade_esposa,atividade_filhos,atividade_netos,"
                    + "tempo_diario_trab,tempo_na_atividade,"
                    + "renda_mensal_ou_viagem,possui_reg_colonia,qual_colonia,so_tranporta,transporta_e_comercializa,"
                    + "na_colonia_desde) values ('"+
                    cbMunicipio.getSelectedItem()+"','"+
                    tfNome.getText()+"','"+
                    tfApelido.getText()+"','"+
                    tfNaturalidade.getText()+"','"+
                    cbSexo.getSelectedItem()+"',"+
                    tfIdade.getText()+",'"+
                    tfAtividadePrincipal.getText()+"','"+
                    tfAtividadeSecundaria.getText()+"','"+
                    cbEstadoCivil.getSelectedItem()+"','"+
                    tfComposicaoFamiliar.getText()+"','"+
                    tfEscolaridade.getText()+"','"+
                    tfPqParou.getText()+"','"+
                    cbLocalMoradia.getSelectedItem()+"','"+
                    cbQualidadeMoradia.getSelectedItem()+"','"+
                    tfTipoConstrucao.getText()+"','"+
                    taAtividadeRendaFamilia.getText()+"','"+
                    tfEntrevistado.getText()+"','"+
                    tfEsposa.getText()+"','"+
                    tfFilhos.getText()+"','"+
                    tfNetos.getText()+"','"+
                    tfTempoDiario.getText()+"','"+
                    tfTempoAtividade.getText()+"','"+
                    tfRendaMensal.getText()+"',"+
                    ckb[0]+",'"+
                    tfQualColonia.getText()+"',"+
                    ckb[1]+","+
                    ckb[2]+",'"+
                    tfDesdeQuando.getText()+"')";

                    //System.out.println(sqlinsert);
            if (conexao.salvar(sqlinsert)) {
                //agora é hora de atualizar o resultset
                conexao.execute("select * from caminhoneiro_cadastro");
                conexao.resultSet.first(); //1º registro
                mostra_dados_atravessador();
            }


        }catch (SQLException erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_CadastrarAction

    private void fechar_janela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar_janela
        conexao.desconecta();
    }//GEN-LAST:event_fechar_janela

    private void chbPossuiColoniaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbPossuiColoniaStateChanged
        if (chbPossuiColonia.isSelected()){
            tfQualColonia.setEditable(true);
        }else{
            tfQualColonia.setEditable(false);
            tfQualColonia.setText("");
        }
    }//GEN-LAST:event_chbPossuiColoniaStateChanged

    private void botao_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarActionPerformed
        // Codigo para alterar os dados do BD
        int[] ckb = new int[3];
        if (chbPossuiColonia.isSelected()){
            ckb[0] = 1;
        }else
            ckb[0] = 0;
        //System.out.println(a);
        if (rdSoTransporta.isSelected()){
            ckb[1] = 1;
        }else
            ckb[1] = 0;

        if (rdTransportaComercializa.isSelected()){
            ckb[2] = 1;
        }else
            ckb[2] = 0;

        try{
            String sql ="UPDATE caminhoneiro_cadastro SET "+
                          "id_local = '"+cbMunicipio.getSelectedItem()+"',"+
                          "so_tranporta ='"+ckb[1]+"',"+
                          "transporta_e_comercializa ='"+ckb[2]+"',"+
                          "nome = '"+tfNome.getText()+"',"+
                          "apelido = '"+ tfApelido.getText() +"',"+
                          "naturalidade = '"+ tfNaturalidade.getText() +"',"+
                          "sexo = '"+ cbSexo.getSelectedItem() +"',"+
                          "idade = '"+ tfIdade.getText() +"',"+
                          "atividade_principal = '"+ tfAtividadePrincipal.getText() +"',"+
                          "atividade_secundaria = '"+ tfAtividadeSecundaria.getText() +"',"+
                          "estado_civil = '"+ cbEstadoCivil.getSelectedItem() +"',"+
                          "composicao_familiar = '"+ tfComposicaoFamiliar.getText() +"',"+
                          "escolaridade = '"+ tfEscolaridade.getText() +"',"+
                          "pq_parou = '"+ tfPqParou.getText() +"',"+
                          "local_moradia = '"+ cbLocalMoradia.getSelectedItem() +"',"+
                          "qualidade_moradia = '"+ cbQualidadeMoradia.getSelectedItem() +"',"+
                          "tipo_construcao = '"+ tfTipoConstrucao.getText() +"',"+
                          "atividades_geram_renda = '"+ taAtividadeRendaFamilia.getText() +"',"+
                          "atividade_entrevistado = '"+ tfEntrevistado.getText() +"',"+
                          "atividade_esposa = '"+ tfEsposa.getText() +"',"+
                          "atividade_filhos = '"+ tfFilhos.getText() +"',"+
                          "atividade_netos = '"+ tfNetos.getText() +"',"+
                          "tempo_diario_trab = '"+ tfTempoDiario.getText() +"',"+
                          "tempo_na_atividade = '"+ tfTempoAtividade.getText() +"',"+
                          "renda_mensal_ou_viagem = '"+ tfRendaMensal.getText() +"',"+
                          "possui_reg_colonia = '"+ ckb[0] +"',"+
                          "qual_colonia = '"+ tfQualColonia.getText() +"',"+
                          "na_colonia_desde = '"+ tfDesdeQuando.getText() +"' "+


                          "where id_caminhoneiro = "+conexao.resultSet.getString("id_caminhoneiro");

            System.out.println(sql);
            if (conexao.update(sql)){
            JOptionPane.showMessageDialog(null,"Alterado com sucesso");
            //Atualiza Resultset
            conexao.execute("select * from caminhoneiro_cadastro");
            conexao.resultSet.next();
            mostra_dados_atravessador();
            }
            

        }catch (Exception e){
            System.out.println(e + "Erro no botão alterar");
        }
    }//GEN-LAST:event_botao_alterarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frm_atravessador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton botao_alterar;
    private javax.swing.JButton botao_anterior;
    private javax.swing.JButton botao_excluir;
    private javax.swing.JButton botao_novo;
    private javax.swing.JButton botao_primeiro;
    private javax.swing.JButton botao_proximo;
    private javax.swing.JButton botao_ultimo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox cbEstadoCivil;
    private javax.swing.JComboBox cbLocalMoradia;
    private javax.swing.JComboBox cbMunicipio;
    private javax.swing.JComboBox cbQualidadeMoradia;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JCheckBox chbPossuiColonia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpAtravessador;
    private javax.swing.JRadioButton rdSoTransporta;
    private javax.swing.JRadioButton rdTransportaComercializa;
    private javax.swing.JTextArea taAtividadeRendaFamilia;
    private javax.swing.JTextField tfApelido;
    private javax.swing.JTextField tfAtividadePrincipal;
    private javax.swing.JTextField tfAtividadeSecundaria;
    private javax.swing.JTextField tfComposicaoFamiliar;
    private javax.swing.JTextField tfDesdeQuando;
    private javax.swing.JTextField tfEntrevistado;
    private javax.swing.JTextField tfEscolaridade;
    private javax.swing.JTextField tfEsposa;
    private javax.swing.JTextField tfFilhos;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JTextField tfNaturalidade;
    private javax.swing.JTextField tfNetos;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPqParou;
    private javax.swing.JTextField tfQualColonia;
    private javax.swing.JTextField tfRendaMensal;
    private javax.swing.JTextField tfTempoAtividade;
    private javax.swing.JTextField tfTempoDiario;
    private javax.swing.JTextField tfTipoConstrucao;
    // End of variables declaration//GEN-END:variables


    public void mostra_dados_atravessador(){
        try {

            tfNome.setText(conexao.resultSet.getString("nome"));
            tfApelido.setText(conexao.resultSet.getString("apelido"));
            tfNaturalidade.setText(conexao.resultSet.getString("naturalidade"));
            tfIdade.setText(conexao.resultSet.getString("idade"));
            tfAtividadePrincipal.setText(conexao.resultSet.getString("atividade_principal"));
            tfAtividadeSecundaria.setText(conexao.resultSet.getString("atividade_secundaria"));
            cbEstadoCivil.setSelectedItem(conexao.resultSet.getString("estado_civil"));
            tfComposicaoFamiliar.setText(conexao.resultSet.getString("composicao_familiar"));
            tfEscolaridade.setText(conexao.resultSet.getString("escolaridade"));
            tfPqParou.setText(conexao.resultSet.getString("pq_parou"));
            taAtividadeRendaFamilia.setText(conexao.resultSet.getString("atividades_geram_renda"));
            tfEntrevistado.setText(conexao.resultSet.getString("atividade_entrevistado"));
            tfEsposa.setText(conexao.resultSet.getString("atividade_esposa"));
            tfFilhos.setText(conexao.resultSet.getString("atividade_filhos"));
            tfNetos.setText(conexao.resultSet.getString("atividade_netos"));
            tfTempoDiario.setText(conexao.resultSet.getString("tempo_diario_trab"));
            tfTempoAtividade.setText(conexao.resultSet.getString("tempo_na_atividade"));
            tfRendaMensal.setText(conexao.resultSet.getString("renda_mensal_ou_viagem"));
            tfQualColonia.setText(conexao.resultSet.getString("qual_colonia"));
            tfDesdeQuando.setText(conexao.resultSet.getString("na_colonia_desde"));
            tfTipoConstrucao.setText(conexao.resultSet.getString("tipo_construcao"));

            //System.out.println(conexao.resultSet.getString("local_moradia"));
            
            if (conexao.resultSet.getString("possui_reg_colonia").equals("1"))
                   chbPossuiColonia.setSelected(true);
            else
                   chbPossuiColonia.setSelected(false);
            
            cbMunicipio.setSelectedItem(conexao.resultSet.getString("id_local"));
            cbSexo.setSelectedItem(conexao.resultSet.getString("sexo"));
            cbLocalMoradia.setSelectedItem(conexao.resultSet.getString("local_moradia"));
            cbQualidadeMoradia.setSelectedItem(conexao.resultSet.getString("qualidade_moradia"));

            if (conexao.resultSet.getString("so_tranporta").equals("1"))
                   rdSoTransporta.setSelected(true);
            else
                   rdSoTransporta.setSelected(false);

            if (conexao.resultSet.getString("transporta_e_comercializa").equals("1"))
                   rdTransportaComercializa.setSelected(true);
            else
                   rdTransportaComercializa.setSelected(false);


        }catch (SQLException ex) {
            if (navega == 1){
                JOptionPane.showMessageDialog(null,"Você já esta no primeiro registro");
                proximo();
            }
            else if (navega == 2){
                JOptionPane.showMessageDialog(null,"Você já esta no ultimo registro");
                anterior();
            }
            else
                JOptionPane.showMessageDialog(null,"Nenhum registro encontrado "+ ex );
            navega = 0;
            //Logger.getLogger(frm_cad_caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void anterior() {
         try {
                    conexao.resultSet.previous();
                } catch (SQLException ex1) {
                    Logger.getLogger(frm_cad_caminhoneiro.class.getName()).log(Level.SEVERE, null, ex1);
                }
    }

    private void proximo() {
        try {
                    conexao.resultSet.next();
                } catch (SQLException ex1) {
                    Logger.getLogger(frm_cad_caminhoneiro.class.getName()).log(Level.SEVERE, null, ex1);
                }
    }
    



}
