/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_questionario_atravessador.java
 *
 * Created on 26/07/2010, 09:44:24
 */
package br.com.bean;

import br.com.Persistencia.Conexao;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MPA
 */

public class frm_questionario_atravessador extends javax.swing.JFrame {

    /** Creates new form frm_questionario_atravessador */
    private Conexao conexao;
    int inicia_combo = 0;
    public frm_questionario_atravessador() {
        initComponents();
        conexao = new Conexao();
        conexao.conecta("mil_interface");

        //Insere nome no cbNomeAtravessador
                try {
                    cbNomeAtravessador.removeAllItems();
                    conexao.execute("select * from dat_questionario_atravessador");
                    while (conexao.resultSet.next()){
                        cbNomeAtravessador.addItem(conexao.resultSet.getString("nome"));
                        System.out.println(conexao.resultSet.getString("nome"));
                    }
                }catch (SQLException ex) {
                    System.out.println(ex);
                }

                //Preenche a tabela
                    try {
                        //cbMunicipio.removeAllItems();
                        conexao.execute("select * from dat_questionario_a_material");
                        preencher_jtable();
                        conexao.execute("select * from dat_questionario_atravessador");
                        conexao.resultSet.first();
                        while (conexao.resultSet.next()){
                            //cbMunicipio.addItem(conexao.resultSet.getString("nome"));
                            System.out.println(conexao.resultSet.getString("nome"));
                        }
                    }catch (SQLException ex) {
                        System.out.println(ex);
                    }
         conexao.execute("select * from dat_questionario_atravessador_pescado_sub");
        try {
            conexao.resultSet.first();
        } catch (SQLException ex) {
            Logger.getLogger(frm_questionario_atravessador.class.getName()).log(Level.SEVERE, null, ex);
        }
         mostra_dados();



    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpPescadoSubproduto = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        botao_cadastrar = new javax.swing.JButton();
        botao_excluir = new javax.swing.JButton();
        botao_primeiro = new javax.swing.JButton();
        botao_anterior = new javax.swing.JButton();
        botao_proximo = new javax.swing.JButton();
        botao_ultimo = new javax.swing.JButton();
        cbNomeAtravessador = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ckbSempreDosMesmos = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        ckbPeixeInteiro = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taOrigemProduto = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        taCriterioQualidadeProduto = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        taRecepcao = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        taComercializacao = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        taArmazenamento = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        botao_add_atravessador = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botao_material_atualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taExigenciaCompraPescado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fechar_janela(evt);
            }
        });

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        botao_cadastrar.setText("Cadastrar");
        botao_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastrarAction(evt);
            }
        });

        botao_excluir.setText("Excluir");
        botao_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirActionPerformed(evt);
            }
        });

        botao_primeiro.setText("<<");
        botao_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_primeiroActionPerformed(evt);
            }
        });

        botao_anterior.setText("<");
        botao_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_anteriorActionPerformed(evt);
            }
        });

        botao_proximo.setText(">");
        botao_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_proximoActionPerformed(evt);
            }
        });

        botao_ultimo.setText(">>");
        botao_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ultimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(botao_cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_excluir))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(botao_primeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_proximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_ultimo)))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_primeiro)
                    .addComponent(botao_anterior)
                    .addComponent(botao_proximo)
                    .addComponent(botao_ultimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_cadastrar)
                    .addComponent(botao_excluir))
                .addContainerGap())
        );

        cbNomeAtravessador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomeAtravessadorActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome.:");

        jLabel9.setText("Origem do produto? Pescado e subprodutos.");

        jLabel10.setText("Adquire o produto sempre dos mesmo pescadores?");

        ckbSempreDosMesmos.setText("SIM");

        jLabel11.setText("Só vente o peixe inteiro? Outras formas de comercialização?");

        ckbPeixeInteiro.setText("SIM");

        jLabel12.setText("Quais os critérios para definir a qualidade do produto?");

        jLabel13.setText("Como funciona a cadeia produtiva ('caminho') do pescado e subprodutos, desde o momento em que você");

        jLabel14.setText("recebe o produto nos portos de desembarque, passando pela conservação até a entrega dos produtos ao");

        jLabel15.setText("comprador final. Caracterizar em cada elo se utiliza (maquinário, gelo, frete, etc).");

        jLabel16.setText("a) Recepção (quantos fornedores e forma; comprado do pescador ou de outro atravessador)");

        taOrigemProduto.setColumns(20);
        taOrigemProduto.setRows(5);
        jScrollPane4.setViewportView(taOrigemProduto);

        taCriterioQualidadeProduto.setColumns(20);
        taCriterioQualidadeProduto.setRows(5);
        jScrollPane5.setViewportView(taCriterioQualidadeProduto);

        taRecepcao.setColumns(20);
        taRecepcao.setRows(5);
        jScrollPane6.setViewportView(taRecepcao);

        taComercializacao.setColumns(20);
        taComercializacao.setRows(5);
        jScrollPane7.setViewportView(taComercializacao);

        taArmazenamento.setColumns(20);
        taArmazenamento.setRows(5);
        jScrollPane8.setViewportView(taArmazenamento);

        jLabel17.setText("b) Armazenamento (algum beneficiamento?)");

        jLabel18.setText("c) Comercialização (vende direto pro consumidor ou outro atravessador?)");

        botao_add_atravessador.setText("Add");
        botao_add_atravessador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_add_atravessadorActionPerformed(evt);
            }
        });

        jLabel19.setText("Quais são os gastos com material utilizado na atividade (estimar frequência dos gastos - 1x por semana");

        jLabel20.setText("por viagem, por mês etc).");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Combustível", null, null, null, null, null},
                {"Lubrificante", null, null, null, null, null},
                {"Gelo", null, null, null, null, null},
                {"Rancho", null, null, null, null, null},
                {"Pagamento de pescador", null, null, null, null, null}
            },
            new String [] {
                "Material", "Tipo", "Quantidade", "Custo", "Outros", "Frequência"
            }
        ));
        jScrollPane9.setViewportView(jTable1);

        botao_material_atualizar.setText("Atualizar");
        botao_material_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_material_atualizarActionPerformed(evt);
            }
        });

        jLabel1.setText("Quais as suas exigências quanto à compra do pescado, e dos subprodutos?");

        taExigenciaCompraPescado.setColumns(20);
        taExigenciaCompraPescado.setRows(5);
        jScrollPane2.setViewportView(taExigenciaCompraPescado);

        javax.swing.GroupLayout jpPescadoSubprodutoLayout = new javax.swing.GroupLayout(jpPescadoSubproduto);
        jpPescadoSubproduto.setLayout(jpPescadoSubprodutoLayout);
        jpPescadoSubprodutoLayout.setHorizontalGroup(
            jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane5)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                                .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbNomeAtravessador, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel9)
                                .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ckbPeixeInteiro))
                                .addComponent(jLabel12)
                                .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ckbSempreDosMesmos))
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane8)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane9)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addComponent(botao_add_atravessador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao_material_atualizar)))
                        .addContainerGap(68, Short.MAX_VALUE))))
        );
        jpPescadoSubprodutoLayout.setVerticalGroup(
            jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbNomeAtravessador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ckbSempreDosMesmos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ckbPeixeInteiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_add_atravessador)
                    .addComponent(botao_material_atualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jpPescadoSubproduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-769)/2, (screenSize.height-790)/2, 769, 790);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_cadastrarAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarAction
        // TODO add your handling code here:
}//GEN-LAST:event_botao_cadastrarAction

    private void botao_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_botao_excluirActionPerformed

    private void botao_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_primeiroActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_botao_primeiroActionPerformed

    private void botao_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_anteriorActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_botao_anteriorActionPerformed

    private void botao_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_proximoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_botao_proximoActionPerformed

    private void botao_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ultimoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_botao_ultimoActionPerformed

    private void cbNomeAtravessadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomeAtravessadorActionPerformed
       
        //Pesquisa automática do Combo Box Nome do atravessador
        /*
        if (inicia_combo == 1){
         try {
            conexao.execute("select * from dat_questionario_atravessador_pescado_sub");
            conexao.resultSet.first();
            String igual = "n"; //inicia dizendo que não localizou
            while(igual == "n") //diz que enquanto não localizar é para ir executando
            {
                if (conexao.resultSet.getString("nome_atravessador").equals(cbNomeAtravessador.getSelectedItem())) {
                    igual = "s"; //incica que achou
                } else
                    conexao.resultSet.next();
            }
            //nas linhas abaixo, mostra_conteudo_tabela();
            // mostra_dados_atravessador_aba2();

        } catch (SQLException ex) {
            System.out.println(ex);
            }
        }inicia_combo = 1;
         */
    }//GEN-LAST:event_cbNomeAtravessadorActionPerformed

    private void botao_add_atravessadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_add_atravessadorActionPerformed
        new addMaterial(cbNomeAtravessador.getSelectedItem().toString()).setVisible(true);
}//GEN-LAST:event_botao_add_atravessadorActionPerformed

    private void botao_material_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_material_atualizarActionPerformed
        conexao.execute("select * from dat_questionario_a_material where nome_atravessador='"+cbNomeAtravessador.getSelectedItem()+"'");
        preencher_jtable();
        conexao.execute("select * from dat_questionario_atravessador");
}//GEN-LAST:event_botao_material_atualizarActionPerformed

    private void fechar_janela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar_janela
        conexao.desconecta();
    }//GEN-LAST:event_fechar_janela

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_questionario_atravessador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_add_atravessador;
    private javax.swing.JButton botao_anterior;
    private javax.swing.JButton botao_cadastrar;
    private javax.swing.JButton botao_excluir;
    private javax.swing.JButton botao_material_atualizar;
    private javax.swing.JButton botao_primeiro;
    private javax.swing.JButton botao_proximo;
    private javax.swing.JButton botao_ultimo;
    private javax.swing.JComboBox cbNomeAtravessador;
    private javax.swing.JCheckBox ckbPeixeInteiro;
    private javax.swing.JCheckBox ckbSempreDosMesmos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpPescadoSubproduto;
    private javax.swing.JTextArea taArmazenamento;
    private javax.swing.JTextArea taComercializacao;
    private javax.swing.JTextArea taCriterioQualidadeProduto;
    private javax.swing.JTextArea taExigenciaCompraPescado;
    private javax.swing.JTextArea taOrigemProduto;
    private javax.swing.JTextArea taRecepcao;
    // End of variables declaration//GEN-END:variables

        public void preencher_jtable(){
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);

        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);//limpa o JTable1;

        try{
            while (conexao.resultSet.next())
                modelo.addRow(new Object[]{conexao.resultSet.getString("nome"),
                                           conexao.resultSet.getString("tipo"),
                                           conexao.resultSet.getString("quantidade"),
                                           conexao.resultSet.getString("custo"),
                                           conexao.resultSet.getString("outros"),
                                           conexao.resultSet.getString("frequencia")});

            conexao.resultSet.first();
        }catch (SQLException erro){
            System.out.println(erro);
        }



    }

    public void mostra_dados(){
        try {
            //Exibir os text areas
            taOrigemProduto.setText(conexao.resultSet.getString("origem_produto"));
            taCriterioQualidadeProduto.setText(conexao.resultSet.getString("criterios_qualidade_produto"));
            taExigenciaCompraPescado.setText(conexao.resultSet.getString("exigencia_pescado_subprodutos"));
            taRecepcao.setText(conexao.resultSet.getString("como_func_recepcao"));
            taArmazenamento.setText(conexao.resultSet.getString("como_func_armazenamento"));
            taComercializacao.setText(conexao.resultSet.getString("como_funf_comercializacao"));

            //Selecionar os check boxes conforme o BD
            if (conexao.resultSet.getString("sempre_dos_mesmos_pesc").equals("1"))
                   ckbSempreDosMesmos.setSelected(true);
            else
                   ckbSempreDosMesmos.setSelected(false);

            if (conexao.resultSet.getString("peixe_inteiro").equals("1"))
                   ckbPeixeInteiro.setSelected(true);
            else
                   ckbPeixeInteiro.setSelected(false);



        } catch (Exception e) {
            System.out.println(e);
        }
    }


}
