/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * colonia_questionario.java
 *
 * Created on 05/08/2010, 12:52:55
 */

package br.com.bean.view.colonia;

import br.com.Persistencia.Conexao;
import java.sql.SQLException;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MPA
 */
public class colonia_questionario extends javax.swing.JFrame {
    private Conexao conexao;
    int inicia_combo = 0;
    String id_atravessador;
    String ItemDoCb;
    /** Creates new form colonia_questionario */
    public colonia_questionario() {
        initComponents();
        conexao = new Conexao();
        conexao.conecta("mil_interface");

                //Insere nome no cbNomeAtravessador
                try {
                    cbColonia.removeAllItems();
                    conexao.execute("select * from colonia_cadastro");

                    while (conexao.resultSet.next()){
                        cbColonia.addItem(conexao.resultSet.getString("id_colonia")+
                                                       " # "+ conexao.resultSet.getString("colonia"));
                    }
                }catch (SQLException ex) {
                    System.out.println(ex);
                }

        conexao.execute("select * from colonia_questionario");
        try {
            conexao.resultSet.first();
        } catch (SQLException ex) {
            System.out.println(ex+" linha 52");
        }
         mostra_dados();
         preencher_jtableAtividade(pega_codigo_ou_nome(1,cbColonia.getSelectedItem().toString()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbColonia = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf17Outro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf25MON = new javax.swing.JTextField();
        tf24NrEmbarc = new javax.swing.JTextField();
        tf26CAN = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf27CAM = new javax.swing.JTextField();
        tf28BPP = new javax.swing.JTextField();
        tf29BMP = new javax.swing.JTextField();
        tf30GEL = new javax.swing.JTextField();
        tf31BIN = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfFno = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfPagantes = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfInadiplentes = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        tf12NomePresidente = new javax.swing.JTextField();
        ckb12TemPresidente = new javax.swing.JCheckBox();
        jScrollPane7 = new javax.swing.JScrollPane();
        tp15descrever = new javax.swing.JTextPane();
        ckb16 = new javax.swing.JCheckBox();
        ckb36Defeso = new javax.swing.JCheckBox();
        ckb38Aposentadoria = new javax.swing.JCheckBox();
        ckb38SeguroDesemprego = new javax.swing.JCheckBox();
        ckb38BolsaFamilia = new javax.swing.JCheckBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtAtividade = new javax.swing.JTable();
        btAtualizarAtividade = new javax.swing.JButton();
        btExcluirAtividade = new javax.swing.JButton();
        btAddAtividade = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        botao_salvar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cb35 = new javax.swing.JComboBox();
        cb37 = new javax.swing.JComboBox();
        jScrollPane9 = new javax.swing.JScrollPane();
        tp18QuantaseQuais = new javax.swing.JTextPane();
        cb13 = new javax.swing.JComboBox();
        ckb17EstarQuite = new javax.swing.JCheckBox();
        ckb17TerTempo = new javax.swing.JCheckBox();
        ckb17Outro = new javax.swing.JCheckBox();
        ckb19Sim = new javax.swing.JCheckBox();
        jScrollPane12 = new javax.swing.JScrollPane();
        tp20TipoConflito = new javax.swing.JTextPane();
        ckb21EntreEles = new javax.swing.JCheckBox();
        ckb21ComLiderancas = new javax.swing.JCheckBox();
        ckb21ComIdosos = new javax.swing.JCheckBox();
        ckb21ComJustica = new javax.swing.JCheckBox();
        ckb21ComIBAMA = new javax.swing.JCheckBox();
        ckb21ComColonia = new javax.swing.JCheckBox();
        ckb21NaPolicia = new javax.swing.JCheckBox();
        ckb21Outro = new javax.swing.JCheckBox();
        tf21Outro = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        ckb22Sim = new javax.swing.JCheckBox();
        jLabel57 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tp22 = new javax.swing.JTextPane();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        tf23Homens = new javax.swing.JTextField();
        tf23Mulheres = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        cb39AchaSuficiente = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        ckb40Sim = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tp41Quem = new javax.swing.JTextPane();
        jLabel29 = new javax.swing.JLabel();
        ckb42Sim = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        cb43Qualidade = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        cb44Acompanha = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setText("Forma de Organização da Comunidade");

        jLabel2.setText("Comunidade:");

        cbColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbColoniaActionPerformed(evt);
            }
        });

        jLabel3.setText("12.Tem Presidente:");

        jLabel4.setText("12.1 Nome:");

        jLabel6.setText("13. A colônia realiza periodicamente reuniões com os pescadores?");

        jLabel7.setText("15. Descrever:");

        jLabel8.setText("16. A eleição do presidente da colônia é realizada em reunião com os pescadores?");

        jLabel9.setText("17. Qual o critério para votar?");

        tf17Outro.setEditable(false);

        jLabel10.setText("18. Quantas e quais comunidades fazem parte da colônia? (Descrever).");

        jLabel11.setText("19. Nos ultimos 3 anos, houve algum tipo de conflito entre pescadores no qual a colônia tenha se envolvido?");

        jLabel12.setText("20. Se sim, qual o tipo de conflito mais comum?");

        jLabel13.setText("21. Como as pessoas resolvem os conflitos?");

        tf25MON.setText("0");

        tf24NrEmbarc.setText("0");

        tf26CAN.setText("0");
        tf26CAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf26CANActionPerformed(evt);
            }
        });

        jLabel16.setText("25. MON");

        jLabel17.setText("26. CAN ");

        jLabel18.setText("28. BPP");

        jLabel20.setText("29. BMP");

        jLabel21.setText("30. GEL");

        jLabel22.setText("31. BIN");

        tf27CAM.setText("0");
        tf27CAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf27CAMActionPerformed(evt);
            }
        });

        tf28BPP.setText("0");

        tf29BMP.setText("0");

        tf30GEL.setText("0");

        tf31BIN.setText("0");

        jLabel23.setText("32.Estimativa do número de embarcações financiadas pelo FNO:");

        tfFno.setText("0");

        jLabel24.setText("33. Situação do financiamento: Pagantes");

        jLabel25.setText("34. Situação do Financiamento: Inadiplentes");

        jLabel26.setText("35. A colônia acha os financiamentos da administrção pública importante para a atividade de pesca ?");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel27.setText("Caracterização da Pesca");

        jLabel31.setText("36. Na comunidade existem algum tipo de defeso?");

        jLabel32.setText("37. Existindo defeso,ele é respeitado?");

        jLabel33.setText("38. Os pescadores recebem algum tipo de auxílio ?");

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel48.setText("Atividades");

        tf12NomePresidente.setEditable(false);

        ckb12TemPresidente.setText("Sim");
        ckb12TemPresidente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckb12TemPresidenteStateChanged(evt);
            }
        });
        ckb12TemPresidente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb12TemPresidenteItemStateChanged(evt);
            }
        });

        jScrollPane7.setViewportView(tp15descrever);

        ckb16.setText("Sim");
        ckb16.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckb16StateChanged(evt);
            }
        });

        ckb36Defeso.setText("Sim");

        ckb38Aposentadoria.setText("Aposentadoria");

        ckb38SeguroDesemprego.setText("Seguro desemprego/Seguro defeso");

        ckb38BolsaFamilia.setText("Bolsa família");

        jtAtividade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_atividade", "Nome da Atividade", "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"
            }
        ));
        jScrollPane8.setViewportView(jtAtividade);

        btAtualizarAtividade.setText("Atualizar");
        btAtualizarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarAtividadeActionPerformed(evt);
            }
        });

        btExcluirAtividade.setText("Excluir");
        btExcluirAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirAtividadeActionPerformed(evt);
            }
        });

        btAddAtividade.setText("Add");
        btAddAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddAtividadeActionPerformed(evt);
            }
        });

        botao_salvar.setText("Salvar");
        botao_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_salvarActionPerformed(evt);
            }
        });

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cb35.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Um pouco", "Mais ou Menos", "Bastante" }));

        cb37.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Um pouco", "Mais ou Menos", "Bastante" }));

        jScrollPane9.setViewportView(tp18QuantaseQuais);

        cb13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não realiza", "Realiza mensalmente", "Realiza trimestralmente", "Realiza", "Realiza ocasionalmente/raramente", "Outros" }));

        ckb17EstarQuite.setText("Estar quite com a contribuição junto à colônia?");

        ckb17TerTempo.setText("Ter um tempo mínimo como associado?");

        ckb17Outro.setText("Outro");
        ckb17Outro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb17OutroItemStateChanged(evt);
            }
        });

        ckb19Sim.setText("Sim");
        ckb19Sim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb19SimItemStateChanged(evt);
            }
        });

        tp20TipoConflito.setEditable(false);
        jScrollPane12.setViewportView(tp20TipoConflito);

        ckb21EntreEles.setText("Entre eles");

        ckb21ComLiderancas.setText("Com lideranças da comunidade");

        ckb21ComIdosos.setText("Com os idosos/Mais velhos da comunidade");

        ckb21ComJustica.setText("Com justiça");

        ckb21ComIBAMA.setText("Com IBAMA");

        ckb21ComColonia.setText("Com a colônia de pescadores");
        ckb21ComColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb21ComColoniaActionPerformed(evt);
            }
        });

        ckb21NaPolicia.setText("Na Polícia");

        ckb21Outro.setText("Outro");
        ckb21Outro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb21OutroItemStateChanged(evt);
            }
        });

        tf21Outro.setEditable(false);

        jLabel56.setText("22. Existe associações, cooperativas ou outras formas de organização social?");

        ckb22Sim.setText("Sim");
        ckb22Sim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb22SimItemStateChanged(evt);
            }
        });

        jLabel57.setText("22.1. Especifique:");

        tp22.setEditable(false);
        jScrollPane2.setViewportView(tp22);

        jLabel58.setText("23. Nº de pescadores associados: Homens:");

        jLabel59.setText("Mulheres:");

        jLabel60.setText("24. Estimativa do total de embarcações dos associados (somatória de todos)");

        jLabel14.setText("27. CAM");

        jLabel15.setText("39. Você acha suficiente o valor do seguro desemprego/seguro defeso recebido do governo durante o defeso?");

        cb39AchaSuficiente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Mais ou Menos", "Suficiente" }));

        jLabel19.setText("40. Existe algum monitoramento para estimular a produção do município?");

        ckb40Sim.setText("Sim");
        ckb40Sim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb40SimItemStateChanged(evt);
            }
        });

        jLabel28.setText("41. Se sim, quem o faz?");

        tp41Quem.setEditable(false);
        jScrollPane3.setViewportView(tp41Quem);

        jLabel29.setText("42. O Municipio tem um local especifico para o desembarque do pescado?");

        ckb42Sim.setText("Sim");

        jLabel30.setText("43. Havendo local, este é de qualidade?");

        cb43Qualidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Parcialmente", "Sim" }));

        jLabel34.setText("44. A colônia acompanha o período de defeso junto aos seus associados?");

        cb44Acompanha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Parcialmente", "Sim" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckb12TemPresidente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf12NomePresidente))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cb13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ckb16))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(ckb17EstarQuite)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckb17TerTempo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(ckb17Outro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf17Outro, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckb21EntreEles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb21ComLiderancas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb21ComIdosos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckb21ComJustica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb21ComIBAMA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb21ComColonia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb21NaPolicia))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckb21Outro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf21Outro, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel56)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb22Sim))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel27)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf23Homens, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf23Mulheres, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb19Sim))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfInadiplentes, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfPagantes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf30GEL))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf25MON, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf26CAN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf31BIN)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf27CAM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf28BPP))
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf29BMP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfFno, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(11, 11, 11)
                                .addComponent(cb35, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb36Defeso))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel33)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel48)
                                .addGap(145, 145, 145))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btAddAtividade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btExcluirAtividade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAtualizarAtividade))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(botao_salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ckb38Aposentadoria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckb38SeguroDesemprego)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckb38BolsaFamilia))
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel28)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckb40Sim))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel30)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cb43Qualidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel34))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ckb42Sim)
                                            .addComponent(cb44Acompanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb39AchaSuficiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf24NrEmbarc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ckb12TemPresidente)
                            .addComponent(jLabel4)
                            .addComponent(tf12NomePresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb16)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb17EstarQuite)
                    .addComponent(ckb17TerTempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf17Outro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckb17Outro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ckb19Sim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb21EntreEles)
                    .addComponent(ckb21ComLiderancas)
                    .addComponent(ckb21ComIdosos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb21ComJustica)
                    .addComponent(ckb21ComIBAMA)
                    .addComponent(ckb21ComColonia)
                    .addComponent(ckb21NaPolicia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb21Outro)
                    .addComponent(tf21Outro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(ckb22Sim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(tf23Homens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59)
                    .addComponent(tf23Mulheres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(tf24NrEmbarc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf25MON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tf26CAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tf27CAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(tf28BPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(tf29BMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf30GEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(tf31BIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfFno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(tfPagantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfInadiplentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cb35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(ckb36Defeso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(cb37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb38Aposentadoria)
                    .addComponent(ckb38SeguroDesemprego)
                    .addComponent(ckb38BolsaFamilia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cb39AchaSuficiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ckb40Sim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(ckb42Sim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(cb43Qualidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(cb44Acompanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluirAtividade)
                    .addComponent(btAddAtividade)
                    .addComponent(btAtualizarAtividade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_salvar)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf27CAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf27CAMActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf27CAMActionPerformed

    private void tf26CANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf26CANActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf26CANActionPerformed

    private void ckb12TemPresidenteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckb12TemPresidenteStateChanged
        
    }//GEN-LAST:event_ckb12TemPresidenteStateChanged

    private void ckb16StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckb16StateChanged
        
    }//GEN-LAST:event_ckb16StateChanged

    private void botao_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_salvarActionPerformed
        try {
            String sqlinsert = "insert into colonia_questionario "
                    + "(id_colonia,12tem_presidente,12nome_presidente,"
                    + "13realiza_reunioes,15descricao_reunioes,16eleicao_e_em_reuniao,"
                    + "17criterio_estar_quite,17criterio_ter_tempo,17criterio_outro,"
                    + "17criterio_outro_qual,18quantas_fazem_part,19houve_conflito,"
                    + "20tipo_conflito,21entre_eles,21com_lideranca,21com_idosos,"
                    + "21com_justica,21com_ibama,21com_colonia,21outro,"
                    + "21outro_qual,22existe_outras,22especificar,"
                    + "23nr_pesc_h,23nr_pesc_m,24total,25mon,26can,27cam,28bpp,"
                    + "29bmp,30gel,31bin,32fno,33sit_pagante,34sit_indadimplentes,"
                    + "35opiniao_financiamento,36defeso,37defeso_respeitado,"
                    + "38aposentadoria,38seguro,38bolsa_familia,39e_suficiente,"
                    + "40existe_monitoramento,41quem_faz,42tem_local,43qualidade_local,"              
                    + "44acompanha) values ("+

                    pega_codigo_ou_nome(1,cbColonia.getSelectedItem().toString())+","+
                    tachecado(ckb12TemPresidente) +",'"+ //tem presidente?
                    tf12NomePresidente.getText()+"','"+

                    cb13.getSelectedItem()+"','"+//"13realiza_reunioes
                    tp15descrever.getText()+"',"+//,15descricao_reunioes
                    tachecado(ckb16)+","+//,16eleicao_e_em_reuniao,"
                    
                    tachecado(ckb17EstarQuite)+","+//"17criterio_estar_quite
                    tachecado(ckb17TerTempo)+","+//,17criterio_ter_tempo
                    tachecado(ckb17Outro)+",'"+//,17criterio_outro,"
                    
                    tf17Outro.getText()+"','"+//"17criterio_outro_qual
                    tp18QuantaseQuais.getText()+"',"+//,18quantas_fazem_part
                    tachecado(ckb19Sim)+",'"+//,19houve_conflito,"
                    
                    tp20TipoConflito.getText()+"',"+//"20tipo_conflito
                    tachecado(ckb21EntreEles)+","+//,21entre_eles
                    tachecado(ckb21ComLiderancas)+","+//,21com_lideranca
                    tachecado(ckb21ComIdosos)+","+//,21com_idosos,"
                    
                    tachecado(ckb21ComJustica)+","+//"21com_justica
                    tachecado(ckb21ComIBAMA)+","+//,21com_ibama
                    tachecado(ckb21ComColonia)+","+//,21com_colonia
                    tachecado(ckb21Outro)+",'"+//,21outro,"
                    
                    tf21Outro.getText()+"',"+//"21outro_qual
                    tachecado(ckb22Sim)+",'"+//,22existe_outras
                    tp22.getText()+"',"+//,22especificar,"
                    
                    tf23Homens.getText()+","+//"23nr_pesc_h
                    tf23Mulheres.getText()+","+//,23nr_pesc_m
                    tf24NrEmbarc.getText()+","+//,24total
                    tf25MON.getText()+","+//,25mon
                    tf26CAN.getText()+","+//,26can
                    tf27CAM.getText()+","+//,27cam
                    tf28BPP.getText()+","+//,28bpp,"
                    
                    tf29BMP.getText()+","+//"29bmp
                    tf30GEL.getText()+","+//,30gel
                    tf31BIN.getText()+","+//,31bin
                    tfFno.getText()+",'"+//,32fno
                    tfPagantes.getText()+"','"+//,33sit_pagante
                    tfInadiplentes.getText()+"','"+//,34sit_indadimplentes,"
                    
                    cb35.getSelectedItem()+"',"+//"35opiniao_financiamento
                    tachecado(ckb36Defeso)+",'"+//,36defeso
                    cb37.getSelectedItem()+"',"+//,37defeso_respeitado,"
                    
                    tachecado(ckb38Aposentadoria)+","+//"38aposentadoria
                    tachecado(ckb38SeguroDesemprego)+","+//,38seguro
                    tachecado(ckb38BolsaFamilia)+",'"+//,38bolsa_familia
                    cb39AchaSuficiente.getSelectedItem()+"',"+//,39e_suficiente,"
                    
                    tachecado(ckb40Sim)+",'"+//"40existe_monitoramento
                    tp41Quem.getText()+"',"+//,41quem_faz
                    tachecado(ckb42Sim)+",'"+//,42tem_local
                    cb43Qualidade.getSelectedItem()+"','"+//,43qualidade_local,"
                         
                    cb44Acompanha.getSelectedItem()+"')";//46quem_faz

                    System.out.println(sqlinsert);
                    
            if (conexao.salvar(sqlinsert)){
            //agora é hora de atualizar o resultset
            JOptionPane.showMessageDialog(null,"Cadastrado com sucesso");
            conexao.execute("select * from colonia_questionario");
            conexao.resultSet.first(); //1º registro
            mostra_dados();
            cbColonia.setSelectedIndex(0);
            }

        }catch (SQLException erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_botao_salvarActionPerformed

    private void cbColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbColoniaActionPerformed

        //Pesquisa automática do Combo Box Nome do atravessador

        if (inicia_combo == 1){
         try {
            conexao.execute("select * from colonia_questionario");
            conexao.resultSet.first();
            String igual = "n"; //inicia dizendo que não localizou
            while(igual == "n") //diz que enquanto não localizar é para ir executando
            {
                String id = pega_codigo_ou_nome(1,cbColonia.getSelectedItem().toString());
                if (conexao.resultSet.getString("id_colonia").equals(id)) {
                    igual = "s"; //incica que achou
                } else
                    conexao.resultSet.next();
            }
            //nas linhas abaixo, mostra_conteudo_tabela();
             limpar_dados();
             mostra_dados();
             
             preencher_jtableAtividade(pega_codigo_ou_nome(1,cbColonia.getSelectedItem().toString()));


        } catch (SQLException ex) {
            limpar_dados();
            
            preencher_jtableAtividade(pega_codigo_ou_nome(1,cbColonia.getSelectedItem().toString()));
            System.out.println(ex+" Erro na troca do combobox");
            }
        }inicia_combo = 1;
    }//GEN-LAST:event_cbColoniaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try{
            String sql ="UPDATE colonia_questionario SET "+
                          "12tem_presidente = '"+tachecado(ckb12TemPresidente)+"',"+
                          
                          "12nome_presidente = '"+tf12NomePresidente.getText()+"',"+
                            

                          "13realiza_reunioes ='"+cb13.getSelectedItem()+"',"+//"
                    "15descricao_reunioes ='"+tp15descrever.getText()+"',"+//,
                    "16eleicao_e_em_reuniao ='"+tachecado(ckb16)+"',"+//,,"
                    
                    "17criterio_estar_quite ='"+tachecado(ckb17EstarQuite)+"',"+//"17criterio_estar_quite
                    "17criterio_ter_tempo ='"+tachecado(ckb17TerTempo)+"',"+//,
                    "17criterio_outro ='"+tachecado(ckb17Outro)+"',"+//,,"
                    
                    "17criterio_outro_qual ='"+tf17Outro.getText()+"',"+//"
                    "18quantas_fazem_part ='"+tp18QuantaseQuais.getText()+"',"+//,
                    "19houve_conflito ='"+tachecado(ckb19Sim)+"',"+//,,"
                    
                    "20tipo_conflito ='"+tp20TipoConflito.getText()+"',"+//"
                    "21entre_eles ='"+tachecado(ckb21EntreEles)+"',"+//,
                    "21com_lideranca ='"+tachecado(ckb21ComLiderancas)+"',"+//,
                    "21com_idosos ='"+tachecado(ckb21ComIdosos)+"',"+//,,"
                    
                    "21com_justica ='"+tachecado(ckb21ComJustica)+"',"+//"
                    "21com_ibama ='"+tachecado(ckb21ComIBAMA)+"',"+//,
                    "21com_colonia ='"+tachecado(ckb21ComColonia)+"',"+//,
                    "21outro ='"+tachecado(ckb21Outro)+"',"+//,,"
                    
                    "21outro_qual ='"+tf21Outro.getText()+"',"+//"
                    "22existe_outras ='"+tachecado(ckb22Sim)+"',"+//,
                    "22especificar ='"+tp22.getText()+"',"+//,,"
                    
                    "23nr_pesc_h ='"+tf23Homens.getText()+"',"+//"
                    "23nr_pesc_m ='"+tf23Mulheres.getText()+"',"+//,
                    "24total ='"+tf24NrEmbarc.getText()+"',"+//,
                    "25mon ='"+tf25MON.getText()+"',"+//,
                    "26can ='"+tf26CAN.getText()+"',"+//,
                    "27cam ='"+tf27CAM.getText()+"',"+//,
                    "28bpp ='"+tf28BPP.getText()+"',"+//,,"
                    
                    "29bmp ='"+tf29BMP.getText()+"',"+//"
                    "30gel ='"+tf30GEL.getText()+"',"+//,
                    "31bin ='"+tf31BIN.getText()+"',"+//,
                    "32fno ='"+tfFno.getText()+"',"+//,
                    "33sit_pagante ='"+tfPagantes.getText()+"',"+//,
                    "34sit_indadimplentes ='"+tfInadiplentes.getText()+"',"+//,,"
                    
                    "35opiniao_financiamento ='"+cb35.getSelectedItem()+"',"+//"
                    "36defeso ='"+tachecado(ckb36Defeso)+"',"+//,
                    "37defeso_respeitado ='"+cb37.getSelectedItem()+"',"+//,,"
                    
                    "38aposentadoria ='"+tachecado(ckb38Aposentadoria)+"',"+//"
                    "38seguro ='"+tachecado(ckb38SeguroDesemprego)+"',"+//,
                    "38bolsa_familia ='"+tachecado(ckb38BolsaFamilia)+"',"+//,
                    "39e_suficiente ='"+cb39AchaSuficiente.getSelectedItem()+"',"+//,,"
                    
                    "40existe_monitoramento ='"+tachecado(ckb40Sim)+"',"+//"
                    "41quem_faz ='"+tp41Quem.getText()+"',"+//,
                    "42tem_local ='"+tachecado(ckb42Sim)+"',"+//,
                    "43qualidade_local ='"+cb43Qualidade.getSelectedItem()+"',"+//,,"
                         
                    "44acompanha ='"+cb44Acompanha.getSelectedItem()+"' "+//
                          

                    "where id_colonia = "+pega_codigo_ou_nome(1,cbColonia.getSelectedItem().toString());

            System.out.println(sql);
            if (conexao.update(sql)){
            JOptionPane.showMessageDialog(null,"Alterado com sucesso");
            //Atualiza Resultset
            conexao.execute("select * from colonia_questionario");
            conexao.resultSet.next();
            mostra_dados();
            cbColonia.setSelectedIndex(0);
            }


        }catch (Exception e){
            System.out.println(e + "Erro no botão alterar");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btAtualizarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarAtividadeActionPerformed
        preencher_jtableAtividade(pega_codigo_ou_nome(1,cbColonia.getSelectedItem().toString()));
    }//GEN-LAST:event_btAtualizarAtividadeActionPerformed

    private void btAddAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddAtividadeActionPerformed
        new addAtividades(pega_codigo_ou_nome(1,cbColonia.getSelectedItem().toString())).setVisible(true);
    }//GEN-LAST:event_btAddAtividadeActionPerformed

    private void btExcluirAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirAtividadeActionPerformed
        // TODO add your handling code here:
        System.out.println(jtAtividade.getValueAt(jtAtividade.getSelectedRow(),0));
        //.removeRow(jTable1.getSelectedRow());
                String sql;

            sql = "delete from colonia_atividade Where id_atividade =" + jtAtividade.getValueAt(jtAtividade.getSelectedRow(),0);

                if (conexao.salvar(sql)) {
                    System.out.println("Exclusão realizada com sucesso");
                    //exibe
                    preencher_jtableAtividade(pega_codigo_ou_nome(1,cbColonia.getSelectedItem().toString()));

                }else{
                JOptionPane.showMessageDialog(null,"Erro na exclusão");


                }
    }//GEN-LAST:event_btExcluirAtividadeActionPerformed

    private void ckb12TemPresidenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb12TemPresidenteItemStateChanged
        if (ckb12TemPresidente.isSelected()){
            tf12NomePresidente.setEditable(true);
        }else{
            tf12NomePresidente.setEditable(false);
            tf12NomePresidente.setText("");
        }
    }//GEN-LAST:event_ckb12TemPresidenteItemStateChanged

    private void ckb17OutroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb17OutroItemStateChanged
        if (ckb17Outro.isSelected())
            tf17Outro.setEditable(true);
        else{
            tf17Outro.setEditable(false);
            tf17Outro.setText("");
        }
    }//GEN-LAST:event_ckb17OutroItemStateChanged

    private void ckb21ComColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb21ComColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckb21ComColoniaActionPerformed

    private void ckb22SimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb22SimItemStateChanged
        if (ckb22Sim.isSelected())
            tp22.setEditable(true);
        else{
            tp22.setEditable(false);
            tp22.setText("");
        }
    }//GEN-LAST:event_ckb22SimItemStateChanged

    private void ckb40SimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb40SimItemStateChanged
        if (ckb40Sim.isSelected())
            tp41Quem.setEditable(true);
        else{
            tp41Quem.setEditable(false);
            tp41Quem.setText("");
        }
    }//GEN-LAST:event_ckb40SimItemStateChanged

    private void ckb19SimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb19SimItemStateChanged
        if (ckb19Sim.isSelected())
            tp20TipoConflito.setEditable(true);
        else{
            tp20TipoConflito.setEditable(false);
            tp20TipoConflito.setText("");
        }
    }//GEN-LAST:event_ckb19SimItemStateChanged

    private void ckb21OutroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb21OutroItemStateChanged
        if (ckb21Outro.isSelected())
            tf21Outro.setEditable(true);
        else{
            tf21Outro.setEditable(false);
            tf21Outro.setText("");
        }
    }//GEN-LAST:event_ckb21OutroItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new colonia_questionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_salvar;
    private javax.swing.JButton btAddAtividade;
    private javax.swing.JButton btAtualizarAtividade;
    private javax.swing.JButton btExcluirAtividade;
    private javax.swing.JComboBox cb13;
    private javax.swing.JComboBox cb35;
    private javax.swing.JComboBox cb37;
    private javax.swing.JComboBox cb39AchaSuficiente;
    private javax.swing.JComboBox cb43Qualidade;
    private javax.swing.JComboBox cb44Acompanha;
    private javax.swing.JComboBox cbColonia;
    private javax.swing.JCheckBox ckb12TemPresidente;
    private javax.swing.JCheckBox ckb16;
    private javax.swing.JCheckBox ckb17EstarQuite;
    private javax.swing.JCheckBox ckb17Outro;
    private javax.swing.JCheckBox ckb17TerTempo;
    private javax.swing.JCheckBox ckb19Sim;
    private javax.swing.JCheckBox ckb21ComColonia;
    private javax.swing.JCheckBox ckb21ComIBAMA;
    private javax.swing.JCheckBox ckb21ComIdosos;
    private javax.swing.JCheckBox ckb21ComJustica;
    private javax.swing.JCheckBox ckb21ComLiderancas;
    private javax.swing.JCheckBox ckb21EntreEles;
    private javax.swing.JCheckBox ckb21NaPolicia;
    private javax.swing.JCheckBox ckb21Outro;
    private javax.swing.JCheckBox ckb22Sim;
    private javax.swing.JCheckBox ckb36Defeso;
    private javax.swing.JCheckBox ckb38Aposentadoria;
    private javax.swing.JCheckBox ckb38BolsaFamilia;
    private javax.swing.JCheckBox ckb38SeguroDesemprego;
    private javax.swing.JCheckBox ckb40Sim;
    private javax.swing.JCheckBox ckb42Sim;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jtAtividade;
    private javax.swing.JTextField tf12NomePresidente;
    private javax.swing.JTextField tf17Outro;
    private javax.swing.JTextField tf21Outro;
    private javax.swing.JTextField tf23Homens;
    private javax.swing.JTextField tf23Mulheres;
    private javax.swing.JTextField tf24NrEmbarc;
    private javax.swing.JTextField tf25MON;
    private javax.swing.JTextField tf26CAN;
    private javax.swing.JTextField tf27CAM;
    private javax.swing.JTextField tf28BPP;
    private javax.swing.JTextField tf29BMP;
    private javax.swing.JTextField tf30GEL;
    private javax.swing.JTextField tf31BIN;
    private javax.swing.JTextField tfFno;
    private javax.swing.JTextField tfInadiplentes;
    private javax.swing.JTextField tfPagantes;
    private javax.swing.JTextPane tp15descrever;
    private javax.swing.JTextPane tp18QuantaseQuais;
    private javax.swing.JTextPane tp20TipoConflito;
    private javax.swing.JTextPane tp22;
    private javax.swing.JTextPane tp41Quem;
    // End of variables declaration//GEN-END:variables

            public String pega_codigo_ou_nome(int n,String teste) { //Se entrar com 1 pega o Código, se não pega o Nome
              //pegar a Id do atravessador

              //aqui ele pega a quantidade de carcteres que tem uma determinada variável
              //e armazena numa INT para usá-la de contador
              int contador = teste.length();

              //cria um for( para fazer uma varredura letra por letra até encontrar
              for(int i = 0;i<contador;i++){
                 //usamos substring pra pegar um caractere, passando como parâmetro,
                 //o primeiro caractere a ser pega, até a ultima.
                //fiz um if para verificar se o caractere é igual a "#"
                if (teste.substring(i,i+1).equals("#")){
                   int posicao = i+1;
                    System.out.println("Está na posição " + posicao);
                    if (n == 1){
                        return teste.substring(0,posicao-2);
                    }
                    else
                        return teste.substring(posicao+1,teste.length());
                }

              }
              return "nada";
        }

    private void mostra_dados() {
        try {
            tf12NomePresidente.setText(conexao.resultSet.getString("12nome_presidente"));

            if (conexao.resultSet.getString("12tem_presidente").equals("1"))
                   ckb12TemPresidente.setSelected(true);
            else
                   ckb12TemPresidente.setSelected(false);

            cb13.setSelectedItem(conexao.resultSet.getString("13realiza_reunioes"));
            tp15descrever.setText(conexao.resultSet.getString("15descricao_reunioes"));

            if (conexao.resultSet.getString("16eleicao_e_em_reuniao").equals("1"))
                   ckb16.setSelected(true);
            else
                   ckb16.setSelected(false);

            if (conexao.resultSet.getString("17criterio_estar_quite").equals("1"))
                   ckb17EstarQuite.setSelected(true);
            else
                   ckb17EstarQuite.setSelected(false);

            if (conexao.resultSet.getString("17criterio_ter_tempo").equals("1"))
                   ckb17TerTempo.setSelected(true);
            else
                   ckb17TerTempo.setSelected(false);

            if (conexao.resultSet.getString("17criterio_outro").equals("1"))
                   ckb17Outro.setSelected(true);
            else
                   ckb17Outro.setSelected(false);

            tf17Outro.setText(conexao.resultSet.getString("17criterio_outro_qual"));
            tp18QuantaseQuais.setText(conexao.resultSet.getString("18quantas_fazem_part"));
            
            if (conexao.resultSet.getString("19houve_conflito").equals("1"))
                   ckb19Sim.setSelected(true);
            else
                   ckb19Sim.setSelected(false);
            
            tp20TipoConflito.setText(conexao.resultSet.getString("20tipo_conflito"));
            
            if (conexao.resultSet.getString("21entre_eles").equals("1"))
                   ckb21EntreEles.setSelected(true);
            else
                   ckb21EntreEles.setSelected(false);
            
            if (conexao.resultSet.getString("21com_lideranca").equals("1"))
                   ckb21ComLiderancas.setSelected(true);
            else
                   ckb21ComLiderancas.setSelected(false);
            
            if (conexao.resultSet.getString("21com_idosos").equals("1"))
                   ckb21ComIdosos.setSelected(true);
            else
                   ckb21ComIdosos.setSelected(false);
            
            if (conexao.resultSet.getString("21com_justica").equals("1"))
                   ckb21ComJustica.setSelected(true);
            else
                   ckb21ComJustica.setSelected(false);
            
            if (conexao.resultSet.getString("21com_ibama").equals("1"))
                   ckb21ComIBAMA.setSelected(true);
            else
                   ckb21ComIBAMA.setSelected(false);
            
            if (conexao.resultSet.getString("21com_colonia").equals("1"))
                   ckb21ComColonia.setSelected(true);
            else
                   ckb21ComColonia.setSelected(false);
            
            if (conexao.resultSet.getString("21outro").equals("1"))
                   ckb21Outro.setSelected(false);
            else
                   ckb21Outro.setSelected(false);
            
            tf21Outro.setText(conexao.resultSet.getString("21outro_qual"));
            
            if (conexao.resultSet.getString("22existe_outras").equals("1"))
                   ckb22Sim.setSelected(true);
            else
                   ckb22Sim.setSelected(false);
                    
            tp22.setText(conexao.resultSet.getString("22especificar"));

            tf23Homens.setText(conexao.resultSet.getString("23nr_pesc_h"));
            tf23Mulheres.setText(conexao.resultSet.getString("23nr_pesc_m"));
            tf24NrEmbarc.setText(conexao.resultSet.getString("24total"));
            tf25MON.setText(conexao.resultSet.getString("25mon"));
            tf26CAN.setText(conexao.resultSet.getString("26can"));
            tf27CAM.setText(conexao.resultSet.getString("27cam"));
            tf28BPP.setText(conexao.resultSet.getString("28bpp"));

            tf29BMP.setText(conexao.resultSet.getString("29bmp"));
            tf30GEL.setText(conexao.resultSet.getString("30gel"));
            tf31BIN.setText(conexao.resultSet.getString("31bin"));
            tfFno.setText(conexao.resultSet.getString("32fno"));
            tfPagantes.setText(conexao.resultSet.getString("33sit_pagante"));
            tfInadiplentes.setText(conexao.resultSet.getString("34sit_indadimplentes"));

            cb35.setSelectedItem(conexao.resultSet.getString("35opiniao_financiamento"));
            
            if (conexao.resultSet.getString("36defeso").equals("1"))
                   ckb36Defeso.setSelected(true);
            else
                   ckb36Defeso.setSelected(false);
            
            cb37.setSelectedItem(conexao.resultSet.getString("37defeso_respeitado"));

            if (conexao.resultSet.getString("38aposentadoria").equals("1"))
                   ckb38Aposentadoria.setSelected(true);
            else
                   ckb38Aposentadoria.setSelected(false);
            
            if (conexao.resultSet.getString("38seguro").equals("1"))
                   ckb38SeguroDesemprego.setSelected(true);
            else
                   ckb38SeguroDesemprego.setSelected(false);
            
            if (conexao.resultSet.getString("38bolsa_familia").equals("1"))
                   ckb38BolsaFamilia.setSelected(true);
            else
                   ckb38BolsaFamilia.setSelected(false);
              
            cb39AchaSuficiente.setSelectedItem(conexao.resultSet.getString("39e_suficiente"));

            if (conexao.resultSet.getString("40existe_monitoramento").equals("1"))
                   ckb40Sim.setSelected(true);
            else
                   ckb40Sim.setSelected(false);
            
            tp41Quem.setText(conexao.resultSet.getString("41quem_faz"));

            if (conexao.resultSet.getString("42tem_local").equals("1"))
                   ckb42Sim.setSelected(true);
            else
                   ckb42Sim.setSelected(false);
            
            cb43Qualidade.setSelectedItem(conexao.resultSet.getString("43qualidade_local"));

            cb44Acompanha.setSelectedItem(conexao.resultSet.getString("44acompanha"));

        } catch (Exception e) {
            System.out.println("Erro na exibição");
        }

    }

    private int tachecado(JCheckBox ckb) {
        if (ckb.isSelected()){
            return 1;
        }else
            return 0;
    }

    private void limpar_dados() {


                    ckb12TemPresidente.setSelected(false);
                    tf12NomePresidente.setText("");

                    cb13.setSelectedIndex(0);
                    tp15descrever.setText("");
                    ckb16.setSelected(false);

                    ckb17EstarQuite.setSelected(false);
                    ckb17TerTempo.setSelected(false);
                    ckb17Outro.setSelected(false);

                    tf17Outro.setText("");
                    tp18QuantaseQuais.setText("");
                    ckb19Sim.setSelected(false);

                    tp20TipoConflito.setText("");
                    ckb21EntreEles.setSelected(false);
                    ckb21ComLiderancas.setSelected(false);
                    ckb21ComIdosos.setSelected(false);

                    ckb21ComJustica.setSelected(false);
                    ckb21ComIBAMA.setSelected(false);
                    ckb21ComColonia.setSelected(false);
                    ckb21Outro.setSelected(false);

                    tf21Outro.setText("");
                    ckb22Sim.setSelected(false);
                    tp22.setText("");

                    tf23Homens.setText("0");
                    tf23Mulheres.setText("0");
                    tf24NrEmbarc.setText("0");
                    tf25MON.setText("0");
                    tf26CAN.setText("0");
                    tf27CAM.setText("0");
                    tf28BPP.setText("0");

                    tf29BMP.setText("0");
                    tf30GEL.setText("0");
                    tf31BIN.setText("0");
                    tfFno.setText("0");
                    tfPagantes.setText("");
                    tfInadiplentes.setText("");

                    cb35.setSelectedIndex(0);
                    ckb36Defeso.setSelected(false);
                    cb37.setSelectedIndex(0);

                    ckb38Aposentadoria.setSelected(false);
                    ckb38SeguroDesemprego.setSelected(false);
                    ckb38BolsaFamilia.setSelected(false);
                    cb39AchaSuficiente.setSelectedIndex(0);

                    ckb40Sim.setSelected(false);
                    tp41Quem.setText("");
                    ckb42Sim.setSelected(false);
                    cb43Qualidade.setSelectedIndex(0);

                    cb44Acompanha.setSelectedIndex(0);

    }


        public void preencher_jtableAtividade(String id){
        conexao.execute("select * from colonia_atividade where id_colonia="+id);

        jtAtividade.getColumnModel().getColumn(0).setMaxWidth(0);
        jtAtividade.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtAtividade.getColumnModel().getColumn(1).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(2).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(3).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(4).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(5).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(6).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(7).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(8).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(9).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(10).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(11).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(12).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(13).setPreferredWidth(10);

        DefaultTableModel modelo = (DefaultTableModel)jtAtividade.getModel();
        modelo.setNumRows(0);//limpa o JTable;

        try{
            while (conexao.resultSet.next())
                modelo.addRow(new Object[]{conexao.resultSet.getString("id_atividade"),
                                           conexao.resultSet.getString("tipo"),
                                          sim_nao( conexao.resultSet.getString("jan") ),
                                          sim_nao( conexao.resultSet.getString("fev") ),
                                          sim_nao( conexao.resultSet.getString("mar") ),
                                          sim_nao( conexao.resultSet.getString("abr") ),
                                          sim_nao( conexao.resultSet.getString("mai") ),
                                          sim_nao( conexao.resultSet.getString("jun") ),
                                          sim_nao( conexao.resultSet.getString("jul") ),
                                          sim_nao( conexao.resultSet.getString("ago") ),
                                          sim_nao( conexao.resultSet.getString("sett") ),
                                          sim_nao( conexao.resultSet.getString("out") ),
                                          sim_nao( conexao.resultSet.getString("nov") ),
                                          sim_nao( conexao.resultSet.getString("dez") )});

            conexao.resultSet.first();

        //conexao.execute("select * from caminhoneiro_questionario");
        }catch (SQLException erro){
            System.out.println(erro);
        }
    }

     private String sim_nao(String i){
         if (i.equals("1") )
             return "S";
         else
             return "";
     }

}
