/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * colonia_questionario.java
 *
 * Created on 05/08/2010, 12:52:55
 */

package br.com.bean.view.colonia;

import br.com.Persistencia.Conexao;
import java.sql.SQLException;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MPA
 */
public class colonia_questionario extends javax.swing.JFrame {
    private Conexao conexao;
    int inicia_combo = 0;
    String id_atravessador;
    String ItemDoCb;
    /** Creates new form colonia_questionario */
    public colonia_questionario() {
        initComponents();
        conexao = new Conexao();
        conexao.conecta("mil_interface");

                //Insere nome no cbNomeAtravessador
                try {
                    cbComunidade.removeAllItems();
                    conexao.execute("select * from colonia_cadastro");

                    while (conexao.resultSet.next()){
                        cbComunidade.addItem(conexao.resultSet.getString("id_colonia")+
                                                       " # "+ conexao.resultSet.getString("colonia"));
                    }
                }catch (SQLException ex) {
                    System.out.println(ex);
                }

        conexao.execute("select * from colonia_questionario");
        try {
            conexao.resultSet.first();
        } catch (SQLException ex) {
            System.out.println(ex+" linha 52");
        }
         mostra_dados();
         preencher_jtableEspecie(pega_codigo_ou_nome(1,cbComunidade.getSelectedItem().toString()));
         preencher_jtableAtividade(pega_codigo_ou_nome(1,cbComunidade.getSelectedItem().toString()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbComunidade = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf17Outro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf25MON = new javax.swing.JTextField();
        tf24NrEmbarc = new javax.swing.JTextField();
        tf26CAN = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf27CAM = new javax.swing.JTextField();
        tf28BPP = new javax.swing.JTextField();
        tf29BMP = new javax.swing.JTextField();
        tf30GEL = new javax.swing.JTextField();
        tf31BIN = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfFno = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfPagantes = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfInadiplentes = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        tf12NomePresidente = new javax.swing.JTextField();
        ckb12TemPresidente = new javax.swing.JCheckBox();
        jScrollPane7 = new javax.swing.JScrollPane();
        tp15descrever = new javax.swing.JTextPane();
        ckb16 = new javax.swing.JCheckBox();
        ckb36Defeso = new javax.swing.JCheckBox();
        ckb38Aposentadoria = new javax.swing.JCheckBox();
        ckb38SeguroDesemprego = new javax.swing.JCheckBox();
        ckb38BolsaFamilia = new javax.swing.JCheckBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtAtividade = new javax.swing.JTable();
        btAtualizarAtividade = new javax.swing.JButton();
        btExcluirAtividade = new javax.swing.JButton();
        btAddAtividade = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        botao_salvar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cb34 = new javax.swing.JComboBox();
        cb37 = new javax.swing.JComboBox();
        jScrollPane9 = new javax.swing.JScrollPane();
        tp18QuantaseQuais = new javax.swing.JTextPane();
        cb13 = new javax.swing.JComboBox();
        ckb17EstarQuite = new javax.swing.JCheckBox();
        ckb17TerTempo = new javax.swing.JCheckBox();
        ckb17Outro = new javax.swing.JCheckBox();
        ckb19Sim = new javax.swing.JCheckBox();
        jScrollPane12 = new javax.swing.JScrollPane();
        tp20TipoConflito = new javax.swing.JTextPane();
        ckb21EntreEles = new javax.swing.JCheckBox();
        ckb21ComLiderancas = new javax.swing.JCheckBox();
        ckb21ComIdosos = new javax.swing.JCheckBox();
        ckb21ComJustica = new javax.swing.JCheckBox();
        ckb21ComIBAMA = new javax.swing.JCheckBox();
        ckb21ComColonia = new javax.swing.JCheckBox();
        ckb21NaPolicia = new javax.swing.JCheckBox();
        ckb21Outro = new javax.swing.JCheckBox();
        tf21Outro = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        ckb22Sim = new javax.swing.JCheckBox();
        jLabel57 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tp22 = new javax.swing.JTextPane();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        tf23Homens = new javax.swing.JTextField();
        tf23Mulheres = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        cb39AchaSuficiente = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        ckb40Sim = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tp41Quem = new javax.swing.JTextPane();
        jLabel29 = new javax.swing.JLabel();
        ckb42Sim = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        cb43Qualidade = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        cb44Acompanha = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setText("Forma de Organização da Comunidade");

        jLabel2.setText("Comunidade:");

        cbComunidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbComunidadeActionPerformed(evt);
            }
        });

        jLabel3.setText("12.Tem Presidente:");

        jLabel4.setText("12.1 Nome:");

        jLabel6.setText("13. A colônia realiza periodicamente reuniões com os pescadores?");

        jLabel7.setText("15. Descrever:");

        jLabel8.setText("16. A eleição do presidente da colônia é realizada em reunião com os pescadores?");

        jLabel9.setText("17. Qual o critério para votar?");

        tf17Outro.setEditable(false);

        jLabel10.setText("18. Quantas e quais comunidades fazem parte da colônia? (Descrever).");

        jLabel11.setText("19. Nos ultimos 3 anos, houve algum tipo de conflito entre pescadores no qual a colônia tenha se envolvido?");

        jLabel12.setText("20. Se sim, qual o tipo de conflito mais comum?");

        jLabel13.setText("21. Como as pessoas resolvem os conflitos?");

        tf25MON.setText("0");

        tf24NrEmbarc.setText("0");

        tf26CAN.setText("0");
        tf26CAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf26CANActionPerformed(evt);
            }
        });

        jLabel16.setText("25. MON");

        jLabel17.setText("26. CAN ");

        jLabel18.setText("28. BPP");

        jLabel20.setText("29. BMP");

        jLabel21.setText("30. GEL");

        jLabel22.setText("31. BIN");

        tf27CAM.setText("0");
        tf27CAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf27CAMActionPerformed(evt);
            }
        });

        tf28BPP.setText("0");

        tf29BMP.setText("0");

        tf30GEL.setText("0");

        tf31BIN.setText("0");

        jLabel23.setText("32.Estimativa do número de embarcações financiadas pelo FNO:");

        tfFno.setText("0");

        jLabel24.setText("33. Situação do financiamento: Pagantes");

        jLabel25.setText("34. Situação do Financiamento: Inadiplentes");

        jLabel26.setText("35. A colônia acha os financiamentos da administrção pública importante para a atividade de pesca ?");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel27.setText("Caracterização da Pesca");

        jLabel31.setText("36. Na comunidade existem algum tipo de defeso?");

        jLabel32.setText("37. Existindo defeso,ele é respeitado?");

        jLabel33.setText("38. Os pescadores recebem algum tipo de auxílio ?");

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel48.setText("Atividades");

        tf12NomePresidente.setEditable(false);

        ckb12TemPresidente.setText("Sim");
        ckb12TemPresidente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckb12TemPresidenteStateChanged(evt);
            }
        });
        ckb12TemPresidente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb12TemPresidenteItemStateChanged(evt);
            }
        });

        jScrollPane7.setViewportView(tp15descrever);

        ckb16.setText("Sim");
        ckb16.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckb16StateChanged(evt);
            }
        });

        ckb36Defeso.setText("Sim");

        ckb38Aposentadoria.setText("Aposentadoria");

        ckb38SeguroDesemprego.setText("Seguro desemprego/Seguro defeso");

        ckb38BolsaFamilia.setText("Bolsa família");

        jtAtividade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_atividade", "Nome da Atividade", "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"
            }
        ));
        jScrollPane8.setViewportView(jtAtividade);

        btAtualizarAtividade.setText("Atualizar");
        btAtualizarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarAtividadeActionPerformed(evt);
            }
        });

        btExcluirAtividade.setText("Excluir");
        btExcluirAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirAtividadeActionPerformed(evt);
            }
        });

        btAddAtividade.setText("Add");
        btAddAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddAtividadeActionPerformed(evt);
            }
        });

        botao_salvar.setText("Salvar");
        botao_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_salvarActionPerformed(evt);
            }
        });

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cb34.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Um pouco", "Mais ou Menos", "Bastante" }));

        cb37.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Um pouco", "Mais ou Menos", "Bastante" }));

        jScrollPane9.setViewportView(tp18QuantaseQuais);

        cb13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não realiza", "Realiza mensalmente", "Realiza trimestralmente", "Realiza", "Realiza ocasionalmente/raramente", "Outros" }));

        ckb17EstarQuite.setText("Estar quite com a contribuição junto à colônia?");

        ckb17TerTempo.setText("Ter um tempo mínimo como associado?");

        ckb17Outro.setText("Outro");
        ckb17Outro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb17OutroItemStateChanged(evt);
            }
        });

        ckb19Sim.setText("Sim");

        jScrollPane12.setViewportView(tp20TipoConflito);

        ckb21EntreEles.setText("Entre eles");

        ckb21ComLiderancas.setText("Com lideranças da comunidade");

        ckb21ComIdosos.setText("Com os idosos/Mais velhos da comunidade");

        ckb21ComJustica.setText("Com justiça");

        ckb21ComIBAMA.setText("Com IBAMA");

        ckb21ComColonia.setText("Com a colônia de pescadores");
        ckb21ComColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb21ComColoniaActionPerformed(evt);
            }
        });

        ckb21NaPolicia.setText("Na Polícia");

        ckb21Outro.setText("Outro");

        jLabel56.setText("22. Existe associações, cooperativas ou outras formas de organização social?");

        ckb22Sim.setText("Sim");
        ckb22Sim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb22SimItemStateChanged(evt);
            }
        });

        jLabel57.setText("22.1. Especifique:");

        jScrollPane2.setViewportView(tp22);

        jLabel58.setText("23. Nº de pescadores associados: Homens:");

        jLabel59.setText("Mulheres:");

        jLabel60.setText("24. Estimativa do total de embarcações dos associados (somatória de todos)");

        jLabel14.setText("27. CAM");

        jLabel15.setText("39. Você acha suficiente o valor do seguro desemprego/seguro defeso recebido do governo durante o defeso?");

        cb39AchaSuficiente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Mais ou Menos", "Suficiente" }));

        jLabel19.setText("40. Existe algum monitoramento para estimular a produção do município?");

        ckb40Sim.setText("Sim");
        ckb40Sim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb40SimItemStateChanged(evt);
            }
        });

        jLabel28.setText("41. Se sim, quem o faz?");

        tp41Quem.setEditable(false);
        jScrollPane3.setViewportView(tp41Quem);

        jLabel29.setText("42. O Municipio tem um local especifico para o desembarque do pescado?");

        ckb42Sim.setText("Sim");

        jLabel30.setText("43. Havendo local, este é de qualidade?");

        cb43Qualidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Parcialmente", "Sim" }));

        jLabel34.setText("44. A colônia acompanha o período de defeso junto aos seus associados?");

        cb44Acompanha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Parcialmente", "Sim" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbComunidade, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckb12TemPresidente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf12NomePresidente))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cb13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ckb16))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(ckb17EstarQuite)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckb17TerTempo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(ckb17Outro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf17Outro, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckb21EntreEles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb21ComLiderancas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb21ComIdosos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckb21ComJustica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb21ComIBAMA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb21ComColonia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb21NaPolicia))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckb21Outro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf21Outro, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel56)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb22Sim))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel27)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf23Homens, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf23Mulheres, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb19Sim))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel25)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfInadiplentes, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel24)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfPagantes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel21)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(tf30GEL))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel16)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tf25MON, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel17)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tf26CAN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel22)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(tf31BIN)))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel14)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tf27CAM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel18)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tf28BPP))
                                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel20)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tf29BMP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(tfFno, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addGap(11, 11, 11)
                                                .addComponent(cb34, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ckb36Defeso))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel32)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cb37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel48)
                                                .addGap(145, 145, 145))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btAddAtividade)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btExcluirAtividade)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btAtualizarAtividade))
                                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(botao_salvar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2))
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(ckb38Aposentadoria)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(ckb38SeguroDesemprego)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(ckb38BolsaFamilia))
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel28)
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel19)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(ckb40Sim))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel29)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel30)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cb43Qualidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(jLabel34))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(ckb42Sim)
                                                            .addComponent(cb44Acompanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cb39AchaSuficiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel60)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf24NrEmbarc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbComunidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ckb12TemPresidente)
                            .addComponent(jLabel4)
                            .addComponent(tf12NomePresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb16)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb17EstarQuite)
                    .addComponent(ckb17TerTempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf17Outro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckb17Outro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ckb19Sim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb21EntreEles)
                    .addComponent(ckb21ComLiderancas)
                    .addComponent(ckb21ComIdosos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb21ComJustica)
                    .addComponent(ckb21ComIBAMA)
                    .addComponent(ckb21ComColonia)
                    .addComponent(ckb21NaPolicia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb21Outro)
                    .addComponent(tf21Outro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(ckb22Sim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(tf23Homens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59)
                    .addComponent(tf23Mulheres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(tf24NrEmbarc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf25MON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tf26CAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tf27CAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(tf28BPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(tf29BMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf30GEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(tf31BIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfFno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(tfPagantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfInadiplentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cb34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(ckb36Defeso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(cb37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb38Aposentadoria)
                    .addComponent(ckb38SeguroDesemprego)
                    .addComponent(ckb38BolsaFamilia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cb39AchaSuficiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ckb40Sim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(ckb42Sim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(cb43Qualidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(cb44Acompanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluirAtividade)
                    .addComponent(btAddAtividade)
                    .addComponent(btAtualizarAtividade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_salvar)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf27CAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf27CAMActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf27CAMActionPerformed

    private void tf26CANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf26CANActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf26CANActionPerformed

    private void ckb12TemPresidenteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckb12TemPresidenteStateChanged
        
    }//GEN-LAST:event_ckb12TemPresidenteStateChanged

    private void ckb16StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckb16StateChanged
        
    }//GEN-LAST:event_ckb16StateChanged

    private void botao_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_salvarActionPerformed
        try {
            String sqlinsert = "insert into colonia_questionario "
                    + "(id_colonia,tem_presidente,nome_presidente,"
                    + "tem_eleicao_presidencial,descricao_eleicao,existe_igreja,"
                    + "quant_igreja,existe_club,quant_club,"
                    + "exite_assoc,especificar_associacao,nr_pescadores,"
                    + "nr_embarcacoes,24mon,25can,"
                    + "26cam,27bpp,28bmp,29gel,30bin,31fno,"
                    + "sit_pagantes,sit_inadimplentes,34fin_adm_important,"
                    + "princ_pesc_ordem_importancia,artes_pesc_ordem_importancia,existe_defeso,"
                    + "e_respeitado,40rec_auxilio_renda,40rec_auxilio_aposentadoria,"                  
                    + "40rec_auxilio_seguro,acha_suf_valor_recebido,45exite_monitoramento,"
                    + "47tem_desembarque,48destino_consumo,48destino_venda,"
                    + "49producao_feita_na,49producao_feita_na_outro,50ramal,"
                    + "50estrada,50rio,50mangue,50outro,50outro_qual,"
                    + "51onibus,51barco,51bicicleta,51pe,"
                    + "52alvenaria,52madeira,52barro,52palha,"
                    + "53telha_de_barro,53quant_telha_de_barro,53cavaco,"
                    + "53quant_cavaco,53amianto,53quant_amianto,"
                    + "54terra_batida,54quant_terra_batida,54cimentado,54quant_cimentado,54lajotado,54quant_lajotado,"
                    + "55quant_mercearias,55quant_bares,"
                    + "55quant_mercearia_bar,52alvenaria_qtd,52madeira_qtd,"
                    + "52barro_qtd,52palha_qtd,"
                    + "42houve_conflito,43conflito_tipo,"
                    + "44entre_eles,44com_lideranca,44com_idosos_pessoas,"
                    + "46quem_faz) values ("+

                    pega_codigo_ou_nome(1,cbComunidade.getSelectedItem().toString())+","+
                    tachecado(ckb12TemPresidente) +",'"+ //tem presidente?
                    tf12NomePresidente.getText()+"',"+

                    tachecado(ckb14temeleicao)+",'"+ //tem_eleicao_presidencial?
                    tp15descrever.getText()+"',"+ //,descricao_eleicao
                    tachecado(ckb16)+","+ //,existe_igreja,"

                    tf17Outro.getText()+","+//"quant_igreja
                    tachecado(ckb18ExisteClube)+",'"+//,existe_club
                    tp18QuantaseQuais.getText()+"',"+//,quant_club,"

                    tachecado(ckb20ExisteAssociacao)+",'"+// "exite_assoc
                    tp21Especificar.getText()+"',"+//especificar_associacao
                    tf25MON.getText()+","+//nr_pescadores,"

                    tf24NrEmbarc.getText()+","+//nr_embarcacoes
                    tf26CAN.getText()+","+//24mon
                    tf27CAM.getText()+","+//25can,"

                    tf28BPP.getText()+","+//"26cam
                    tf29BMP.getText()+","+//27bpp
                    tf30GEL.getText()+","+//28bmp
                    tfGel.getText()+","+//29gel
                    tf31BIN.getText()+","+//30bin
                    tfFno.getText()+",'"+//31fno

                    tfPagantes.getText()+"','"+//"sit_pagantes
                    tfInadiplentes.getText()+"','"+//,sit_inadimplentes
                    cb34.getSelectedItem()+"','"+//,34fin_adm_important

                    tp35.getText()+"','"+//+ "princ_pesc_ordem_importancia
                    tp36.getText()+"',"+//,artes_pesc_ordem_importancia
                    tachecado(ckb36Defeso)+",'"+//,existe_defeso,"

                    cb37.getSelectedItem()+"',"+//+ "e_respeitado
                    tachecado(ckb38Aposentadoria)+","+//,40rec_auxilio_renda
                    tachecado(ckb38SeguroDesemprego)+","+//,40rec_auxilio_aposentadoria,"

                    tachecado(ckb38BolsaFamilia)+",'"+// "40rec_auxilio_seguro
                    cb41axasuf.getSelectedItem()+"',"+//,acha_suf_valor_recebido
                    tachecado(ckb45Sim)+","+//,45exite_monitoramento,"

                    tachecado(ckb47)+",'"+//"47tem_desembarque
                    cb48Consumo.getSelectedItem()+"','"+//,44destino_consumo
                    cb48Venda.getSelectedItem()+"','"+//,44destino_venda,"

                    cb49ProducaoVenda.getSelectedItem()+"','"+//+ "45producao_feita_na
                    tf49OutrasLocalidades.getText()+"',"+//,45producao_feita_na_outro
                    tachecado(ckb50Ramal)+","+//,46ramal,"

                    tachecado(ckb50Estrada)+","+//"46estrada
                    tachecado(ckb50Riu)+","+//,46rio
                    tachecado(ckb50Mangue)+","+//,46mangue
                    tachecado(ckb50Outro)+",'"+//,46outro
                    tf50Outro.getText()+"',"+//,46outro_qual,"

                    tachecado(ckb51Onibus)+","+//"47onibus
                    tachecado(ckb51Barco)+","+//,47barco
                    tachecado(ckb51Bicicleta)+","+//47bicicleta
                    tachecado(ckb51ape)+","+//,47pe,"
                    
                    tachecado(ckb52Alvenaria)+","+//"48alvenaria
                    tachecado(ckb52Madeira)+","+//,48madeira
                    tachecado(ckb52Barro)+","+//,48barro
                    tachecado(ckb52Palha)+","+//,48palha,"
                    
                    tachecado(ckb53TelhadeBarro)+","+//"49telha_de_barro
                    tf53TelhadeBarro.getText()+","+//,49quant_telha_de_barro
                    tachecado(ckb53Cavaco)+","+//,49cavaco,"
                    
                    tf53Cavaco.getText()+","+//"49quant_cavaco
                    tachecado(ckb53Amianto)+","+//,49amianto
                    tf53Amianto.getText()+","+//,49quant_amianto,"
                    
                    tachecado(ckb54TerraBatida)+","+//"50terra_batida
                    tf54TerraBatida.getText()+","+//,50quant_terra_batida
                    tachecado(ckb54Cimentado)+","+//,50cimentado
                    tf54Cimentado.getText()+","+//,50quant_cimentado
                    tachecado(ckb54Lajotado)+","+//,50lajotado
                    tf54Lajotado.getText()+","+//,50quant_lajotado,"
                    
                    tf55mercearias.getText()+","+//51quant_mercearias
                    tf55bares.getText()+","+//51quant_bares,"
                    tf55merceariaEbar.getText()+","+//51quant_mercearia_bar

            //a partir daqui não segue a ordem, é só as mudanças! Dane-se!
            tf52Alvenaria.getText()+","+
            tf52Madeira.getText()+","+
            tf52Barro.getText()+","+
            tf52Palha.getText()+","+

            tachecado(ckb42sim)+",'"+//42houve_conflito
            tp43ConflitoTipo.getText()+"',"+//43conflito_tipo,"
            tachecado(ckb44EntreEles)+","+//44entre_eles,
            tachecado(ckb44Lideranca)+","+//44com_lideranca,
            tachecado(ckb44Idosos)+",'"+//44com_idosos_pessoas,"
            tp46quemfaz.getText()+"')";//46quem_faz

                    System.out.println(sqlinsert);
                    
            if (conexao.salvar(sqlinsert)){
            //agora é hora de atualizar o resultset
            JOptionPane.showMessageDialog(null,"Cadastrado com sucesso");
            conexao.execute("select * from colonia_questionario");
            conexao.resultSet.first(); //1º registro
            mostra_dados();
            cbComunidade.setSelectedIndex(0);
            }

        }catch (SQLException erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_botao_salvarActionPerformed

    private void cbComunidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbComunidadeActionPerformed

        //Pesquisa automática do Combo Box Nome do atravessador

        if (inicia_combo == 1){
         try {
            conexao.execute("select * from colonia_questionario");
            conexao.resultSet.first();
            String igual = "n"; //inicia dizendo que não localizou
            while(igual == "n") //diz que enquanto não localizar é para ir executando
            {
                String id = pega_codigo_ou_nome(1,cbComunidade.getSelectedItem().toString());
                if (conexao.resultSet.getString("id_colonia").equals(id)) {
                    igual = "s"; //incica que achou
                } else
                    conexao.resultSet.next();
            }
            //nas linhas abaixo, mostra_conteudo_tabela();
             limpar_dados();
             mostra_dados();
             preencher_jtableEspecie(pega_codigo_ou_nome(1,cbComunidade.getSelectedItem().toString()));
             preencher_jtableAtividade(pega_codigo_ou_nome(1,cbComunidade.getSelectedItem().toString()));


        } catch (SQLException ex) {
            limpar_dados();
            preencher_jtableEspecie(pega_codigo_ou_nome(1,cbComunidade.getSelectedItem().toString()));
            preencher_jtableAtividade(pega_codigo_ou_nome(1,cbComunidade.getSelectedItem().toString()));
            System.out.println(ex+" Erro na troca do combobox");
            }
        }inicia_combo = 1;
    }//GEN-LAST:event_cbComunidadeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try{
            String sql ="UPDATE colonia_questionario SET "+
                          "tem_presidente = '"+tachecado(ckb12TemPresidente)+"',"+
                          "nome_presidente = '"+ tf12NomePresidente.getText() +"',"+
                          "tem_eleicao_presidencial = '"+ tachecado(ckb14temeleicao) +"',"+
                          "descricao_eleicao = '"+ tp15descrever.getText() +"',"+
                          "existe_igreja = '"+ tachecado(ckb16) +"',"+
                          "quant_igreja = '"+ tf17Outro.getText() +"',"+
                          "existe_club = '"+ tachecado(ckb18ExisteClube) +"',"+
                          "quant_club = '"+ tp18QuantaseQuais.getText() +"',"+
                          "exite_assoc = '"+ tachecado(ckb20ExisteAssociacao) +"',"+
                          "especificar_associacao = '"+ tp21Especificar.getText() +"',"+
                          "nr_pescadores = '"+ tf25MON.getText() +"',"+
                          "nr_embarcacoes = '"+ tf24NrEmbarc.getText() +"',"+
                          "24mon = '"+ tf26CAN.getText() +"',"+
                          "25can = '"+ tf27CAM.getText() +"',"+
                          "26cam = '"+ tf28BPP.getText() +"',"+
                          "27bpp = '"+ tf29BMP.getText() +"',"+
                          "28bmp = '"+ tf30GEL.getText() +"',"+
                          "29gel = '"+ tfGel.getText() +"',"+
                          "30bin = '"+ tf31BIN.getText() +"',"+
                          "31fno = '"+ tfFno.getText() +"',"+
                          "sit_pagantes = '"+ tfPagantes.getText() +"',"+
                          "sit_inadimplentes = '"+ tfInadiplentes.getText() +"',"+
                          "34fin_adm_important = '"+ cb34.getSelectedItem() +"',"+
                          "princ_pesc_ordem_importancia = '"+ tp35.getText() +"',"+
                          "artes_pesc_ordem_importancia = '"+ tp36.getText() +"',"+
                          "existe_defeso = '"+ tachecado(ckb36Defeso) +"',"+
                          "e_respeitado = '"+ cb37.getSelectedItem() +"',"+
                          "40rec_auxilio_renda = '"+ tachecado(ckb38Aposentadoria) +"',"+
                          "40rec_auxilio_aposentadoria = '"+ tachecado(ckb38SeguroDesemprego) +"',"+

                          "40rec_auxilio_seguro = '"+ tachecado(ckb38BolsaFamilia) +"',"+
                          "acha_suf_valor_recebido = '"+ cb41axasuf.getSelectedItem() +"',"+
                          "45exite_monitoramento = '"+ tachecado(ckb45Sim) +"',"+
                          "47tem_desembarque = '"+ tachecado(ckb47) +"',"+
                          "48destino_consumo = '"+ cb48Consumo.getSelectedItem() +"',"+
                          "48destino_venda = '"+ cb48Venda.getSelectedItem() +"',"+
                          "49producao_feita_na = '"+ cb49ProducaoVenda.getSelectedItem() +"',"+
                          "49producao_feita_na_outro = '"+ tf49OutrasLocalidades.getText() +"',"+
                          "50ramal = '"+ tachecado(ckb50Ramal) +"',"+
                          "50estrada = '"+ tachecado(ckb50Estrada) +"',"+
                          "50rio = '"+ tachecado(ckb50Riu) +"',"+
                          "50mangue = '"+ tachecado(ckb50Mangue) +"',"+
                          "50outro = '"+ tachecado(ckb50Outro) +"',"+
                          "50outro_qual = '"+ tf50Outro.getText() +"',"+
                          "51onibus = '"+ tachecado(ckb51Onibus) +"',"+

                          "51barco = '"+ tachecado(ckb51Barco) +"',"+
                          "51bicicleta = '"+ tachecado(ckb51Bicicleta) +"',"+
                          "51pe = '"+ tachecado(ckb51ape) +"',"+
                          "52alvenaria = '"+ tachecado(ckb52Alvenaria) +"',"+
                          "52madeira = '"+ tachecado(ckb52Madeira) +"',"+
                          "52barro = '"+ tachecado(ckb52Barro) +"',"+
                          "52palha = '"+ tachecado(ckb52Palha) +"',"+
                          "53telha_de_barro = '"+ tachecado(ckb53TelhadeBarro) +"',"+
                          "53quant_telha_de_barro = '"+ tf53TelhadeBarro.getText() +"',"+
                          "53cavaco = '"+ tachecado(ckb53Cavaco) +"',"+
                          "53quant_cavaco = '"+ tf53Cavaco.getText() +"',"+

                          "53amianto = '"+ tachecado(ckb53Amianto) +"',"+
                          "53quant_amianto = '"+ tf53Amianto.getText() +"',"+
                          "54terra_batida = '"+ tachecado(ckb54TerraBatida) +"',"+
                          "54quant_terra_batida = '"+ tf54TerraBatida.getText() +"',"+
                          "54cimentado = '"+ tachecado(ckb54Cimentado) +"',"+
                          "54quant_cimentado = '"+ tf54Cimentado.getText() +"',"+
                          "54lajotado = '"+ tachecado(ckb54Lajotado) +"',"+
                          "54quant_lajotado = '"+ tf54Lajotado.getText() +"',"+
                          "55quant_mercearias = '"+ tf55mercearias.getText() +"',"+
                          "55quant_bares = '"+ tf55bares.getText() +"',"+
                          "55quant_mercearia_bar = '"+ tf55merceariaEbar.getText() +"',"+
                          "52alvenaria_qtd = '"+ tf52Alvenaria.getText() +"',"+
                          "52madeira_qtd = '"+ tf52Madeira.getText() +"',"+
                          "52barro_qtd = '"+ tf52Barro.getText() +"',"+
                          "52palha_qtd = '"+ tf52Palha.getText() +"',"+

                          "42houve_conflito = '"+ tachecado(ckb42sim)+"',"+
                          "43conflito_tipo = '"+ tp43ConflitoTipo.getText()+"',"+
                          "44entre_eles = '"+ tachecado(ckb44EntreEles)+"',"+
                          "44com_lideranca = '"+ tachecado(ckb44Lideranca)+"',"+
                          "44com_idosos_pessoas = '"+ tachecado(ckb44Idosos)+"',"+
                          "46quem_faz = '"+ tp46quemfaz.getText()+"' "+

                          "where id_colonia = "+pega_codigo_ou_nome(1,cbComunidade.getSelectedItem().toString());

            System.out.println(sql);
            if (conexao.update(sql)){
            JOptionPane.showMessageDialog(null,"Alterado com sucesso");
            //Atualiza Resultset
            conexao.execute("select * from colonia_questionario");
            conexao.resultSet.next();
            mostra_dados();
            cbComunidade.setSelectedIndex(0);
            }


        }catch (Exception e){
            System.out.println(e + "Erro no botão alterar");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btAtualizarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarAtividadeActionPerformed
        preencher_jtableAtividade(pega_codigo_ou_nome(1,cbComunidade.getSelectedItem().toString()));
    }//GEN-LAST:event_btAtualizarAtividadeActionPerformed

    private void btAddAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddAtividadeActionPerformed
        new addAtividades(pega_codigo_ou_nome(1,cbComunidade.getSelectedItem().toString())).setVisible(true);
    }//GEN-LAST:event_btAddAtividadeActionPerformed

    private void btExcluirAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirAtividadeActionPerformed
        // TODO add your handling code here:
        System.out.println(jtAtividade.getValueAt(jtAtividade.getSelectedRow(),0));
        //.removeRow(jTable1.getSelectedRow());
                String sql;

            sql = "delete from colonia_addatividade Where id_atividade =" + jtAtividade.getValueAt(jtAtividade.getSelectedRow(),0);

                if (conexao.salvar(sql)) {
                    System.out.println("Exclusão realizada com sucesso");
                    //exibe
                    preencher_jtableAtividade(pega_codigo_ou_nome(1,cbComunidade.getSelectedItem().toString()));

                }else{
                JOptionPane.showMessageDialog(null,"Erro na exclusão");


                }
    }//GEN-LAST:event_btExcluirAtividadeActionPerformed

    private void ckb12TemPresidenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb12TemPresidenteItemStateChanged
        if (ckb12TemPresidente.isSelected()){
            tf12NomePresidente.setEditable(true);
        }else{
            tf12NomePresidente.setEditable(false);
            tf12NomePresidente.setText("");
        }
    }//GEN-LAST:event_ckb12TemPresidenteItemStateChanged

    private void ckb17OutroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb17OutroItemStateChanged
        if (ckb17Outro.isSelected())
            tf17Outro.setEditable(true);
        else{
            tf17Outro.setEditable(false);
            tf17Outro.setText("");
        }
    }//GEN-LAST:event_ckb17OutroItemStateChanged

    private void ckb21ComColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb21ComColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckb21ComColoniaActionPerformed

    private void ckb22SimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb22SimItemStateChanged
        if (ckb22Sim.isSelected())
            tp22.setEditable(true);
        else{
            tp22.setEditable(false);
            tp22.setText("");
        }
    }//GEN-LAST:event_ckb22SimItemStateChanged

    private void ckb40SimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb40SimItemStateChanged
        if (ckb40Sim.isSelected())
            tp41Quem.setEditable(true);
        else{
            tp41Quem.setEditable(false);
            tp41Quem.setText("");
        }
    }//GEN-LAST:event_ckb40SimItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new colonia_questionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_salvar;
    private javax.swing.JButton btAddAtividade;
    private javax.swing.JButton btAtualizarAtividade;
    private javax.swing.JButton btExcluirAtividade;
    private javax.swing.JComboBox cb13;
    private javax.swing.JComboBox cb34;
    private javax.swing.JComboBox cb37;
    private javax.swing.JComboBox cb39AchaSuficiente;
    private javax.swing.JComboBox cb43Qualidade;
    private javax.swing.JComboBox cb44Acompanha;
    private javax.swing.JComboBox cbComunidade;
    private javax.swing.JCheckBox ckb12TemPresidente;
    private javax.swing.JCheckBox ckb16;
    private javax.swing.JCheckBox ckb17EstarQuite;
    private javax.swing.JCheckBox ckb17Outro;
    private javax.swing.JCheckBox ckb17TerTempo;
    private javax.swing.JCheckBox ckb19Sim;
    private javax.swing.JCheckBox ckb21ComColonia;
    private javax.swing.JCheckBox ckb21ComIBAMA;
    private javax.swing.JCheckBox ckb21ComIdosos;
    private javax.swing.JCheckBox ckb21ComJustica;
    private javax.swing.JCheckBox ckb21ComLiderancas;
    private javax.swing.JCheckBox ckb21EntreEles;
    private javax.swing.JCheckBox ckb21NaPolicia;
    private javax.swing.JCheckBox ckb21Outro;
    private javax.swing.JCheckBox ckb22Sim;
    private javax.swing.JCheckBox ckb36Defeso;
    private javax.swing.JCheckBox ckb38Aposentadoria;
    private javax.swing.JCheckBox ckb38BolsaFamilia;
    private javax.swing.JCheckBox ckb38SeguroDesemprego;
    private javax.swing.JCheckBox ckb40Sim;
    private javax.swing.JCheckBox ckb42Sim;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jtAtividade;
    private javax.swing.JTextField tf12NomePresidente;
    private javax.swing.JTextField tf17Outro;
    private javax.swing.JTextField tf21Outro;
    private javax.swing.JTextField tf23Homens;
    private javax.swing.JTextField tf23Mulheres;
    private javax.swing.JTextField tf24NrEmbarc;
    private javax.swing.JTextField tf25MON;
    private javax.swing.JTextField tf26CAN;
    private javax.swing.JTextField tf27CAM;
    private javax.swing.JTextField tf28BPP;
    private javax.swing.JTextField tf29BMP;
    private javax.swing.JTextField tf30GEL;
    private javax.swing.JTextField tf31BIN;
    private javax.swing.JTextField tfFno;
    private javax.swing.JTextField tfInadiplentes;
    private javax.swing.JTextField tfPagantes;
    private javax.swing.JTextPane tp15descrever;
    private javax.swing.JTextPane tp18QuantaseQuais;
    private javax.swing.JTextPane tp20TipoConflito;
    private javax.swing.JTextPane tp22;
    private javax.swing.JTextPane tp41Quem;
    // End of variables declaration//GEN-END:variables

            public String pega_codigo_ou_nome(int n,String teste) { //Se entrar com 1 pega o Código, se não pega o Nome
              //pegar a Id do atravessador

              //aqui ele pega a quantidade de carcteres que tem uma determinada variável
              //e armazena numa INT para usá-la de contador
              int contador = teste.length();

              //cria um for( para fazer uma varredura letra por letra até encontrar
              for(int i = 0;i<contador;i++){
                 //usamos substring pra pegar um caractere, passando como parâmetro,
                 //o primeiro caractere a ser pega, até a ultima.
                //fiz um if para verificar se o caractere é igual a "#"
                if (teste.substring(i,i+1).equals("#")){
                   int posicao = i+1;
                    System.out.println("Está na posição " + posicao);
                    if (n == 1){
                        return teste.substring(0,posicao-2);
                    }
                    else
                        return teste.substring(posicao+1,teste.length());
                }

              }
              return "nada";
        }

    private void mostra_dados() {
        try {
            tf12NomePresidente.setText(conexao.resultSet.getString("nome_presidente"));
            tp15descrever.setText(conexao.resultSet.getString("descricao_eleicao"));
            tf17Outro.setText(conexao.resultSet.getString("quant_igreja"));
            tp18QuantaseQuais.setText(conexao.resultSet.getString("quant_club"));
            tp21Especificar.setText(conexao.resultSet.getString("especificar_associacao"));

            tf25MON.setText(conexao.resultSet.getString("nr_pescadores"));
            tf24NrEmbarc.setText(conexao.resultSet.getString("nr_embarcacoes"));
            tf26CAN.setText(conexao.resultSet.getString("24mon"));
            tf27CAM.setText(conexao.resultSet.getString("25can"));
            tf28BPP.setText(conexao.resultSet.getString("26cam"));
            tf29BMP.setText(conexao.resultSet.getString("27bpp"));
            tf30GEL.setText(conexao.resultSet.getString("28bmp"));
            tfGel.setText(conexao.resultSet.getString("29gel"));
            tf31BIN.setText(conexao.resultSet.getString("30bin"));
            tfFno.setText(conexao.resultSet.getString("31fno"));
            tfPagantes.setText(conexao.resultSet.getString("sit_pagantes"));
            tfInadiplentes.setText(conexao.resultSet.getString("sit_inadimplentes"));

            tp35.setText(conexao.resultSet.getString("princ_pesc_ordem_importancia"));
            tp36.setText(conexao.resultSet.getString("artes_pesc_ordem_importancia"));

            tf49OutrasLocalidades.setText(conexao.resultSet.getString("49producao_feita_na_outro"));

            cb34.setSelectedItem(conexao.resultSet.getString("34fin_adm_important"));
            cb37.setSelectedItem(conexao.resultSet.getString("e_respeitado"));
            cb41axasuf.setSelectedItem(conexao.resultSet.getString("acha_suf_valor_recebido"));
            cb48Consumo.setSelectedItem(conexao.resultSet.getString("48destino_consumo"));
            cb48Venda.setSelectedItem(conexao.resultSet.getString("48destino_venda"));
            cb49ProducaoVenda.setSelectedItem(conexao.resultSet.getString("49producao_feita_na"));
            //CheckBoxes
            if (conexao.resultSet.getString("tem_presidente").equals("1"))
                   ckb12TemPresidente.setSelected(true);
            else
                   ckb12TemPresidente.setSelected(false);

            if (conexao.resultSet.getString("tem_eleicao_presidencial").equals("1"))
                   ckb14temeleicao.setSelected(true);
            else
                   ckb14temeleicao.setSelected(false);

            if (conexao.resultSet.getString("existe_igreja").equals("1"))
                   ckb16.setSelected(true);
            else
                   ckb16.setSelected(false);

            if (conexao.resultSet.getString("existe_club").equals("1"))
                   ckb18ExisteClube.setSelected(true);
            else
                   ckb18ExisteClube.setSelected(false);

            if (conexao.resultSet.getString("exite_assoc").equals("1"))
                   ckb20ExisteAssociacao.setSelected(true);
            else
                   ckb20ExisteAssociacao.setSelected(false);

            //
            if (conexao.resultSet.getString("existe_defeso").equals("1"))
                   ckb36Defeso.setSelected(true);
            else
                   ckb36Defeso.setSelected(false);

            //
            if (conexao.resultSet.getString("40rec_auxilio_renda").equals("1"))
                   ckb38Aposentadoria.setSelected(true);
            else
                   ckb38Aposentadoria.setSelected(false);

            if (conexao.resultSet.getString("40rec_auxilio_aposentadoria").equals("1"))
                   ckb38SeguroDesemprego.setSelected(true);
            else
                   ckb38SeguroDesemprego.setSelected(false);

            if (conexao.resultSet.getString("40rec_auxilio_seguro").equals("1"))
                   ckb38BolsaFamilia.setSelected(true);
            else
                   ckb38BolsaFamilia.setSelected(false);

            //
            if (conexao.resultSet.getString("45exite_monitoramento").equals("1"))
                   ckb45Sim.setSelected(true);
            else
                   ckb45Sim.setSelected(false);

            if (conexao.resultSet.getString("47tem_desembarque").equals("1"))
                   ckb47.setSelected(true);
            else
                   ckb47.setSelected(false);


            //estrutura da comunidade
            if (conexao.resultSet.getString("50ramal").equals("1"))
                   ckb50Ramal.setSelected(true);
            else
                   ckb50Ramal.setSelected(false);

            if (conexao.resultSet.getString("50estrada").equals("1"))
                   ckb50Estrada.setSelected(true);
            else
                   ckb50Estrada.setSelected(false);

            if (conexao.resultSet.getString("50rio").equals("1"))
                   ckb50Riu.setSelected(true);
            else
                   ckb50Riu.setSelected(false);

            if (conexao.resultSet.getString("50mangue").equals("1"))
                   ckb50Mangue.setSelected(true);
            else
                   ckb50Mangue.setSelected(false);

            if (conexao.resultSet.getString("50outro").equals("1"))
                   ckb50Outro.setSelected(true);
            else
                   ckb50Outro.setSelected(false);

            tf50Outro.setText(conexao.resultSet.getString("50outro_qual"));

            //ckb51
            if (conexao.resultSet.getString("51onibus").equals("1"))
                   ckb51Onibus.setSelected(true);
            else
                   ckb51Onibus.setSelected(false);

            if (conexao.resultSet.getString("51barco").equals("1"))
                   ckb51Barco.setSelected(true);
            else
                   ckb51Barco.setSelected(false);

            if (conexao.resultSet.getString("51bicicleta").equals("1"))
                   ckb51Bicicleta.setSelected(true);
            else
                   ckb51Bicicleta.setSelected(false);

            if (conexao.resultSet.getString("51pe").equals("1"))
                   ckb51ape.setSelected(true);
            else
                   ckb51ape.setSelected(false);

            //ckb52
            if (conexao.resultSet.getString("52alvenaria").equals("1"))
                   ckb52Alvenaria.setSelected(true);
            else
                   ckb52Alvenaria.setSelected(false);

            if (conexao.resultSet.getString("52madeira").equals("1"))
                   ckb52Madeira.setSelected(true);
            else
                   ckb52Madeira.setSelected(false);

            if (conexao.resultSet.getString("52barro").equals("1"))
                   ckb52Barro.setSelected(true);
            else
                   ckb52Barro.setSelected(false);

            if (conexao.resultSet.getString("52palha").equals("1"))
                   ckb52Palha.setSelected(true);
            else
                   ckb52Palha.setSelected(false);

            tf52Alvenaria.setText(conexao.resultSet.getString("52alvenaria_qtd"));
            tf52Madeira.setText(conexao.resultSet.getString("52madeira_qtd"));
            tf52Barro.setText(conexao.resultSet.getString("52barro_qtd"));
            tf52Palha.setText(conexao.resultSet.getString("52palha_qtd"));

            //49
            if (conexao.resultSet.getString("53telha_de_barro").equals("1"))
                   ckb53TelhadeBarro.setSelected(true);
            else
                   ckb53TelhadeBarro.setSelected(false);

            if (conexao.resultSet.getString("53cavaco").equals("1"))
                   ckb53Cavaco.setSelected(true);
            else
                   ckb53Cavaco.setSelected(false);

            if (conexao.resultSet.getString("53amianto").equals("1"))
                   ckb53Amianto.setSelected(true);
            else
                   ckb53Amianto.setSelected(false);

            tf53TelhadeBarro.setText(conexao.resultSet.getString("53quant_telha_de_barro"));
            tf53Cavaco.setText(conexao.resultSet.getString("53quant_cavaco"));
            tf53Amianto.setText(conexao.resultSet.getString("53quant_amianto"));

            //54
            if (conexao.resultSet.getString("54terra_batida").equals("1"))
                   ckb54TerraBatida.setSelected(true);
            else
                   ckb54TerraBatida.setSelected(false);

            if (conexao.resultSet.getString("54cimentado").equals("1"))
                   ckb54Cimentado.setSelected(true);
            else
                   ckb54Cimentado.setSelected(false);

            if (conexao.resultSet.getString("54lajotado").equals("1"))
                   ckb54Lajotado.setSelected(true);
            else
                   ckb54Lajotado.setSelected(false);

            tf54TerraBatida.setText(conexao.resultSet.getString("54quant_terra_batida"));
            tf54Cimentado.setText(conexao.resultSet.getString("54quant_cimentado"));
            tf54Lajotado.setText(conexao.resultSet.getString("54quant_lajotado"));

            //55
            tf55mercearias.setText(conexao.resultSet.getString("55quant_mercearias"));
            tf55bares.setText(conexao.resultSet.getString("55quant_bares"));
            tf55merceariaEbar.setText(conexao.resultSet.getString("55quant_mercearia_bar"));

            //exibindo os novos dados
            if (conexao.resultSet.getString("42houve_conflito").equals("1"))
                   ckb42sim.setSelected(true);
            else
                   ckb42sim.setSelected(false);
            
            if (conexao.resultSet.getString("44entre_eles").equals("1"))
                   ckb44EntreEles.setSelected(true);
            else
                   ckb44EntreEles.setSelected(false);
            
            if (conexao.resultSet.getString("44com_lideranca").equals("1"))
                   ckb44Lideranca.setSelected(true);
            else
                   ckb44Lideranca.setSelected(false);
            
            if (conexao.resultSet.getString("44com_idosos_pessoas").equals("1"))
                   ckb44Idosos.setSelected(true);
            else
                   ckb44Idosos.setSelected(false);
            
            tp43ConflitoTipo.setText(conexao.resultSet.getString("43conflito_tipo"));
            tp46quemfaz.setText(conexao.resultSet.getString("46quem_faz"));

        } catch (Exception e) {
        }

    }

    private int tachecado(JCheckBox ckb) {
        if (ckb.isSelected()){
            return 1;
        }else
            return 0;
    }

    private void limpar_dados() {


                    ckb12TemPresidente.setSelected(false);
                    tf12NomePresidente.setText("");

                    ckb14temeleicao.setSelected(false);
                    tp15descrever.setText("");
                    ckb16.setSelected(false);

                    tf17Outro.setText("0");
                    ckb18ExisteClube.setSelected(false);
                    tp18QuantaseQuais.setText("0");

                    ckb20ExisteAssociacao.setSelected(false);
                    tp21Especificar.setText("");
                    tf25MON.setText("0");

                    tf24NrEmbarc.setText("0");
                    tf26CAN.setText("0");
                    tf27CAM.setText("0");

                    tf28BPP.setText("0");
                    tf29BMP.setText("0");
                    tf30GEL.setText("0");
                    tfGel.setText("0");
                    tf31BIN.setText("0");
                    tfFno.setText("0");

                    tfPagantes.setText("");
                    tfInadiplentes.setText("");
                    cb34.setSelectedIndex(0);

                    tp35.setText("");
                    tp36.setText("");
                    ckb36Defeso.setSelected(false);

                    cb37.setSelectedIndex(0);
                    ckb38Aposentadoria.setSelected(false);
                    ckb38SeguroDesemprego.setSelected(false);

                    ckb38BolsaFamilia.setSelected(false);
                    cb41axasuf.setSelectedIndex(0);
                    ckb45Sim.setSelected(false);

                    ckb47.setSelected(false);
                    cb48Consumo.setSelectedIndex(0);
                    cb48Venda.setSelectedIndex(0);

                    cb49ProducaoVenda.setSelectedIndex(0);
                    tf49OutrasLocalidades.setText("");
                    ckb50Ramal.setSelected(false);

                    ckb50Estrada.setSelected(false);
                    ckb50Riu.setSelected(false);
                    ckb50Mangue.setSelected(false);
                    ckb50Outro.setSelected(false);
                    tf50Outro.setText("");

                    ckb51Onibus.setSelected(false);
                    ckb51Barco.setSelected(false);
                    ckb51Bicicleta.setSelected(false);
                    ckb51ape.setSelected(false);

                    ckb52Alvenaria.setSelected(false);
                    ckb52Madeira.setSelected(false);
                    ckb52Barro.setSelected(false);
                    ckb52Palha.setSelected(false);

                    ckb53TelhadeBarro.setSelected(false);
                    tf53TelhadeBarro.setText("0");
                    ckb53Cavaco.setSelected(false);

                    tf53Cavaco.setText("0");
                    ckb53Amianto.setSelected(false);
                    tf53Amianto.setText("0");

                    ckb54TerraBatida.setSelected(false);
                    tf54TerraBatida.setText("0");
                    ckb54Cimentado.setSelected(false);
                    tf54Cimentado.setText("0");
                    ckb54Lajotado.setSelected(false);
                    tf54Lajotado.setText("0");

                    tf55mercearias.setText("0");
                    tf55bares.setText("0");
                    tf55merceariaEbar.setText("0");

                    tf52Alvenaria.setText("0");
                    tf52Madeira.setText("0");
                    tf52Barro.setText("0");
                    tf52Palha.setText("0");

                    ckb42sim.setSelected(false);
                    ckb44EntreEles.setSelected(false);
                    ckb44Idosos.setSelected(false);
                    ckb44Lideranca.setSelected(false);
                    tp46quemfaz.setText("");
                    tp43ConflitoTipo.setText("");

    }


        public void preencher_jtableAtividade(String id){
        conexao.execute("select * from colonia_addatividade where id_colonia="+id);

        jtAtividade.getColumnModel().getColumn(0).setMaxWidth(0);
        jtAtividade.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtAtividade.getColumnModel().getColumn(1).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(2).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(3).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(4).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(5).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(6).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(7).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(8).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(9).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(10).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(11).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(12).setPreferredWidth(10);
        jtAtividade.getColumnModel().getColumn(13).setPreferredWidth(10);

        DefaultTableModel modelo = (DefaultTableModel)jtAtividade.getModel();
        modelo.setNumRows(0);//limpa o JTable;

        try{
            while (conexao.resultSet.next())
                modelo.addRow(new Object[]{conexao.resultSet.getString("id_atividade"),
                                           conexao.resultSet.getString("tipo"),
                                          sim_nao( conexao.resultSet.getString("jan") ),
                                          sim_nao( conexao.resultSet.getString("fev") ),
                                          sim_nao( conexao.resultSet.getString("mar") ),
                                          sim_nao( conexao.resultSet.getString("abr") ),
                                          sim_nao( conexao.resultSet.getString("mai") ),
                                          sim_nao( conexao.resultSet.getString("jun") ),
                                          sim_nao( conexao.resultSet.getString("jul") ),
                                          sim_nao( conexao.resultSet.getString("ago") ),
                                          sim_nao( conexao.resultSet.getString("sett") ),
                                          sim_nao( conexao.resultSet.getString("out") ),
                                          sim_nao( conexao.resultSet.getString("nov") ),
                                          sim_nao( conexao.resultSet.getString("dez") )});

            conexao.resultSet.first();

        //conexao.execute("select * from caminhoneiro_questionario");
        }catch (SQLException erro){
            System.out.println(erro);
        }
    }

     private String sim_nao(String i){
         if (i.equals("1") )
             return "S";
         else
             return "";
     }

}
